### ISSUE TITLE
Does not support 12.0.20 version can't base64 decoding

### ISSUE THREAD

**Issue by xz00311** [DoubleLabyrinth/navicat-keygen#1]
Does not support 12.0.20 version can't base64 decoding X86

**Comment by DoubleLabyrinth** [comment]
Please provide your RegPrivateKey.pem content and your base64 request code.

**Comment by xz00311** [comment]
[RegPrivateKey.zip](https://github.com/DoubleLabyrinth/navicat-keygen/files/1557717/RegPrivateKey.zip)

RkY1Izc3ItmFcD3aT3BxSD5JArIMrP0W2JOvXMZnMzb3wz+fJXwLgJ6b26/JW9Qq86kzeKNX/Z6y
42BGPgHO/OKK5AY63F0aE/h7DPAXXJ5xy06mBoOjN6UvEcL/5uhs9MiHc9Gex9CtSXxSZJz8+SFn
1l8IPuwzWimdrZBwpRL44ewYpqV2uIKXnOCpTxj7eLdUvSkly/NkVSDde3siewNfvmB60/tomcBE
h6tlr+a28O6gLctFOYIKYcsJAyUM5Jvvsf1JLX67mMRhsYEC3wyO5Mz4aERnnVPGP2PPaq16g0RA
rDZz125qUwQW/ieCEkrlETQ/qbwNvAEeC0sz8Q==

It can be registered in the sandbox, but it doesn't work without a sandbar installation.

**Comment by DoubleLabyrinth** [comment]
It seems that you did not patch your navicat.exe. Or you've upgrade your Navicat but you did not patch navicat.exe again. Because I cannot decrypt your request code by the private key you provided.

Please make sure that your navicat.exe has been patched.

**Comment by xz00311** [comment]
Every time I have the path, I find the reason why some say reinstall after the failure, because the same machine can not use the same name and organization, each reinstall the name and the organization must not be registered before the same 100% unsuccessful
