### ISSUE TITLE
some info of Mac version

### ISSUE THREAD

**Issue by Wizr** [DoubleLabyrinth/navicat-keygen#10]
I did some investigation on Mac for Navicat Premium 12.0.19 (English).
I found something different:
1. data[5], d[6] are 0xAC, 0x88 (#4 )
2. `data[10]` is not standard base32 encoded, the alphabet table is `ABCDEFGH8JKLMN9PQRSTUVWXYZ234567`
3. `T` is mandatory, it is epoch time (seconds since 00:00:00 UTC, Thursday, 1 January 1970) (can be string or integer)

**Comment by DoubleLabyrinth** [comment]
Thanks for your discovery. The second item is very useful for me. Now I can know why some snKeys generated do not work.

**Comment by Deltafox79** [comment]
The maximum value of T can be January 18, 2038....
