### ISSUE TITLE
12.0.29.x64 繁體版 navicat-patcher error : The key is not appropriate to use

### ISSUE THREAD

**Issue by SyaoranChang** [DoubleLabyrinth/navicat-keygen#102]
版本: Navicat.Premium.v12.0.29.x64 繁體安裝檔
https://www.navicat.com/download/direct-download?product=navicat_premium_ct_x64.exe&location=1

使用 navicat-patcher 繁體版本出現錯誤訊息
導致 navicat-keygen 也無法成功取得 註冊碼

訊息
navicat-keygen_for_x64>navicat-patcher "C:\Program Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem

Warning: Unknown version detected, still continue? [y/n] y
@[BackupFile]: C:\Program Files\PremiumSoft\Navicat Premium 12\libcc.dll has been backed up.
The key is not appropriate to use. @[patcher::Solution1::Do -> CheckRSAKeyIsAppropriate]
Failed!

Navicat.Premium.v12.0.26.x64 繁體安裝檔 也 測試失敗
Navicat.Premium.v12.0.11.x64 簡體安裝檔 則 測試成功

似乎是繁體版會有問題

**Comment by SyaoranChang** [comment]
從你這邊下載
https://github.com/DoubleLabyrinth/navicat-keygen/releases/download/v1.7/navicat-keygen_for_x64.zip

我晚點測試看看 Navicat.Premium.v12.0.26.x64 簡體安裝檔
還是移除後要重開機才會正常?

**Comment by DoubleLabyrinth** [comment]
@SyaoranChang 
对于旧版的Navicat.Premium.v12.0.11.x64，patcher的策略是生成新RSA私钥后写入到当前目录的RegPrivateKey.pem文件中，可能是这个时候发生变化了

**Comment by SyaoranChang** [comment]
好的
感謝你的說明
目前 Navicat.Premium.v12.0.29.x64 繁體 還在正常使用中
應該之後比較不用遇到這問題才是
為了在資料庫就能看到 emoji 文字才想說用最新版本的
只是後來Lite版取消了
