### ISSUE TITLE
Navicat 12.1.4 > new Offline Activation Response Information Request

### ISSUE THREAD

**Issue by Deltafox79** [DoubleLabyrinth/navicat-keygen#107]
The format:
#if defined(NAVICAT_12)
    sprintf_s(LicenseJson, "{\"K\":\"%.16s\", \"N\":\"%s\", \"O\":\"%s\", \"DI\":\"%s\"}", SnKey, Name, Organization, DeviceIdentifier);

it seems no longer valid on new Offline Activation Response Information while the Request Code remains unchanged

Working on this...

**Comment by DoubleLabyrinth** [comment]
What do you means? I found this format still works fine here.

**Comment by Deltafox79** [comment]
Sorry my code issue..

Tks and Regards
