### ISSUE TITLE
Navicat for MySQL 12.1.4的Registration Key无法使用

### ISSUE THREAD

**Issue by GuangTianLi** [DoubleLabyrinth/navicat-keygen#109]
<img width="487" alt="2018-08-01 12 18 43" src="https://user-images.githubusercontent.com/24431425/43500900-51a6a774-9585-11e8-8a52-caaf55a3c01a.png">

**Comment by m-hume** [comment]
You need to enter the name and organization you entered in the keygen

**Comment by GuangTianLi** [comment]
the name and organization can not be changed.

**Comment by m-hume** [comment]
That's strange. Maybe you can backup and delete the registry keys associated with the licencing for Navicat for MySQL 12.1.4 and try again?
They should be somewhere under HKCU\Software\PremiumSoft in a key called something like "Registration12XEN"

That or you try Navicat Premium 12.1.5?

**Comment by DoubleLabyrinth** [comment]
@GuangTianLi 
This keygen is for Navicat Premium only. 
Please download Navicat Premium and try again

**Comment by DoubleLabyrinth** [comment]
@m-hume 
You cannot modify the textboxes of `name` and `organization`. Because that information is contained in `Activate code`

**Comment by m-hume** [comment]
@DoubleLabyrinth
My apologies. Just trying to help (but obviously about something i know little about;)

Maybe the README.md should be updated to specify this is for **Navicat Premium only** ?

**Comment by GuangTianLi** [comment]
I still can not enter the name and organization, and when I get the SnKey, I need input my name. What name should I input?
<img width="601" alt="2018-08-01 6 46 37" src="https://user-images.githubusercontent.com/24431425/43517444-4a9356b8-95bb-11e8-9155-94d9cfca861b.png">
<img width="488" alt="2018-08-01 6 46 20" src="https://user-images.githubusercontent.com/24431425/43517447-4ae21a50-95bb-11e8-8d9a-fa2d381c2ccf.png">

**Comment by DoubleLabyrinth** [comment]
@GuangTianLi
Your activation has not been done. 
Please see `README.md` in `mac` branch carefully, especially `step 5 to 9` at the end of `README.md`.

**Comment by GuangTianLi** [comment]
I am sure that I have followed the instruction one step by step until the end of step 4. I can not input the Name and Organization.

**Comment by GuangTianLi** [comment]
Ok, it is fine. Even though I can not input these, I just need to keep the name and organization empty in the process of `./navicat-keygen 2048key.pem` and the I got valid Activation Code. So it is awesome and Thanks.

**Comment by dragonflylee** [comment]
@GuangTianLi  名称和组织是在注册机生成 激活码的时候输入的（也就是说激活码中包含了 名称组织信息）

**Comment by GuangTianLi** [comment]
@dragonflylee 如果是这样，那么在破解过程中`./navicat-keygen 2048key.pem`程序让用户输入名称和组织这个过程则毫无意义

**Comment by dragonflylee** [comment]
@GuangTianLi 是不是我的表述有问题，
> 破解过程中./navicat-keygen 2048key.pem程序让用户输入名称和组织这个过程

就是为了让 激活码 中包含你的信息，具体原理请参考 [Readme.md](https://github.com/DoubleLabyrinth/navicat-keygen/blob/windows/README.zh-CN.md#1-%E5%85%B3%E9%94%AE%E8%AF%8D%E8%A7%A3%E9%87%8A) 中 

> 离线激活回复信息

的描述
