### ISSUE TITLE
How can I use in Windows x86 version 

### ISSUE THREAD

**Issue by Ding-Jun** [DoubleLabyrinth/navicat-keygen#11]

**Comment by DoubleLabyrinth** [comment]
I think there is no difference about offline activation process between Navicat 12 x86 and Navicat 12 x64.
You can download source code and build patcher and keygen in x86 mode by yourself.

Before you build I must tell you that this is a VS2015 project and you should have OpenSSL x86 version and adjust OpenSSL include path and lib path.
