### ISSUE TITLE
12.0.29无法激活

### ISSUE THREAD

**Issue by wilean** [DoubleLabyrinth/navicat-keygen#111]
替换文件的时候会提示：
Warning: Unknown version detected, still continue? [y/n] y
@[BackupFile]: C:\Program Files\PremiumSoft\Navicat Premium 12\libcc.dll has been backed up.
Failed to open libcc.dll. CODE: 0x00000020 @[patcher::Solution1::Do -> CreateFile]
Failed!
但是会生成.backup文件，就算上一步偶尔能通过，手动激活也会报下面的错：
Failed to decrypt request code.

**Comment by DoubleLabyrinth** [comment]
CODE: 0x00000020 是表示文件正在被占用，估计你的navicat没关。请用backup文件恢复后重新运行patcher。
如果仍然还是报错，请麻烦报告下你的navicat版本

**Comment by wilean** [comment]
已经解决了，非常感激，我用的是12.0.29 premium中文版。
