### ISSUE TITLE
求navicat 12.0.28版本的官网安装包

### ISSUE THREAD

**Issue by ding2022** [DoubleLabyrinth/navicat-keygen#114]
navicat 12.0.29 激活 最新版本的激活报错
`PS C:\Users\dinre\Downloads\navicat-keygen_for_x64> .\navicat-patcher.exe "E:\work\tools\Navicat 12 for MySQL"
Warning: Unknown version detected, still continue? [y/n] y
@[BackupFile]: E:\work\tools\Navicat 12 for MySQL\libcc.dll has been backed up.
Failed to open libcc.dll. CODE: 0x00000020 @[patcher::Solution1::Do -> CreateFile]
Failed!`

邮箱 ding2022@163.com

**Comment by DoubleLabyrinth** [comment]
首先，你运行patcher的时候navicat应该是关闭的。
第二，请不要使用本注册机注册navicat mysql，我不保证成功，因为这个注册机是给navicat premium用的。
第三，官网上下载的navicat premium（截止到目前）仍然是可以用该注册机激活的

**Comment by ding2022** [comment]
已激活，多谢指导！
