### ISSUE TITLE
Resource doest not match.

### ISSUE THREAD

**Issue by Ezio87** [DoubleLabyrinth/navicat-keygen#118]
navicat版本:12.0.29,navicat-keygen版本:2.0.
运行navicat-patcher.exe命令后出现,如下错误,之前失效过一次.
New RSA private key has been saved to RegPrivateKey.pem.
Target has been found: navicat.exe
@patcher::Solution0::CheckFile LINE: 143
ERROR: Resource doest not match.

**Comment by DoubleLabyrinth** [comment]
之前失效过一次是什么意思？如果是之前运行过navicat-patcher 2.0麻烦把之前的输出也贴出来。

另外ERROR: Resource doest not match的意思是navicat.exe文件中的公钥已经不是官方的公钥了，很有可能是你之前的运行改动了navicat.exe。所以如有可能，请将之前的输出也贴出来。

如果实在不行。请你用navicat安装目录下的navicat.exe.backup还原navicat.exe（如果有libcc.dll.backup也连同还原），然后再按照说明运行一次。

**Comment by Ezio87** [comment]
如教程顺利完成前三步操作后,此时打开navicat,弹出提示框,版本Navicat Premium 12.0.29
Application Error 
Exception EAccessViolation in module LIBEAY32.dll at 
0000000000083FED. 
Access violation at address 00007FF891 IC3FED in module 
'LIBEAY32.dll'. Read of address 0000000000000018.

**Comment by DoubleLabyrinth** [comment]
出现这种情况是说明navicat.exe或libcc.dll已经坏了。请用backup文件恢复，然后重新运行patcher和keygen。

如果还是不成功，请麻烦将命令行输出给贴出来（这一点很重要，我需要看输出来确定问题）
