### ISSUE TITLE
Not work on official 12.0.22

### ISSUE THREAD

**Issue by ac1982** [DoubleLabyrinth/navicat-keygen#12]
It doesn't work on official release 12.0.22.
Thanks.

**Comment by waloyn** [comment]
Software updates too fast.
Please look here. 
https://github.com/DoubleLabyrinth/navicat-keygen/issues/8

**Comment by ac1982** [comment]
Lucky, It works on Chinese release.

**Comment by YuHangZM** [comment]
navicat for mysql  12.0.26  ，how to use it ???
