### ISSUE TITLE
提示:win10不能激活

### ISSUE THREAD

**Issue by qlmlove** [DoubleLabyrinth/navicat-keygen#121]
重试好多次不行,最后一次重装navicat后才发现是犯了初级错误
需要管理员权限运行powershell才可以

**Comment by DoubleLabyrinth** [comment]
如果你的navicat是安装在系统盘的program files文件夹下的话是要管理员权限的，因为在那个文件夹下修改文件是要提权的

**Comment by MrXionGe** [comment]
目前情况下，Windows10 64  navicat 12.1.6 英文版，激活没有任何问题。
通常激活出现问题都可能是修改文件权限不够的事情。
天大的老哥很厉害！

**Comment by ifconfig2333** [comment]
牛逼 。真的是powershell才可以成功。。。Windows10  。失败的 重装软件 然后 管理员权限打开powershell  输一次命令就过了。。
