### ISSUE TITLE
Decrypt<RSACipher::KeyType::PrivateKey> fails.

### ISSUE THREAD

**Issue by adamweixuan** [DoubleLabyrinth/navicat-keygen#122]
系统是win10，官网下载的mysql版本，请问这个是哪里操作不对导致的
![image](https://user-images.githubusercontent.com/7525242/44617508-2ee32900-a896-11e8-9c95-96e1d657f2d4.png)

**Comment by DoubleLabyrinth** [comment]
你运行了
patcher吗

**Comment by adamweixuan** [comment]
运行patch 有个报错
```
Target has been found: navicat.exe
@patcher::Solution0::BackupFile LINE: 160
Failed @ CopyFile. CODE: 0x00000050
```

**Comment by DoubleLabyrinth** [comment]
请删除navicat安装目录下的navicat.exe.backup和libcc.dll.backup两个文件，然后再重新运行patcher

**Comment by adamweixuan** [comment]
已经可以正常激活了 非常感谢 ~
