### ISSUE TITLE
Data Modeler 2.1.18 Mac data[7]  value

### ISSUE THREAD

**Issue by Deltafox79** [DoubleLabyrinth/navicat-keygen#123]
Hi I not have mac 
but I ask if anyone know the correct value for data[7] into Datamodeler Mac v2.1.18
because 0x47 or 0x4a appare to be wrong..

can anyone be brute for generate correct serial?

Regards

**Comment by dragonflylee** [comment]
@Deltafox79  0x48 for standard, 0x4B for educational

**Comment by Deltafox79** [comment]
@dragonflylee tks working you say how emulate on mac CTRL+SHIFT? for load a license file?

Regards

**Comment by dragonflylee** [comment]
@Deltafox79 @DoubleLabyrinth 

Just put **license_file** at User Desktop before click activiate

**Comment by dragonflylee** [comment]
![init](https://user-images.githubusercontent.com/6219280/58073024-10674f80-7bd4-11e9-8214-89f9750092ef.jpg)
