### ISSUE TITLE
序列号位数不对，Activate置灰

### ISSUE THREAD

**Issue by armoour** [DoubleLabyrinth/navicat-keygen#124]
RT，我生成的序列号是：NAVE-ZSZD-QGXI-24DGa，然后输入序列号（不输入a）时activate是置灰的；
![image](https://user-images.githubusercontent.com/38121283/44652561-c83d4700-aa1e-11e8-9cc6-4bc245e62667.png)

win7 64位；

**Comment by DoubleLabyrinth** [comment]
这个好像是format出问题了，你再重新运行下keygen，重新生成一个就好

**Comment by DoubleLabyrinth** [comment]
@armoour 
首先`NAVE-ZSZD-QGXI-24DG`这个key我检查了下，是给navicat premium简体中文版用的，
![image](https://user-images.githubusercontent.com/16631994/44709102-67277900-aadb-11e8-84d8-2580a614075e.png)

我到官网上查了最新版，只有12.0.29版本。所以我很怀疑你的navicat premium是英文版，所以在运行keygen的时候你很可能选错了语言，请你检查下navicat语言版本，然后在keygen里选择正确的语言

**Comment by armoour** [comment]
果然是这样，我下载的是英文版本，我以为选择语言就是选择想要显示的语言，所以我选择了简体中文，现在已经激活了，谢啦；
