### ISSUE TITLE
大佬给个linux版的破解教程呗

### ISSUE THREAD

**Issue by wencyGit** [DoubleLabyrinth/navicat-keygen#125]

**Comment by DoubleLabyrinth** [comment]
linux下的其实就是Windows版的navicat+wine环境，所以直接在wine环境下按照windows的方式操作即可

**Comment by wencyGit** [comment]
@izern 描述中的./Navicat 在哪里呢？没看到。navicat-keygen.exe是网上下载的吧？

**Comment by wencyGit** [comment]
@izern 
我执行wine64 navicat-keygen.exe ./Navicat RegPrivateKey.pem报下面的错误
`000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053`

你所说的./Navicat放在哪呢？，能在描述清楚一点不？给个详细的破解过程呗

**Comment by DoubleLabyrinth** [comment]
这个错误是因为公钥替换失败，看来的patcher没有运行成功。
我稍微对代码做出了一点修改，你可以去下最新的release，2.1版的

以下是我激活的过程中patcher和keygen的输出，供你参考
![capture](https://user-images.githubusercontent.com/16631994/45195492-65537780-b28a-11e8-99c3-ecd7bbb1b79c.PNG)

![capture2](https://user-images.githubusercontent.com/16631994/45195495-697f9500-b28a-11e8-8fa6-a2cf9d68a42b.png)

**Comment by wencyGit** [comment]
@DoubleLabyrinth 
- 我navicat v12.0.11版本
- 我下载了最新的release，2.1版本按你激活过程操作了一遍，到填写秘钥的提示了秘钥无效。我使用release，2.0版，按照izern所说的步骤
> 一样的，已激活。
1.下载release的压缩包，解压至wine版本的Navicat根目录
wine64 navicat-keygen.exe ./Navicat RegPrivateKey.pem
2. 执行ls Navicat/ -l 发现exe和dll已经被替换了
3. wine64 navicat-keygen.exe RegPrivateKey.pem
按照readme操作就好了

1）、我先是使用release，2.0版按照上面zern所说的操作获取的秘钥是有效的
2）、我拿到使用release，2.0版生成的有效秘钥后先保存起来
3）、再使用release，2.1版按照你所说的操作了一遍，启动navicat填写之前保存起来的有效秘钥，然后点击激活，复制请求码
4）、粘贴进去，回车两次成功打印出License，到此激活成功
- 到这里我不清楚是什么原因，是不是版本的原因呢？你是用2.1能拿到有效的秘钥，我使用2.1却拿不到有效的密码
![1](https://user-images.githubusercontent.com/21151964/45197695-37bffb80-b295-11e8-9f7f-632a9876bf84.png)
![2](https://user-images.githubusercontent.com/21151964/45197699-3d1d4600-b295-11e8-89c4-ba8823421700.png)
![3](https://user-images.githubusercontent.com/21151964/45197702-41e1fa00-b295-11e8-8071-4775b6c786dc.png)
![5](https://user-images.githubusercontent.com/21151964/45197709-460e1780-b295-11e8-8efc-2e11cd980517.png)

**Comment by DoubleLabyrinth** [comment]
@wencyGit 
你的navcat是中文版，在运行keygen之后选择语言的部分请选择simplified chinese，而不是和我一样选englist

**Comment by wencyGit** [comment]
@DoubleLabyrinth 
我又走了一遍流程，的确是语言选择造成的，
谢谢！你的分享
