### ISSUE TITLE
12.0.28 mac中文版激活后，再次打开密码失效

### ISSUE THREAD

**Issue by charles0212** [DoubleLabyrinth/navicat-keygen#126]
@DoubleLabyrinth 12.0.28 mac 中文版 激活后，保存的连接设置中的密码，在navicat再次打开的时候，密码错误，得重新设置密码。

**Comment by DoubleLabyrinth** [comment]
你没有对navicat重新进行代码签名，具体怎么做请见 #50

**Comment by charles0212** [comment]
@DoubleLabyrinth Thanks成功解决问题。
