### ISSUE TITLE
Mac版激活小记

### ISSUE THREAD

**Issue by BrightVan** [DoubleLabyrinth/navicat-keygen#127]
按照教程，成功激活。Mac版12.0.28；
1、现在macos自带的是libreSSL，如果要编译的话还是要```brew install openssl```
2、激活不需要断网
3、那个navicat 可执行文件路径，按照文档的copy（当然了你是安装的哪个版本要注意），我把```\```给去掉了，不行。
然后，按照原理，这个激活了是不能升级的。毕竟和可执行程序签名有关。

**Comment by DoubleLabyrinth** [comment]
@superwg1984 
请见 #50 ，之前刚好有人问了怎么弄证书的问题

**Comment by BeingHsiung** [comment]
> 按照教程，成功激活。Mac版12.0.28；
> 1、现在macos自带的是libreSSL，如果要编译的话还是要`brew install openssl`
> 2、激活不需要断网
> 3、那个navicat 可执行文件路径，按照文档的copy（当然了你是安装的哪个版本要注意），我把`\`给去掉了，不行。
> 然后，按照原理，这个激活了是不能升级的。毕竟和可执行程序签名有关。

mac的教程在哪里呀

**Comment by Echowxsy** [comment]
> > 按照教程，成功激活。Mac版12.0.28；
> > 1、现在macos自带的是libreSSL，如果要编译的话还是要`brew install openssl`
> > 2、激活不需要断网
> > 3、那个navicat 可执行文件路径，按照文档的copy（当然了你是安装的哪个版本要注意），我把`\`给去掉了，不行。
> > 然后，按照原理，这个激活了是不能升级的。毕竟和可执行程序签名有关。
> 
> mac的教程在哪里呀

```bash
git checkout mac
open README.zh-CN.md
```

**Comment by BlackBirch** [comment]
成功激活了！ 感谢作者！！版本[12.1.12]是作者发的[连接](https://github.com/DoubleLabyrinth/navicat-keygen/issues/190#issuecomment-449428728)。官网下的版本[12.1.15]激活不成功。
有一步是make all之后，需要cd bin/ 才能执行./navicat-patcher 和./navicat-keygen

**Comment by listenkeep** [comment]
Mac版12.1.20激活成功，教程有些地方不够清楚，主要在自签名那里，贴个教程https://blog.csdn.net/stupid56862/article/details/83023511

**Comment by elon-funs** [comment]
codesign 不能生成的话， 那么就是手动在keychain.app 里， 创建一个 CA证书，并信任他， 然后在来执行地这个条codesign 的命令，不过呢，要记得 codesign时的名字与你刚才创建的CA证书名字相同。其他步骤 一样。
