### ISSUE TITLE
can't click Activate after input my snKey

### ISSUE THREAD

**Issue by Photooo** [DoubleLabyrinth/navicat-keygen#13]
in step 4, i can't click Activate

**Comment by DoubleLabyrinth** [comment]
Well, please report your Navicat version include version number and language.
Also, please report snKey you input.

**Comment by Photooo** [comment]
@DoubleLabyrinth 
Navicat Premium Version 12.0.20  English
snKey:  NAVA-UXI5-R5GN-A2W5
thx

**Comment by DoubleLabyrinth** [comment]
The snKey you input is for Navicat Simplified Chinese version. 
You should clone this repo and modify `#define NAVICAT_CHS` to `#define NAVICAT_ENG` at `/navicat-keygen/navicat-keygen/_tmain.cpp` LINE 18, then rebuild project.

**Comment by Photooo** [comment]
helpful, thanks
