### ISSUE TITLE
找不到主程序

### ISSUE THREAD

**Issue by ratten3anger** [DoubleLabyrinth/navicat-keygen#131]
@patcher::Solution0::FindTargetFile LINE: 73
Unexpected Error @ LoadLibrary. CODE: 0x000000C1
@wmain LINE: 126
ERROR: Cannot find main program. Are you sure the path you specified is correct?
您好，我的navicat版本是12.0.29的，我检查了下我的路径没有问题，请问一下这是什么问题，怎么解决呢

**Comment by DoubleLabyrinth** [comment]
能提供命令行的截图吗

**Comment by ratten3anger** [comment]
![image](https://user-images.githubusercontent.com/30595927/45276104-fe84c700-b4f2-11e8-9505-ca64359e6712.png)

**Comment by DoubleLabyrinth** [comment]
从你的命令行来看，你似乎是下载了x86的注册机，但是我很怀疑你的navicat是x64的，所以请你下载x64的注册机再试

**Comment by ratten3anger** [comment]
您好，我换成x64之后，出现了新的错误：
![image](https://user-images.githubusercontent.com/30595927/45364364-87dbec80-b60c-11e8-9870-6f6b6c589489.png)

**Comment by DoubleLabyrinth** [comment]
CODE:0x00000050是The file exists. 
请你到navicat的安装目录，用navicat.exe.backup和libcc.dll.backup分别还原navicat.exe和libcc.dll。
然后在确保没有navicat.exe.backup和libcc.dll.backup这两个文件之后再次运行patcher

**Comment by ratten3anger** [comment]
成功激活，感谢
