### ISSUE TITLE
简中版12.1.7 在patch完之后进行到点击“激活”时navicat报错

### ISSUE THREAD

**Issue by biosc** [DoubleLabyrinth/navicat-keygen#135]
![err](https://user-images.githubusercontent.com/30924187/45410452-4860df00-b6a4-11e8-963e-2867ae117936.png)
这个是32位版本报的错，64位版本也有类似报错。

**Comment by DoubleLabyrinth** [comment]
简体中文已升级到最新，没有复现出你所说的情况。

出现这种情况是说明libcc.dll或navicat.exe已经坏掉了，请你用navicat安装目录下的libcc.dll.backup和navicat.exe.backup分别还原文件然后再打patcher。

**Comment by biosc** [comment]
重做了，还是报同样的错误。
![err1](https://user-images.githubusercontent.com/30924187/45414099-36d00500-b6ad-11e8-9efd-73ef57bb6451.png)

**Comment by DoubleLabyrinth** [comment]
请将命令行输出截个图给我看下

**Comment by biosc** [comment]
> 
> 
> 请将命令行输出截个图给我看下

![cmdinfo](https://user-images.githubusercontent.com/30924187/45415169-9af3c880-b6af-11e8-8923-5c6b0e0cc716.png)

**Comment by DoubleLabyrinth** [comment]
好我这边复现出来了，应该是随机生成的RSA公钥有问题，我这边会尝试修一下。

如果你急着用的话请用repo里提供的RegPrivateKey.pem来作为替换的RSA密钥

**Comment by DoubleLabyrinth** [comment]
好了，最新的release应该修正了

**Comment by biosc** [comment]
已解决，感谢
