### ISSUE TITLE
Navicate premium 12.1.8 有老哥激活吗？

### ISSUE THREAD

**Issue by winterzou** [DoubleLabyrinth/navicat-keygen#136]
按照步骤来的，也断网了，但是序列号验证总是一个X过不了

**Comment by DoubleLabyrinth** [comment]
请你检查下在运行navicat-keygen的时候选择的语言和你下载的navicat语言版本是否一致。

**Comment by winterzou** [comment]
> 请你检查下在运行navicat-keygen的时候选择的语言和你下载的navicat语言版本是否一致。
我忘了下载时候怎么选的，但应该是简体中文版，我打开也是简体中文版。选择语言也选的是简体中文 2

**Comment by winterzou** [comment]
![image](https://user-images.githubusercontent.com/10276430/45604427-e4089b80-ba66-11e8-81a5-eb636147cf96.png)
下载的时候并没有选项，应该默认的中文版

**Comment by singlepig** [comment]
Emmm...
好像上面的图是对的，教程没看完😂
这个时候激活失败，然后点“Manual Activation”，然后弹出个对话框，复制Request code，贴到之前没有退出的keygen命令行立面，然后回车两下，会吐出个activation code，贴到navicat的对话框立面，然后就激活了。。。

**Comment by winterzou** [comment]
上面的老哥指点一下迷津啊，我的序列号没有通过验证是怎么回事~

**Comment by winterzou** [comment]
现在激活了，确实是语言版本看错了 ...

**Comment by Jinxiansen** [comment]
@winterzou  https://pan.baidu.com/s/1IQi-Nxn7yiA29H1MfuwheA   m1re
