### ISSUE TITLE
360报毒……

### ISSUE THREAD

**Issue by xingline** [DoubleLabyrinth/navicat-keygen#138]
360报毒……我也是无语了

**Comment by DoubleLabyrinth** [comment]
我也没有办法，反正代码已经公开，代码审核的话谁都可以做，不放心的可以自己编译。

我已经在最大限度上公开了，我也知道navicat这种东西事关数据库安全，我毫无保留地公开都是为了得到各位的信任。

**Comment by xingline** [comment]
嗯，使用了
