### ISSUE TITLE
打补丁备份文件错误

### ISSUE THREAD

**Issue by JustForRain** [DoubleLabyrinth/navicat-keygen#139]
系统：Windows 7 64Bit
Navicat版本：12.1.7 64Bit
Navicat安装路径：C:\Program Files\PremiumSoft\Navicat Premium 12
执行命令：
`
navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem
`
报错：
`
C:\Users\JustForRain\Downloads\navicat-keygen-for-x64>navicat-patcher.exe "C:\Pr
ogram Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem
Target has been found: Navicat.exe
@patcher::Solution0::BackupFile LINE: 160
Failed @ CopyFile. CODE: 0x00000050

C:\Users\JustForRain\Downloads\navicat-keygen-for-x64>
`

**Comment by DoubleLabyrinth** [comment]
CODE: 0x00000050是The file exists. 

这说明你之前打过补丁。如果你能确保navicat安装目录下的navicat.exe和libcc.dll两个文件是原版的，那么请直接删除navicat.exe.backup和libcc.dll.backup这两个文件，然后重新运行patcher；否则请用backup文件分别还原navicat.exe和libcc.dll然后再重新打补丁。

**Comment by JustForRain** [comment]
感谢答复，已解决

**Comment by Xanthuim** [comment]
不行的，我重新安装的也是这个错误
