### ISSUE TITLE
Failed to decrypt data. 不出激活码

### ISSUE THREAD

**Issue by RichardKidd** [DoubleLabyrinth/navicat-keygen#141]
![image](https://user-images.githubusercontent.com/31839508/45695573-48754900-bb94-11e8-83d0-410e2bb2fe07.png)
什么情况就是不出激活码

**Comment by DoubleLabyrinth** [comment]
你运行了patcher吗？

**Comment by RichardKidd** [comment]
两个都跑了·，拿低版本的安装成功了，但是我能问一下这样的破解是否可以检查更新和登陆账号么

**Comment by RichardKidd** [comment]
> 你运行了patcher吗？

两个都跑了·，拿低版本的安装成功了，但是我能问一下这样的破解是否可以检查更新和登陆账号么

**Comment by DoubleLabyrinth** [comment]
可以检查更新，但是安装更新的时候很可能会失败，可能是因为覆盖了数字签名的原因。通常我是重新到官网下新版本，然后覆盖。

登录账号我没试过，我没有navicat的账号

**Comment by ernesto2066** [comment]
Serial number:
NAVL-O2RR-VHSX-ZYUW

Your name: Juan
Your organization: charrasquiado
Input request code (in Base64), input empty line to end:
ObD3/bMSKfejWR7YV28vhYVlU2OELjZrXCYqkzisDKoJADIPwXlL5x2HcVlQ0KrahjITxtaswE6W
TPQ2MZnnqP1KI+92f1CfK66l2ZLdspu/sqdbJ6pbSe7AQJYbBmbeg+iJ68q7fwyTZ/GbeOGN/+Lf
imdqXGdx8cWsy9+5OvYXpp7FNkkxHv4s9L5LWK6eZd9XoucSohBBk1f3Mn/z8AMBsIkipoRmAgld
jSNh+9plzDCA8B+NoncdKdhapXbZsH6J2JpPsV0xctaeyTnmiHHaUxD8nIcv235enEFnC+wzUq2h
KseQnY+0IXYnM3KBPCizpnjXu+b8moWzT1BILQ==

@Function: int __cdecl main(int,char *[]) LINE: 391
Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by DoubleLabyrinth** [comment]
@ernesto2066 
你运行了patcher吗？

**Comment by xcloading** [comment]
同样的问题，
navicat Premium 版本 12.1.12
![wx20181130-144459](https://user-images.githubusercontent.com/12317213/49273108-e0ee4a80-f4ae-11e8-921c-5facae7a27a3.png)

**Comment by DoubleLabyrinth** [comment]
@xcloading 
你运行了patcher吗？
如果你运行了，并且你没有更改patcher的代码，那么你看看navicat-keygen文件夹下的2048key.pem是不是被改了，改了的话麻烦git checkout还原，然后重试

**Comment by yanlun0323** [comment]
最新的版本好像是不支持，报加密数据失败；换了12.0.20版本可以正常玩
