### ISSUE TITLE
mac 12.1.8版本 在每次电脑重启后，数据库连接信息的密码失效

### ISSUE THREAD

**Issue by xsdhy** [DoubleLabyrinth/navicat-keygen#143]
**版本**：12.1.8 简体中文
**平台**：mac
**场景复现**：

1. 破解成功后，
2. 在navicat中新建一个连接，
3. 输入地址、账号、密码等信息，保存，
4. 然后进行连接，显示连接成功。
5. 然后重启电脑，打开navicat，
6. 选择上一步中新建的那个连接，
7. 提示"连接失败，密码错误"，
8. 编辑连接，重新输入密码，
9. 进行连接，提示连接成功

**总结**：也就是说，每次重启了电脑以后，在navicat中保存的连接信息的密码都会失效，需要重新输入密码才可以。
不知道大家是否遇到同样的问题？

**说明**：在破解过程中，好像没有执行这一步，但是破解还是成功了的

> 生成一个自签名的代码签名证书，并在Keychain.app中总是信任它。然后使用codesign命令对Navicat Premium.app进行重签名。

**自我分析**：我怀疑是不是就是因为破解的时候少执行了一步的原因，同时我还发现一个问题，以前版本，在navicat中保存的密码信息，在Keychain.app中都是可以看到的，但是目前我这个情况，是看不到的，说没有的，不知道是不是这样原因？

**不知道大家是否遇到同样的问题？望赐教！！！**

**Comment by DoubleLabyrinth** [comment]
Navicat的数据库密码信息是存在keychain里的，对于数字签名无效的软件，mac好像是不允许其访问keychain。

最后，请不要随意省略步骤。

**Comment by xsdhy** [comment]
好滴谢谢

**Comment by caiwen09** [comment]
请问你是否已经解决，我也遇见了同样的问题

**Comment by xsdhy** [comment]
> 请问你是否已经解决，我也遇见了同样的问题
文档里面有写，你把这一步，重新做一下

生成一份自签名的代码证书，并总是信任该证书。这一步非常重要。然后用codesign对Navicat Premium.app重签名。
`codesign -f -s "Your self-signed code-sign certificate name" <path to Navicat Premium.app>`

注意：
"Your self-signed code-sign certificate name"是你证书的名字，不是路径。
例如：
`codesign -f -s "foobar" /Applications/Navicat\ Premium.app/`
