### ISSUE TITLE
navicat12.1.8 成功激活,感谢楼主

### ISSUE THREAD

**Issue by panxch** [DoubleLabyrinth/navicat-keygen#146]
navicat12.1.8 成功激活,感谢楼主
<img width="1680" alt="wx20180927-092121 2x" src="https://user-images.githubusercontent.com/6477572/46117954-bb3a9000-c236-11e8-9cc3-bd93614b87d9.png">

**Comment by YagamiLelouch** [comment]
现在Navicat有黑色主题了吗

**Comment by panxch** [comment]
Mac 新系统的深色模式

**Comment by Darkbish** [comment]
@panxch 
楼主没出mac的包呀，你是自己编译的么？

**Comment by panxch** [comment]
> @panxch
> 楼主没出mac的包呀，你是自己编译的么？

看教程，多试试，主要是钥匙串，看看别的Issues里面有教程

**Comment by Darkbish** [comment]
@panxch 

我的意思是楼主只更新了 windows 的分支，mac 分支没更新，以前发的包能用么？

**Comment by panxch** [comment]
> @panxch
> 
> 我的意思是楼主只更新了 windows 的分支，mac 分支没更新，以前发的包能用么？

可以的

**Comment by Darkbish** [comment]
> > @panxch
> > 我的意思是楼主只更新了 windows 的分支，mac 分支没更新，以前发的包能用么？
> 
> 可以的

ok，谢了哈。
