### ISSUE TITLE
12.1.8 mac版激活失败

### ISSUE THREAD

**Issue by xp0028** [DoubleLabyrinth/navicat-keygen#147]
![image](https://user-images.githubusercontent.com/19699805/46121709-969ae400-c247-11e8-9dc5-a1ecbcba156e.png)

**Comment by DoubleLabyrinth** [comment]
你运行patcher了吗？以及你的navicat是premium吗？

**Comment by xp0028** [comment]
按照readme的操作，证书，重签名都执行了

**Comment by xp0028** [comment]
这是我的操作步骤
![image](https://user-images.githubusercontent.com/19699805/46122782-4e7ec000-c24d-11e8-97ff-b781ce0e5cf1.png)

**Comment by xp0028** [comment]
> 从文件修改时间来看，很明显2048key.pem已经被修改过了。
> 
> 如果你是想用你自己的RSA私钥，请麻烦
> 
> 1. 重装Navicat。因为文件已经修改，没法还原了。
> 2. 修改navicat-patcher\main.c（第14行到第22行）里的公钥为自己的RSA公钥。
> 3. 修改navicat-keygen\2048key.pem的内容为自己的RSA私钥。
>    然后只需重新编译navicat-patcher，并用navicat-patcher给Navicat主程序打补丁，接着重签名、用navicat-keygen激活。
> 
> 如果你不想这么麻烦，那么请用git checkout还原2048key.pem然后再运行navicat-keygen试试。
激活成功了，谢谢！
原因是执行了 openssl genrsa -out 2048key.pem 2048。

**Comment by me450722457** [comment]
请问编译的时候是用的什么版本的g++，我换了好多版本，都有错误
