### ISSUE TITLE
openssl 版本问题

### ISSUE THREAD

**Issue by UnaHe** [DoubleLabyrinth/navicat-keygen#15]
您好～ 我在执行的时候提示
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/una/Downloads/navicat-keygen/./navicat-kengen
  Reason: image not found
Abort trap: 6

但是我 openssl version 版本 2.2.7
需要怎么办？

**Comment by DoubleLabyrinth** [comment]
你应该打开Makefile，修改`-I/usr/local/opt/openssl/include`和`-L/usr/local/opt/openssl/lib`，分别改成你电脑上openssl的include和lib路径，再重新编译。

**Comment by UnaHe** [comment]
好的 我尝试一下
给windows版本提个建议,我windows 12.0.22x64 激活成功

激活的时候可以不用断网,点设置代理服务器,指向直接本地127.0.0.1就可以了.
![image](https://user-images.githubusercontent.com/30680842/35105675-3a43a158-fca7-11e7-8c3c-21d8ef862b45.png)
![image](https://user-images.githubusercontent.com/30680842/35105757-6bf4c6b4-fca7-11e7-852a-a524efc5146e.png)

**Comment by UnaHe** [comment]
非常感谢～mac也激活成功了。
报错原因还是因为没有装openssl（不知道为什么openssl命令还能用）
后面用Homebrew装了一个搞定了

**Comment by DoubleLabyrinth** [comment]
额，High Sierra是自带openssl的，但是只有可执行文件，没有提供编译用的库。你在Homebrew下的就是带链接库的openssl
