### ISSUE TITLE
版本Navicat Premium 12.1.8在Mac下激活失败

### ISSUE THREAD

**Issue by youngme** [DoubleLabyrinth/navicat-keygen#154]
版本Navicat Premium 12.1.8在Mac下激活失败。按照步骤走的不知道什么问题？求解～
@DoubleLabyrinth

**Comment by CoCoHuBin** [comment]
<img width="639" alt="wx20181008-165204 2x" src="https://user-images.githubusercontent.com/40587941/46599933-2c255600-cb1b-11e8-9fcc-0f5d4eeb923c.png">
