### ISSUE TITLE
输入序列号显示叉叉

### ISSUE THREAD

**Issue by 1987zfp** [DoubleLabyrinth/navicat-keygen#155]
已patch，已断网，还是这样
安装目录下会自动释放.backup文件

**Comment by DoubleLabyrinth** [comment]
backup文件是正常的，方便你以后恢复文件。
序列号显示叉叉是序列号不对，请你务必在运行navicat-keygen.exe的时候选择正确的产品类型和产品语言版本。

**Comment by 1987zfp** [comment]
> backup文件是正常的，方便你以后恢复文件。
> 序列号显示叉叉是序列号不对，请你务必在运行navicat-keygen.exe的时候选择正确的产品类型和产品语言版本。

好的，我明天试下，感谢提供这个工具
