### ISSUE TITLE
mac make release 失败

### ISSUE THREAD

**Issue by laraCai** [DoubleLabyrinth/navicat-keygen#156]
![image](https://user-images.githubusercontent.com/26062252/46619346-75de6280-cb54-11e8-920e-f5b96ab62b52.png)
openssl已经装了

**Comment by DoubleLabyrinth** [comment]
这是warning，不是error。只要有文件生成无视即可

**Comment by laraCai** [comment]
嗯嗯，解决了，最新版12.1.9已破解，就是证书那个地方卡了一下，感谢大佬神器
