### ISSUE TITLE
没有navicat-patcher.exe文件

### ISSUE THREAD

**Issue by nnewer** [DoubleLabyrinth/navicat-keygen#158]
没有navicat-patcher.exe文件，不知道如何生成该文件，使用教程不清晰

**Comment by DoubleLabyrinth** [comment]
你确定没有navicat-patcher.exe？我不知道你是从哪里下载的，但至少我可以保证release页面里是有的。

至于使用教程不清晰，麻烦指出那里不清晰，我会更新一下

**Comment by nnewer** [comment]
找到exe了，可在navicat-patcher.exe时候还是出现异常，后来干脆装了个破解版的，感谢回复。
ps:版本prenium 12.0.28,之前用注册机破解过一次30天。
