### ISSUE TITLE
win10 1803 安装失败 显示‘此应用无法在你的电脑上运行’

### ISSUE THREAD

**Issue by syf-** [DoubleLabyrinth/navicat-keygen#160]
操作系统版本：17134.285 
运行 navicat-patcher.exe "...." RegPrivateKey.pem  错误，显示“此应用无法在你的电脑上运行 若要找到适用于你的电脑的版本，请咨询软件发布者”

**Comment by syf-** [comment]
@DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
很可能你是32位的系统，但是你下载了给x64用的注册机。请使用x86的版本再试一次

**Comment by l619534951** [comment]
我也是一样，win10 1809。使用旧版本成功了。
