### ISSUE TITLE
ERROR: GetFileAttributes Failed. CODE: 0x00000003

### ISSUE THREAD

**Issue by RMD1998** [DoubleLabyrinth/navicat-keygen#164]
Hello, I have a problem. When I tried to execute the patcher using cmd like at the tutorial, I've got the message like this
![problem](https://user-images.githubusercontent.com/44256337/47138814-9b9e0100-d2e4-11e8-9ffb-14a37fdc2098.png)
Please reply using English, I can't read Chinese properly, thank you

**Comment by DoubleLabyrinth** [comment]
CODE 0x00000003 is `The system cannot find the path specified. `
You should use 
```
"C:\Program Files\PremiumSoft\Navicat Premium 12"
```
NOT
```
"C:Program Files\PremiumSoft\Navicat Premium 12"
```
Please don't forget there is a back-slant after drive letter.

**Comment by RMD1998** [comment]
Wow, I didn't realize it that I forgot the "\" after "C:" . Thank you for fast respons. It work now.
