### ISSUE TITLE
Unknown error. CODE: 0x00000005.

### ISSUE THREAD

**Issue by guotie** [DoubleLabyrinth/navicat-keygen#17]
Unknown error. CODE: 0x00000005.

**Comment by DoubleLabyrinth** [comment]
This is error is ACCESS_DENIED. Maybe you should run your command prompt as administrator.
By the way, you can query error code by a tool called `Error Lookup` in Visual Studio.

**Comment by guotie** [comment]
nice!

**Comment by guotie** [comment]
Failed to decrypt request code.
