### ISSUE TITLE
12.1.12版本输入序列号，激活按钮是灰的

### ISSUE THREAD

**Issue by keke9036** [DoubleLabyrinth/navicat-keygen#171]
版本：Navicat Premium 12.1.12  MAC
前面的操作都照做了，但是输入SN不能激活，能帮忙看下吗

**Comment by hsz591031981** [comment]
不能用最新的安装包，windows下是12.1.7的版本之前才能激活成功（我的电脑是这种，没在其他电脑上测试）

**Comment by keke9036** [comment]
> 不能用最新的安装包，windows下是12.1.7的版本之前才能激活成功（我的电脑是这种，没在其他电脑上测试）

已经放弃了，换了一个低版本的破解版

**Comment by DoubleLabyrinth** [comment]
SN号不能用只能说明你没有选择正确的Navicat产品类型和语言版本。

```
Select Navicat product:
1. DataModeler
2. Premium
3. MySQL
4. PostgreSQL
5. Oracle
6. SQLServer
7. SQLite
8. MariaDB
9. MongoDB
10. ReportViewer

(Input index)> 1

Select product language:
1. English
2. Simplified Chinese
3. Traditional Chinese
4. Japanese
5. Polish
6. Spanish
7. French
8. German
9. Korean
10. Russian
11. Portuguese

(Input index)> 1

(Input major version number, range: 0 ~ 15, default: 12)> 12
```

我在README里给的只是一个样例。具体是什么product、什么language那只有你自己知道，请如实选择。

**Comment by devguo** [comment]
Navicat Premium 12.1.12 MAC 
安装完后，打开界面是英文版，选英文获得的激活码和你的情况一样，后来选中文，重新生成激活码，填写新激活码，就可以成功了。

**Comment by Xanthuim** [comment]
就出了12.1.12版本？最新版不是12.1.10吗？

**Comment by Echowxsy** [comment]
在`12.0.27`破解激活的基础上，下载最新版`12.1.14`替换。
使用`avicat-patcher`替换证书并签名：
```bash
./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
codesign -f -s - /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
```
打开就是激活状态。

**Comment by pteros** [comment]
12.1.10版本成功，开始也遇到了这个问题，最后一次成功的操作：断网， 运行navicat-keygen.exe，生成SN号， 再打开软件输入SN号， 按钮不再是灰色，后续按文档操作，激活成功。供大家参考。

**Comment by crazyliuzc** [comment]
猜测按钮灰色的是因为SN号输入错误，cmd中生成的字母V看起来很像U，我就遇到了。
输入正确后按钮不再是灰色，不联网在hosts文件中加入activate.navicat.com也行。
版本：win8下Navicat Premium12.1.11中文版

**Comment by trb331617** [comment]
成功！！！感谢！！！
Navicat Premium12.1.11 中文版 Win10。
也遇到”输入序列号，激活按钮是灰的“情况：是由于”Navicat product“选择错误。（选择了MySQL，其实应该是Premium）
