### ISSUE TITLE
提问：破解后可以正常更新吗？

### ISSUE THREAD

**Issue by justdontbeasaltedfish** [DoubleLabyrinth/navicat-keygen#172]
上次成功激活一段时间后出现程序崩溃，不知是否与更新有关。

**Comment by DoubleLabyrinth** [comment]
应该是可以更新的

关于崩溃，可否告知下复现步骤？

**Comment by justdontbeasaltedfish** [comment]
> 应该是可以更新的
> 
> 关于崩溃，可否告知下复现步骤？

程序可正常运行并能成功链接数据库，在打开 table 的时候会报错（抱歉，错误信息没保存下来）。重装并重新破解后可正常使用

**Comment by coder77** [comment]
感恩
