### ISSUE TITLE
tips: Mac自签名证书是选择创建证书颁发机构……

### ISSUE THREAD

**Issue by zxj5470** [DoubleLabyrinth/navicat-keygen#174]

**Comment by wxlg1117** [comment]
!!!!!也可以使用adhoc方式签名，就一个“-”即可。
$ codesign -f -s - /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

**Comment by xiaozhouwu** [comment]
> !!!!!也可以使用adhoc方式签名，就一个“-”即可。
> $ codesign -f -s - /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

跟自签名的代码签名证书有什么区别呢？

**Comment by StefanChang** [comment]
> !!!!!也可以使用adhoc方式签名，就一个“-”即可。
> $ codesign -f -s - /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

这样是可以激活navicat，但是激活之后navicat无法保存密码到钥匙串了！！！！
