### ISSUE TITLE
navicat premium 批量修改字段功能失效

### ISSUE THREAD

**Issue by justdontbeasaltedfish** [DoubleLabyrinth/navicat-keygen#175]
问题是激活后出现的，试用期件该功能正常使用。问题表现为点击字段名后只选中部分数据。（navicat premium 12.1.12，macOS 10.14.1）

**Comment by DoubleLabyrinth** [comment]
您好，我这边没有复现出你所说的情况
<img width="897" alt="screen shot 2018-11-16 at 15 46 56" src="https://user-images.githubusercontent.com/16631994/48605337-7372f200-e9b7-11e8-9e76-a2e1ab6a3122.png">

在点击user字段之后，整个列是全部选中的

**Comment by justdontbeasaltedfish** [comment]
![image](https://user-images.githubusercontent.com/26694896/48819381-ad167500-ed8a-11e8-8e7e-e76666b5e33a.png)
我的情况是这样的，并且可以复现，不知是否个例。

**Comment by justdontbeasaltedfish** [comment]
在我的两台 MacBook 都出现了这种情况。刚破解完是能正常使用的，在使用一段时间后就会出这个 bug。重启软件，数据库或者机器都不能修复这个问题。

**Comment by phantomsoul** [comment]
我的也是无法整列修改

**Comment by MyDinnerIsReady** [comment]
是的，mac版的我的也不能整列修改。
