### ISSUE TITLE
请问各位出现这个问题是怎么回事？有碰到过吗？

### ISSUE THREAD

**Issue by steplp** [DoubleLabyrinth/navicat-keygen#179]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Windows\system32> navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
navicat-patcher.exe : 无法将“navicat-patcher.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写
，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" ...
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (navicat-patcher.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>

**Comment by DoubleLabyrinth** [comment]
你的powershell当前目录是`C:\Windows\system32`，你确认navicat-patcher.exe在这个目录下？

另外powershell类似linux的bash，在当前目录下启动navicat-patcher.exe得是`.\navicat-patcher.exe`打头

**Comment by steplp** [comment]
解决了   谢谢
