### ISSUE TITLE
v12.1.10  ERROR: Cannot open Navicat.exe. CODE: 0x00000020  

### ISSUE THREAD

**Issue by i-yxy** [DoubleLabyrinth/navicat-keygen#180]
C:\Program Files\PremiumSoft\keygen>navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
@wmain LINE: 98
ERROR: Cannot open Navicat.exe. CODE: 0x00000020

**Comment by DoubleLabyrinth** [comment]
CODE: 0x00000020
The process cannot access the file because it is being used by another process. 

Please close all of Navicat process first.

**Comment by i-yxy** [comment]
thank you
