### ISSUE TITLE
v12.1.10 ERROR: Cannot find RSA public key in Navicat.exe

### ISSUE THREAD

**Issue by i-yxy** [DoubleLabyrinth/navicat-keygen#181]
C:\Program Files\PremiumSoft\keygen>navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
MESSAGE: Navicat.exe has been found.
MESSAGE: libcc.dll has been found.

@wmain LINE: 165
ERROR: Cannot find RSA public key in Navicat.exe.

**Comment by DoubleLabyrinth** [comment]
It means that your `Navicat.exe` has been patched. Please make sure that `Navicat.exe` is official, not patched version.

**Comment by i-yxy** [comment]
thank you
