### ISSUE TITLE
版本:12.1.11最后一步返回激活码失败

### ISSUE THREAD

**Issue by MingSpace** [DoubleLabyrinth/navicat-keygen#187]
今天刚更新了 Navicat Premium 12.1.11，提示失效了，就去激活，上面流程一切正常，到最后返回激活码的时候报错：
@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by ccpwcn** [comment]
我也收到同样的错误，12.1.11激活失败。

**Comment by kerojiang** [comment]
12.1.11不行了  上来给大佬加油

｡◕◡◕｡)ﾉ非常感谢

**Comment by Eternity-Myth** [comment]
大佬加油

**Comment by songchaoyuan** [comment]
我的也是激活不了了,大佬

**Comment by songchaoyuan** [comment]
Input request code (in Base64), input empty line to end:
tCg/tcWcflkJOJCyf2gOhaSiTS/yK0oj0M6CRL2+D/8MVcsuSWuI0lITXz2bww6nPFtM11xGwiQfIavzVUH2leAziuvmFSnN5F4HsZJN8cLr2ux4sqHqDxw1KgtgHifF2tI7BGklsaCoO0UPVUcPaEvRnlJAj2SKIvC+3zoF1Ow/1mBrAVg4CZGN1tujf3KURjQiXnFK16yzn5rNtzGbHBJuWWIo7YYEUGmRyuMNz7QbL5HM9KVnbyo+fQQL1RHgW4HNTgMSqWe2jjmxDelEIurrxDq1myW9dgLIXGsOb1E0TsRaXmJRjjTEE0nECKHgDKXqRd4rQhPZMG4JMyHuYg==

@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by songchaoyuan** [comment]
看群主,大概意思是从文件读入key的时候报错了

**Comment by songchaoyuan** [comment]
RequestCode = Helper::Base64Decode(RequestCode_b64);
        if (RequestCode.empty()) {
            std::cout << "@Function: " << __FUNCSIG__ << " LINE: " << __LINE__ << std::endl;
            std::cout << "ERROR: Base64Decode fails." << std::endl;
            return;
        }

        if (!cipher->Decrypt(RequestCode.data(),
                             RequestCode.size(),
                             RequestInfo,
                             RSA_PKCS1_PADDING)) {
            std::cout << "@Function: " << __FUNCSIG__ << " LINE: " << __LINE__ << std::endl;
            std::cout << "ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails." << std::endl;
            return;
        }

        std::cout << "Request Info:" << std::endl;
        std::cout << RequestInfo << std::endl;
        std::cout << std::endl;

**Comment by songchaoyuan** [comment]
似乎无法解密了,RequestCode.size()这个还是256位,大佬能否初步分析下,是不是解密模式变了

**Comment by songchaoyuan** [comment]
修改为,if (!cipher->Decrypt(RequestCode.data(),
                             RequestCode.size(),
                             RequestInfo,
			RSA_NO_PADDING)) {
            std::cout << "@Function: " << __FUNCSIG__ << " LINE: " << __LINE__ << std::endl;
            std::cout << "ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails." << std::endl;
            return;
        } 就能解密了,但是后面生成的
Input request code (in Base64), input empty line to end:
CPemPKKeQPittjHPnYJzOqgc9weiUkfwx66SV5dPjM07e49f27Il3kVGrQY8R+lAzmwAswY1qQ0zOlWMH6nr44Mt86gb/W/s8wQdvMWApwesY7/qSNdayITlYEkh8uGWq5SdiOARgdazbEiqnKqELBby1oRMIGbI/hOtfn/eDsxrabmZETRT49B7/BGW60XN3SP8DBZVjmP2rMaTEuopNnE3yIkFKkIxqhbu4l5J7oWXwNMrf3Pzf6yJisM4jb05vV/oojmom30O216oPOZ0voVtrYEp9cT9OiR5Lj6z89Bs5D76HeKFtazl5neutStIlSpObTeSXyT/Dh58odfy9w==

256Request Info:
\?????~?????7??)?p??L,??l?3*?k}K??fku

Response Info:
null

License:
oef2jmD3gVuQ73whfTo59nduDwPBOgixWpuRXxeTB2NHP3ZE5avOA3SICcCA5m+f
a2w5/etWhhuhozUF74haMB403F8vsez4Bnw81giewvTiqf+k9lNXHlK5wKOrfc36
RARxjbKqcPvkSyAcESPn7fShk3XkOxdax8H2O/MGHruJgve+OyaDSohgkg2qY5bw
nvRTlaTgn8qJFdcN1XAXRxl9d87LtuuoXy9JAel5Wy8u1pabKqbyWJRyK01LIkJ+
1wHuy/rWA2my5dl1636dr+bRIEL9SLIFdpdwPAwdArBRunIhjxd3t+YxoS+kfqHU
V5XkQoAtyNAjrRovdKqouA==

还是无法激活

**Comment by TACHAI** [comment]
我的版本是12.1.12
最后一步报的错是：Failed to decrypt data.

**Comment by songchaoyuan** [comment]
> 我的版本是12.1.12
> 最后一步报的错是：Failed to decrypt data.

你哪里下载到的?

**Comment by DoubleLabyrinth** [comment]
x64版本的已经可以了

![capture](https://user-images.githubusercontent.com/16631994/49933654-2ecf6d80-ff07-11e8-82ba-db66789202af.PNG)

我再看下x86版本的就可以了哈

**Comment by DoubleLabyrinth** [comment]
@songchaoyuan 
额RSA_PKCS1_PADDING改成NoPadding是没有用的，NoPadding的话连是否是正确的明文都没办法判断了。

**Comment by songchaoyuan** [comment]
> @songchaoyuan
> 额RSA_PKCS1_PADDING改成NoPadding是没有用的，NoPadding的话连是否是正确的明文都没办法判断了。

不懂这块,谢谢告知

**Comment by songchaoyuan** [comment]
> x64版本的已经可以了
> 
> ![capture](https://user-images.githubusercontent.com/16631994/49933654-2ecf6d80-ff07-11e8-82ba-db66789202af.PNG)
> 
> 我再看下x86版本的就可以了哈

改动了什么地方呀?

**Comment by DoubleLabyrinth** [comment]
@songchaoyuan 
我这么说吧，RSA的公钥是
```
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1dqF3SkCaAAmMzs889I
...
...
```

在libcc.dll里，写了一个巨大的函数来生成XOR密钥，不过XOR密钥长只有8字节，那么大的函数只是用来混淆的，专门防那些靠IDA F5反编译插件破解的手段。程序启动时是用这个XOR密钥循环加密，然后验证时循环解密，来得到RSA公钥。

事实上如果你看汇编代码的话你会看到
```
xor eax, 'M'
mov byte_xxxxxx, al
...
xor eax, 'I'
mov byte_xxxxxx, al
...
xor eax, 'I'
mov byte_xxxxxx, al
...
xor eax, 'B'
mov byte_xxxxxx, al
...
xor eax, 'I'
mov byte_xxxxxx, al
...
...
```

这样字眼的汇编，很简单了，把这些`M`、`I`、`I`、`B`这些东西换成咱们自己的公钥就行了。不过的话呢，这些patch位点数量可以达到0x188个，就是有点烦。还有x86下xor的寄存器会变，也稍微麻烦点。

**Comment by DoubleLabyrinth** [comment]
@MingSpace @ccpwcn @Eternity-Myth @kerojiang @TACHAI @songchaoyuan 
最新的release应该可以激活12.1.11了。

**Comment by songchaoyuan** [comment]
> @MingSpace @ccpwcn @Eternity-Myth @kerojiang @TACHAI @songchaoyuan
> 最新的release应该可以激活12.1.11了。

谢谢,真的很谢谢,这个软件picpick,有着极强的反汇编,在你启动该程序的时候会检测是电脑是否启动了反汇编软件,一旦启动了,它自己都启动不起来.

**Comment by Eternity-Myth** [comment]
> @MingSpace @ccpwcn @Eternity-Myth @kerojiang @TACHAI @songchaoyuan
> 最新的release应该可以激活12.1.11了。

非常感谢大佬，已经激活成功

**Comment by songchaoyuan** [comment]
> @songchaoyuan
> 我这么说吧，RSA的公钥是
> 
> ```
> MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1dqF3SkCaAAmMzs889I
> ...
> ...
> ```
> 在libcc.dll里，写了一个巨大的函数来生成XOR密钥，不过XOR密钥长只有8字节，那么大的函数只是用来混淆的，专门防那些靠IDA F5反编译插件破解的手段。程序启动时是用这个XOR密钥循环加密，然后验证时循环解密，来得到RSA公钥。
> 
> 事实上如果你看汇编代码的话你会看到
> 
> ```
> xor eax, 'M'
> mov byte_xxxxxx, al
> ...
> xor eax, 'I'
> mov byte_xxxxxx, al
> ...
> xor eax, 'I'
> mov byte_xxxxxx, al
> ...
> xor eax, 'B'
> mov byte_xxxxxx, al
> ...
> xor eax, 'I'
> mov byte_xxxxxx, al
> ...
> ...
> ```
> 这样字眼的汇编，很简单了，把这些`M`、`I`、`I`、`B`这些东西换成咱们自己的公钥就行了。不过的话呢，这些patch位点数量可以达到0x188个，就是有点烦。还有x86下xor的寄存器会变，也稍微麻烦点。

这得从什么地方才能学到这个?大神推荐点资料

**Comment by ccpwcn** [comment]
12.1.11亲测成功，感谢大佬。

**Comment by fanjianhao** [comment]
版本:12.1.11最后一步返回激活码失败
![image](https://user-images.githubusercontent.com/16731100/51164868-571d0400-18d9-11e9-9be2-7a1eb0de09ec.png)
