### ISSUE TITLE
Patch的时候，顺便把activate.navicat.com写入host，就可以不用断网啦。

### ISSUE THREAD

**Issue by Renshk** [DoubleLabyrinth/navicat-keygen#188]
一个小小的改动却可以带来巨大的方便，特别是远程服务器，要是一断网，连服务器都连不上了。

**Comment by songchaoyuan** [comment]
但是这样,就破坏了你windows的hosts文这种操作一般很流氓的

**Comment by Renshk** [comment]
这个好办，提供一个选项，让用户自己选择即可！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: songchaoyuan <notifications@github.com>
发送时间: Thursday, December 13, 2018 10:17:07 AM
收件人: DoubleLabyrinth/navicat-keygen
抄送: Renshk; Author
主题: Re: [DoubleLabyrinth/navicat-keygen] Patch的时候，顺便把activate.navicat.com写入host，就可以不用断网啦。 (#188)


但是这样,就破坏了你windows的hosts文这种操作一般很流氓的

―

**Comment by Renshk** [comment]
甚至默认情况，选项都可以是关闭的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: songchaoyuan <notifications@github.com>
发送时间: Thursday, December 13, 2018 10:17:07 AM
收件人: DoubleLabyrinth/navicat-keygen
抄送: Renshk; Author
主题: Re: [DoubleLabyrinth/navicat-keygen] Patch的时候，顺便把activate.navicat.com写入host，就可以不用断网啦。 (#188)


但是这样,就破坏了你windows的hosts文这种操作一般很流氓的

―

**Comment by Joeng100** [comment]
激活那里配置一个代理不就行了

**Comment by Renshk** [comment]
> 激活那里配置一个代理不就行了

稍显麻烦，因为设置好后，激活完成还要把设置去掉，否则就不能更新，这样一来一回有点浪费时间。

**Comment by KeikoSong** [comment]
> > 激活那裡配置一個代理不就行了
> 
> 稍顯麻煩，因為設置好後，激活完成還要把設置去掉，否則就不能更新，這樣一來一回有點浪費時間。

會很麻煩嗎？勾選取消掉一個動作就好，去改Hosts，不是更麻煩？

**Comment by Renshk** [comment]
> 激活那裡配置一個代理不就行了
> 
> 稍顯麻煩，因為設置好後，激活完成還要把設置去掉，否則就不能更新，這樣一來一回有點浪費時間。
> 
> 會很麻煩嗎？勾選取消掉一個動作就好，去改Hosts，不是更麻煩？

如果工具能直接支持打Host补丁，就不会麻烦，输入YES或者NO让用户自己选择，还省去设置代理以及取消勾选。

**Comment by KeikoSong** [comment]
> 如果工具能直接支持打Host補丁，就不會麻煩，輸入YES或者NO讓用戶自己選擇，還省去設置代理以及取消勾選。

对我这种有强迫症的人来说，能不动系统就不动，尤其是Hosts档案，尤其这种方式对于一些不懂电脑的人来说，很不友善。

**Comment by Renshk** [comment]
> 如果工具能直接支持打Host補丁，就不會麻煩，輸入YES或者NO讓用戶自己選擇，還省去設置代理以及取消勾選。
> 
> 对我这种有强迫症的人来说，能不动系统就不动，尤其是Hosts档案，尤其这种方式对于一些不懂电脑的人来说，很不友善。

这个根本不是问题嘛，只要默认是NO就行了啊，大家用基本也都是写个Patch的脚本，所以甚至可以开出参数控制。另外，这个和使用代理并没有矛盾，喜欢设置代理解决的用户仍然可以使用，并没有影响到强迫症用户，多一种方式就多一个选择，并无坏处，却可以帮到那些喜欢省事的用户。
