### ISSUE TITLE
visual paradigm 破解

### ISSUE THREAD

**Issue by bongQ417** [DoubleLabyrinth/navicat-keygen#19]
你好，请问一下visual paradigm 软件要怎么破解，有什么破解的思路吗？

mac版的

**Comment by DoubleLabyrinth** [comment]
你说的软件我有时间会看下。

还有这里是navicat-keygen的repo，请不要提和本repo无关的问题。如果有问题请你直接向我的邮箱xiao_ai_yu@live.cn发邮件。

**Comment by bongQ417** [comment]
@DoubleLabyrinth sorry~，我下次会注意的
