### ISSUE TITLE
12.1.14 Failed to decrypt data.

### ISSUE THREAD

**Issue by UnaHe** [DoubleLabyrinth/navicat-keygen#190]
Update to the latest version 12.1.14 today Tip Unable to decrypt data

**Comment by DoubleLabyrinth** [comment]
Okay, I will take a look.

**Comment by wallaceyoung** [comment]
the same problem,wait for solution.

**Comment by DoubleLabyrinth** [comment]
I'm afraid to tell you that we'd better wait for next release of `Navicat Premium for mac`.

It seems that `Navicat Premium 12.1.14 for mac` itself has some severe bugs about offline activation. 

Example, crash when deactivate offline. And offline activation does not 100% work even when correct activation code is provided. So I suggest that we'd better wait for next release of Navicat Premium and see if bugs are fixed. I've update `mac` branch, but it it just for test only.

**Comment by zlsq** [comment]
so anyone has the 12.1.13version?

**Comment by DoubleLabyrinth** [comment]
For those who are looking for an old version of Navicat Premium, here's a link
https://pan.baidu.com/s/1Fnaeh7IoTGbsMCTIdAID6w

This is 12.1.12 version, thanks #200

**Comment by DoubleLabyrinth** [comment]
I've updated `mac` branch. It should work for Navicat Premium 12.1.15 now. Please read README carefully.
