### ISSUE TITLE
12.1.11激活失败

### ISSUE THREAD

**Issue by kubeeliang** [DoubleLabyrinth/navicat-keygen#191]
前几布都成功了，最后一步激活时失败
![image](https://user-images.githubusercontent.com/14833803/50039878-b686ba80-0074-11e9-865e-483e88b08410.png)

**Comment by DoubleLabyrinth** [comment]
可以将请求码和激活码以文本形式贴出来吗？

**Comment by mms0536** [comment]
我卸载之后还是不行,是哪里没清理干净吗? 直接windows自带卸载工具卸载的

**Comment by kubeeliang** [comment]
> 我卸载之后还是不行,是哪里没清理干净吗? 直接windows自带卸载工具卸载的

把原安装目录下的 Navicat Premium 12文件夹删除以下试试，然后重新安装下 12.1.11版本

**Comment by selfdialog** [comment]
![nn_8g 08feros8m2 1 xa](https://user-images.githubusercontent.com/30248712/50050374-894d1180-0133-11e9-9712-bf511936b068.png)
3.8激活最新版12.1.11报错
