### ISSUE TITLE
Win版12.1.11激活失败

### ISSUE THREAD

**Issue by wood4083** [DoubleLabyrinth/navicat-keygen#193]
patcher日志：
MESSAGE: Navicat.exe has been found.
MESSAGE: libcc.dll has been found.

MESSAGE: [Solution0] Keyword has been found: offset = +0x029a4b9c.
MESSAGE: Cannot find RSA public key in libcc.dll. Solution1 will be omitted.
MESSAGE: Cannot find RSA public key in libcc.dll. Solution2 will be omitted.

Your RSA public key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOZGsX7UoDPuxCfEuw4i
yWDASpwaN19GaPNrTlWz6K7MKXGrAQpYD5gNZ8nGdfRgp52TErTHSNoRjgfpxGqK
ApPUISsIanGMcyf/H2b8pGuz1oF19kVKSyZTPaVLbE+1Cw7FULbI04bc64XnWSHo
aQAXrYKGpC7oDomRGMtx28figu3AHAk1UQrcCvE3+0ITTA7X8xaRwz6+gb+uLgCd
iXyRYDodG8i+kk1YIt3f2mt7jH+uEHqBYjIfvvo6g5MZz4KNz7Ewc6+sDyO8bmlX
eFnHo6YAgCcaHVvVtGNCxCd1O5wWHvUN985HHQYnFr7qzJaL9cPb735pP2hb0IXe
ywIDAQAB
-----END PUBLIC KEY-----

MESSAGE: Navicat.exe has been backed up successfully.

//
// Begin Solution0
//
@+0x029A4B9C
Previous:
+0x00000000029A4B90  72 00 66 00 6c 00 6f 00 77 00 00 00 2d 2d 2d 2d  r.f.l.o.w...----
+0x00000000029A4BA0  2d 42 45 47 49 4e 20 50 55 42 4c 49 43 20 4b 45  -BEGIN PUBLIC KE
+0x00000000029A4BB0  59 2d 2d 2d 2d 2d 0d 0a 4d 49 49 42 49 6a 41 4e  Y-----..MIIBIjAN
+0x00000000029A4BC0  42 67 6b 71 68 6b 69 47 39 77 30 42 41 51 45 46  BgkqhkiG9w0BAQEF
+0x00000000029A4BD0  41 41 4f 43 41 51 38 41 4d 49 49 42 43 67 4b 43  AAOCAQ8AMIIBCgKC
+0x00000000029A4BE0  41 51 45 41 77 31 64 71 46 33 53 6b 43 61 41 41  AQEAw1dqF3SkCaAA
+0x00000000029A4BF0  6d 4d 7a 73 38 38 39 49 0d 0a 71 64 57 39 4d 32  mMzs889I..qdW9M2
+0x00000000029A4C00  64 49 64 68 33 6a 47 39 79 50 63 6d 4c 6e 6d 4a  dIdh3jG9yPcmLnmJ
+0x00000000029A4C10  69 47 70 42 46 34 45 39 56 48 53 4d 47 65 38 6f  iGpBF4E9VHSMGe8o
+0x00000000029A4C20  50 41 79 32 6b 4a 44 6d 64 4e 74 34 42 63 45 79  PAy2kJDmdNt4BcEy
+0x00000000029A4C30  67 76 73 73 45 66 67 69 6e 76 0d 0a 61 35 74 35  gvssEfginv..a5t5
+0x00000000029A4C40  6a 6d 33 35 32 55 41 6f 44 6f 73 55 4a 6b 54 58  jm352UAoDosUJkTX
+0x00000000029A4C50  47 51 68 70 41 57 4d 46 34 66 42 6d 42 70 4f 33  GQhpAWMF4fBmBpO3
+0x00000000029A4C60  45 65 64 47 36 32 72 4f 73 71 4d 42 67 6d 53 64  EedG62rOsqMBgmSd
+0x00000000029A4C70  41 79 78 43 53 50 42 52 4a 49 4f 46 0d 0a 52 30  AyxCSPBRJIOF..R0
+0x00000000029A4C80  51 67 5a 46 62 52 6e 55 30 66 72 6a 33 34 66 69  QgZFbRnU0frj34fi
+0x00000000029A4C90  56 6d 67 59 69 4c 75 5a 53 41 6d 49 62 73 38 5a  VmgYiLuZSAmIbs8Z
+0x00000000029A4CA0  78 69 48 50 64 70 31 6f 44 34 74 55 70 76 73 46  xiHPdp1oD4tUpvsF
+0x00000000029A4CB0  63 69 34 51 4a 74 59 4e 6a 4e 6e 47 55 32 0d 0a  ci4QJtYNjNnGU2..
+0x00000000029A4CC0  57 50 48 36 72 76 43 68 47 6c 31 49 52 4b 72 78  WPH6rvChGl1IRKrx
+0x00000000029A4CD0  4d 74 71 4c 69 65 6c 73 76 61 6a 55 6a 79 72 67  MtqLielsvajUjyrg
+0x00000000029A4CE0  4f 43 36 4e 6d 79 6d 59 4d 76 5a 4e 45 52 33 68  OC6NmymYMvZNER3h
+0x00000000029A4CF0  74 46 45 74 4c 31 65 51 62 43 79 54 66 44 6d 74  tFEtL1eQbCyTfDmt
+0x00000000029A4D00  0d 0a 59 79 51 31 57 74 34 4f 74 31 32 6c 78 66  ..YyQ1Wt4Ot12lxf
+0x00000000029A4D10  30 77 56 49 52 35 6d 63 47 4e 37 58 43 58 4a 52  0wVIR5mcGN7XCXJR
+0x00000000029A4D20  48 4f 46 48 53 66 31 67 7a 58 57 61 62 52 53 76  HOFHSf1gzXWabRSv
+0x00000000029A4D30  6d 74 31 6e 72 6c 37 73 57 36 63 6a 78 6c 6a 75  mt1nrl7sW6cjxlju
+0x00000000029A4D40  75 51 0d 0a 61 77 49 44 41 51 41 42 0d 0a 2d 2d  uQ..awIDAQAB..--
+0x00000000029A4D50  2d 2d 2d 45 4e 44 20 50 55 42 4c 49 43 20 4b 45  ---END PUBLIC KE
+0x00000000029A4D60  59 2d 2d 2d 2d 2d 0d 0a a2 8c df 98 7b 3c 3a 79  Y-----......{<:y
After:
+0x00000000029A4B90  72 00 66 00 6c 00 6f 00 77 00 00 00 2d 2d 2d 2d  r.f.l.o.w...----
+0x00000000029A4BA0  2d 42 45 47 49 4e 20 50 55 42 4c 49 43 20 4b 45  -BEGIN PUBLIC KE
+0x00000000029A4BB0  59 2d 2d 2d 2d 2d 0d 0a 4d 49 49 42 49 6a 41 4e  Y-----..MIIBIjAN
+0x00000000029A4BC0  42 67 6b 71 68 6b 69 47 39 77 30 42 41 51 45 46  BgkqhkiG9w0BAQEF
+0x00000000029A4BD0  41 41 4f 43 41 51 38 41 4d 49 49 42 43 67 4b 43  AAOCAQ8AMIIBCgKC
+0x00000000029A4BE0  41 51 45 41 74 4f 5a 47 73 58 37 55 6f 44 50 75  AQEAtOZGsX7UoDPu
+0x00000000029A4BF0  78 43 66 45 75 77 34 69 0d 0a 79 57 44 41 53 70  xCfEuw4i..yWDASp
+0x00000000029A4C00  77 61 4e 31 39 47 61 50 4e 72 54 6c 57 7a 36 4b  waN19GaPNrTlWz6K
+0x00000000029A4C10  37 4d 4b 58 47 72 41 51 70 59 44 35 67 4e 5a 38  7MKXGrAQpYD5gNZ8
+0x00000000029A4C20  6e 47 64 66 52 67 70 35 32 54 45 72 54 48 53 4e  nGdfRgp52TErTHSN
+0x00000000029A4C30  6f 52 6a 67 66 70 78 47 71 4b 0d 0a 41 70 50 55  oRjgfpxGqK..ApPU
+0x00000000029A4C40  49 53 73 49 61 6e 47 4d 63 79 66 2f 48 32 62 38  ISsIanGMcyf/H2b8
+0x00000000029A4C50  70 47 75 7a 31 6f 46 31 39 6b 56 4b 53 79 5a 54  pGuz1oF19kVKSyZT
+0x00000000029A4C60  50 61 56 4c 62 45 2b 31 43 77 37 46 55 4c 62 49  PaVLbE+1Cw7FULbI
+0x00000000029A4C70  30 34 62 63 36 34 58 6e 57 53 48 6f 0d 0a 61 51  04bc64XnWSHo..aQ
+0x00000000029A4C80  41 58 72 59 4b 47 70 43 37 6f 44 6f 6d 52 47 4d  AXrYKGpC7oDomRGM
+0x00000000029A4C90  74 78 32 38 66 69 67 75 33 41 48 41 6b 31 55 51  tx28figu3AHAk1UQ
+0x00000000029A4CA0  72 63 43 76 45 33 2b 30 49 54 54 41 37 58 38 78  rcCvE3+0ITTA7X8x
+0x00000000029A4CB0  61 52 77 7a 36 2b 67 62 2b 75 4c 67 43 64 0d 0a  aRwz6+gb+uLgCd..
+0x00000000029A4CC0  69 58 79 52 59 44 6f 64 47 38 69 2b 6b 6b 31 59  iXyRYDodG8i+kk1Y
+0x00000000029A4CD0  49 74 33 66 32 6d 74 37 6a 48 2b 75 45 48 71 42  It3f2mt7jH+uEHqB
+0x00000000029A4CE0  59 6a 49 66 76 76 6f 36 67 35 4d 5a 7a 34 4b 4e  YjIfvvo6g5MZz4KN
+0x00000000029A4CF0  7a 37 45 77 63 36 2b 73 44 79 4f 38 62 6d 6c 58  z7Ewc6+sDyO8bmlX
+0x00000000029A4D00  0d 0a 65 46 6e 48 6f 36 59 41 67 43 63 61 48 56  ..eFnHo6YAgCcaHV
+0x00000000029A4D10  76 56 74 47 4e 43 78 43 64 31 4f 35 77 57 48 76  vVtGNCxCd1O5wWHv
+0x00000000029A4D20  55 4e 39 38 35 48 48 51 59 6e 46 72 37 71 7a 4a  UN985HHQYnFr7qzJ
+0x00000000029A4D30  61 4c 39 63 50 62 37 33 35 70 50 32 68 62 30 49  aL9cPb735pP2hb0I
+0x00000000029A4D40  58 65 0d 0a 79 77 49 44 41 51 41 42 0d 0a 2d 2d  Xe..ywIDAQAB..--
+0x00000000029A4D50  2d 2d 2d 45 4e 44 20 50 55 42 4c 49 43 20 4b 45  ---END PUBLIC KE
+0x00000000029A4D60  59 2d 2d 2d 2d 2d 0d 0a a2 8c df 98 7b 3c 3a 79  Y-----......{<:y

Solution0 has been done successfully.

register日志：
Select Navicat product:
0. DataModeler
1. Premium
2. MySQL
3. PostgreSQL
4. Oracle
5. SQLServer
6. SQLite
7. MariaDB
8. MongoDB
9. ReportViewer

(Input index)> 1

Select product language:
0. English
1. Simplified Chinese
2. Traditional Chinese
3. Japanese
4. Polish
5. Spanish
6. French
7. German
8. Korean
9. Russian
10. Portuguese

(Input index)> 1

(Input major version number, range: 0 ~ 15, default: 12)> 12

Serial number:
NAVC-R7FF-LY54-IJT3

Your name: TSONG
Your organization: TSONG

Input request code (in Base64), input empty line to end:
lect2KwNenXdvLfGJZ+gAhRqCisSGAUeftQ95Va80E6lMbzOSG7YokS7621E65oQCXoEkTJLTKdfwcCgLBhLh9FKpsT0UXIZ3RvSq+iHhgSewEItOB42cEPhNwmDBDbdLzkwnwtDFxq+xZzB+esRN3kP5Vu/GcEe9yFPAHzBrSfvG08+Fq5P/s86QX0eEwWWUTJBJprl7hg1Iys6tiruWCL44HRDr8ctIz2rSMF2VoJqKC4we0/TUigG5f3g7NGFXOtq2nrWevWnic8OqESna4gFMo/PqEqoAqwGSSeVgZ8HbAWY8WRnP8ikJ54EixqdWnwLR4QHvF7yLsvGRUjSjA==

@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by DoubleLabyrinth** [comment]
很显然
```
MESSAGE: Cannot find RSA public key in libcc.dll. Solution1 will be omitted.
MESSAGE: Cannot find RSA public key in libcc.dll. Solution2 will be omitted.
```

你的libcc.dll肯定是打过补丁了，请确保navicat.exe和libcc.dll都是官方原版再试。
