### ISSUE TITLE
3.8激活12.1.11失败，卸载删除重试也是失败，暂时用的英文版

### ISSUE THREAD

**Issue by selfdialog** [DoubleLabyrinth/navicat-keygen#195]
![nn_8g 08feros8m2 1 xa](https://user-images.githubusercontent.com/30248712/50050419-45f3a280-0135-11e9-8122-5508bed579ee.png)
3.8激活12.1.11失败

**Comment by selfdialog** [comment]
> 这个注册机不是我发布的，你应该去[＃8](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8)

谢谢，我激活了，但是发现绑定input框的小bug

![sc4rele zqfb83st 4htpb7](https://user-images.githubusercontent.com/30248712/50050508-1c884600-0138-11e9-8f34-75152031eb63.png)

**Comment by selfdialog** [comment]
> > 这个注册机不是我发布的，你应该去[＃8](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8)
> 
> 谢谢，我激活了，但是发现绑定的输入框的小的bug
> 
> ![sc4rele zqfb83st 4htpb7](https://user-images.githubusercontent.com/30248712/50050508-1c884600-0138-11e9-8f34-75152031eb63.png)

**Comment by DoubleLabyrinth** [comment]
额，就算有bug也不要跟我讲，我不负责这个注册机。你应该去那个issue问楼主

**Comment by Deltafox79** [comment]
> 
> 
> ![nn_8g 08feros8m2 1 xa](https://user-images.githubusercontent.com/30248712/50050419-45f3a280-0135-11e9-8122-5508bed579ee.png)
> 3.8激活12.1.11失败

New v4.1 Online fix some bug.. tk's for report..

**Comment by Deltafox79** [comment]
> 
> 
> > > 这个注册机不是我发布的，你应该去[＃8](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8)
> > 
> > 
> > 谢谢，我激活了，但是发现绑定的输入框的小的bug
> > ![sc4rele zqfb83st 4htpb7](https://user-images.githubusercontent.com/30248712/50050508-1c884600-0138-11e9-8f34-75152031eb63.png)

New v4.1 Online fix some bug.. tk's for report..

**Comment by gzkiko** [comment]
12.1.11激活成功，特意上来感谢。
一开始也是不行，后来看了前面的帖，卸载了删了目录（这个很重要）重新装再激活，一次就成功了。
给作者一万个赞！
