### ISSUE TITLE
Mac版的怎么编译

### ISSUE THREAD

**Issue by zjcnew** [DoubleLabyrinth/navicat-keygen#2]
能中文解释下吗

**Comment by DoubleLabyrinth** [comment]
确保你有openssl，以及你知道openssl的include和lib位置在哪

clone这个项目的Mac分支：
git clone -b mac https://github.com/DoubleLabyrinth/navicat-keygen.git

进入navicat-keygen文件夹
把Makefile里include路径和lib路径改成你的openssl的include和lib路径

之后终端（在这个文件夹下）
$ make navicat-keygen

**Comment by zjcnew** [comment]
感谢，回家我试下。但我现在测试Navicat 12.0.18 64位 简体中文版，并未生成 私钥文件RegPrivateKey.pem！
测试平台：2008 R2 64位 简体中文版
下载地址：http://www.navicat.com.cn/installers/navicat120_premium_cs_x64.exe
![qq 20171214093351](https://user-images.githubusercontent.com/22335594/33971141-ed681f8c-e0b1-11e7-8f62-236b8464f68d.png)

**Comment by DoubleLabyrinth** [comment]
理论上讲，你的RegPrivateKey.pem文件在C:\users\Administrator下

**Comment by zjcnew** [comment]
果然是在C:\Users\Administrator目录下，为什么不是生成在navicat12-keygen_x64目录里呢，怎么会乱跑！

但是仍然激活失败！！
![qq 20171214172619](https://user-images.githubusercontent.com/22335594/33984863-f035da46-e0f3-11e7-8339-24a20f997ada.png)

**Comment by DoubleLabyrinth** [comment]
我不知道你有没有仔细看我在52pojie上帖子的说明，从你的截图来看你没有断网激活，因为我根本没看到你输入了请求码

至于为什么在那个目录下，因为你的当前目录就是C:\Users\Administrator，注册机代码里生成文件时为了避免文件夹不存在问题，是直接在当前目录下生成的。这一类问题你直接看代码就明白的，就在GeneratePrivateKey函数里。

**Comment by hysys32** [comment]
特地来感谢作者！~软件很常用码码农必备啊~价格也是一般个人用户难以承受的~感谢作者慷慨提供~~~
