### ISSUE TITLE
Virus, in release, reported

### ISSUE THREAD

**Issue by RUSshy** [DoubleLabyrinth/navicat-keygen#20]
You added a virus in the release 

I report you motherfucker

**Comment by DoubleLabyrinth** [comment]
please tell me which release and post virus report. 
I can promise that all of the releases were built from source code.

**Comment by RUSshy** [comment]
microsoft defender blocked file as trojan, it is the one for windows 64 english

**Comment by DoubleLabyrinth** [comment]
Do you means the file `navicat12-keygen_Win_ENG_x64.zip`?
I've checked it. But my windows defender does not block it. 

This zip file contains three files. 
* `libcrypto-1_1-x64.dll` is a OpenSSL dll from `http://slproweb.com/products/Win32OpenSSL.html`. SHA1 value is `54F4EE9AD1F4147011D63D4FBA2664F0A8EA84B2`. And it was not built by me. But I think it should be safe for it has long history.
* `navicat-keygen.exe` and `navicat-patcher.exe` were built by me and SHA1 values are `567953CF68A0D10FAC40CAFBBA851CE5654C9225` and `9843660BBB146DDAE9C654C44CCAE11D7C11C157` respectively. I've decompiled them by IDA and confirmed that no malicious code inserted.

If you find SHA1 values do not match, please post the file you got to this issue. 
Or if match and you still insist that I added a virus, please show convincing evidence.

By the way, can you tell me what version your Microsoft Defender is?

**Comment by Deltafox79** [comment]
@RUSshy exist also false positive.. So before insulting someone studies
