### ISSUE TITLE
Data Modeler 2.1.17 无法使用

### ISSUE THREAD

**Issue by 60999** [DoubleLabyrinth/navicat-keygen#201]
patcher后启动有错误框
---------------------------
Navicat Data Modeler
---------------------------
Access violation at address 000000000100A022 in module 'modeler.exe'. Read of address 0000000000000000.
---------------------------
确定   
---------------------------

Data Modeler 2.1.17 windows
提示：
激活服务器当前不可用。请稍后再试一次。
80260001 couldn't resolve host name.

**Comment by 60999** [comment]
用原版本重新补丁后，启动还是有读内存的报错，用-bin生成文件，许可文件方式激活成功。
重启后还有读内存报错。

**Comment by DoubleLabyrinth** [comment]
很抱歉我这边没有复现出你说的情况。你确定注册机是最新版本的吗？

**Comment by gz818** [comment]
最新版的，v4.2, Data Modeler 2.1.17.0  x64，Win10

**Comment by gz818** [comment]
@DoubleLabyrinth 谢谢，但又出现了 达到激活上限或注册码没有卸载！注册表中的Data Modeler的键都删除了，不知道藏在那里判断的，网也断了！

**Comment by DoubleLabyrinth** [comment]
按住ctrl和shift、同时点激活，应该会弹出一个文件选择对话框，选择生成的license_file即可

**Comment by gz818** [comment]
@DoubleLabyrinth 谢谢，不好意思麻烦您了！就是按 #173 （您说的 按住ctrl和shift、同时点激活，应该会弹出一个文件选择对话框，选择生成的license_file即可）这个方式，但确认license_file后出现 【达到激活上限或注册码没有卸载！】这个提示，激活不了！已经把 注册表中的Data Modeler的键都删除了，不知道藏在那里判断的，网也断了！

**Comment by DoubleLabyrinth** [comment]
@gz818 
如果你没打补丁，那就先打补丁再试。如果打了补丁还是出现这样的情况，那可能是生成license_file时用的序列号和你输入的序列号不一致造成的，请重新运行navicat-keygen.exe，填入新的序列号、并选择新生成的license_file

**Comment by gz818** [comment]
@DoubleLabyrinth `谢谢，成功激活！
