### ISSUE TITLE
大神，激活成功了，简体中文的，非常感谢，但是点击工具栏就闪退了？

### ISSUE THREAD

**Issue by dongliang0201** [DoubleLabyrinth/navicat-keygen#204]
RT，windows版，版本12.1.10 x64
![image](https://user-images.githubusercontent.com/8383365/50409694-86d37180-082f-11e9-8b81-f76f71053431.png)

请帮忙看下，谢谢

**Comment by DoubleLabyrinth** [comment]
我现在已经找不到官方原版的12.1.10版本了。所以这个问题我也没办法。

**Comment by liurenjin** [comment]
这个问题没办法解决么

**Comment by DoubleLabyrinth** [comment]
@liurenjin 
如果要解决也可以，请麻烦提供12.1.10版本的下载链接

**Comment by dongliang0201** [comment]
![image](https://user-images.githubusercontent.com/8383365/50502079-74f40780-0a97-11e9-8237-006c8bd42b09.png)
这个就是从官网刚刚下载的，
这个是地址;http://dn.navicat.com/download/navicat121_premium_en_x64.exe

**Comment by DoubleLabyrinth** [comment]
@dongliang0201 
未复现出你说的情况

![tempsnip](https://user-images.githubusercontent.com/16631994/50505227-6ca6c700-0aad-11e9-9e23-987938a0633c.png)

**Comment by dongliang0201** [comment]
> @dongliang0201
> 未复现出你说的情况
> 
> ![tempsnip](https://user-images.githubusercontent.com/16631994/50505227-6ca6c700-0aad-11e9-9e23-987938a0633c.png)

谢谢，我重新安装下再试试。

**Comment by liurenjin** [comment]
把有道的鼠标取词，禁用就可以
