### ISSUE TITLE
注册完无法取消

### ISSUE THREAD

**Issue by vipwuping** [DoubleLabyrinth/navicat-keygen#205]
绿色版注册完无法取消注册，直接报错。

**Comment by vipwuping** [comment]
@ @ #

> 
![333](https://user-images.githubusercontent.com/40034996/50445371-508a1500-0949-11e9-9f7d-26a21417a769.png)

**Comment by DoubleLabyrinth** [comment]
取消必须联网，这应该算是navicat的一个bug
