### ISSUE TITLE
12.1.11无法破解成功

### ISSUE THREAD

**Issue by vipwuping** [DoubleLabyrinth/navicat-keygen#206]
提示  
@LoadKey LINE: 65
ERROR: The RSA private key you provide cannot be used.

**Comment by DoubleLabyrinth** [comment]
这只能说明你使用的RSA私钥是不符合要求的，主要是不能通过代码中solution1的检查。
请使用repo里的RegPrivateKey.pem再试。

**Comment by MrJiao** [comment]
codesign -f -s "jackson" /Applications/Navicat\ Premium\ 2.app
error: The specified item could not be found in the keychain.

**Comment by sjdskl** [comment]
> specified

你要从keychain里自己创建证书并信任

**Comment by MrJiao** [comment]
> > specified
> 
> 你要从keychain里自己创建证书并信任

谢谢解惑。
创建证书步骤 打开keychain->钥匙串访问(左上角)->证书助理->创建证书
