### ISSUE TITLE
Navicat for mysql 12.0.24(64bit) cannot activate

### ISSUE THREAD

**Issue by lixiang4u** [DoubleLabyrinth/navicat-keygen#21]
我的12.0.24 for MySQL 的版本激活不了，请问是不适用吗？

可以生成snKey，然后将snKey写入到激活页面，激活按钮一直是灰色（没有关闭生成snKey的窗口）
没有什么 request code 

![tim 20180224132553](https://user-images.githubusercontent.com/5090006/36626060-716c08d8-1966-11e8-8db8-90812a45bfe4.png)

![tim 20180224133244](https://user-images.githubusercontent.com/5090006/36626111-a7944172-1967-11e8-9a68-63ecc9e730a1.png)

**Comment by DoubleLabyrinth** [comment]
这个注册机是给navicat premium用的。

**Comment by dragonflylee** [comment]
[参考这里](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8#issuecomment-363683264)

**Comment by dragonflylee** [comment]
@lixiang4u 
![navicat](https://user-images.githubusercontent.com/6219280/36828678-3a1b148e-1d56-11e8-9ded-831288efd3df.PNG)

**Comment by songchaoyuan** [comment]
12.0.26无法注册成功了,官方太坑了,迅速修复了

**Comment by 5452** [comment]
> [参考这里](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8#issuecomment-363683264)

没看明白，知道链接中解决了window工具可以全线激活的问题，mac如果不想虚拟机运行windows keygen，如何单独在Mac上做哪些修改呢？
