### ISSUE TITLE
[FAILURE][wind10] 连接oracle 闪退

### ISSUE THREAD

**Issue by WangShuangQuan-A** [DoubleLabyrinth/navicat-keygen#210]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [ ] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: _Navicat Premium_____

2. What is your Navicat language version? Check one of the following:
   - [ ] English
   - [ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: _Simplified Chinese_____

3. What is your OS? Check one of the following:
   - [1 ] Windows
   - [ ] macOS
   - [ ] Linux

4. Can you post console output here? If don't have, leave it empty.
```
Please post here
```

5. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

6. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by DoubleLabyrinth** [comment]
请看 #152
