### ISSUE TITLE
win10 正常激活，但是两三天后就又不行了

### ISSUE THREAD

**Issue by hou-xx** [DoubleLabyrinth/navicat-keygen#211]
![image](https://user-images.githubusercontent.com/18113669/50676665-7d68b700-1030-11e9-811c-2b1003472dac.png)

**Comment by hou-xx** [comment]
重新再激活一次，又能用了，但都只能用 2~3 天。
知不知道 navicat 是哪几个域名发起的请求做校验，可不可以加 hosts 的方式屏蔽掉

**Comment by DoubleLabyrinth** [comment]
你可以屏蔽掉
```
activate.navicat.com
```
试试。顺便问下的你的navicat版本是多少？

**Comment by hou-xx** [comment]
屏蔽掉  activate.navicat.com  了的（本身是为了出手动激活的弹窗）
版本是 12.0.11 （64-bit）Premium
相同版本我在另一个封闭环境里（外网不通），一次激活使用了很久也没再次弹窗提示到期。
猜测可能还有其它域名用于检验

**Comment by DoubleLabyrinth** [comment]
你确定是12.0.11不是12.1.11？如果是前者的话，那么老的版本我已经找不到了。如果是后者我只能说我从来没遇到你这样的情况。

**Comment by Junonin** [comment]
'navicat-patcher.exe' is not recognized as an internal or external command,
operable program or batch file.
这如何处理？

**Comment by DoubleLabyrinth** [comment]
@Junonin 
命令行的当前目录下有navicat-patcher.exe这个程序吗？没有的话用cd进入到navicat-patcher.exe所在的目录，或者指定全路径

**Comment by hou-xx** [comment]
@DoubleLabyrinth  我使用了 12.1.11 ，已经没有问题了。
