### ISSUE TITLE
[FAILURE][Win10] Navicat 12.1.12 registration failure

### ISSUE THREAD

**Issue by DoubleLabyrinth** [DoubleLabyrinth/navicat-keygen#215]
According to a report in issue #200, it has been comfirmed that Navicat Premium 12.1.12 has changed the registration algorithm. This issue is opend to report any progress.

根据issue #200 下的一份报告，可以证明Navicat Premium 12.1.12已经修改了注册算法。特开启此issue，以报告任何进展。

**Comment by alterem** [comment]
@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by uuip** [comment]
官网下载的最新版是12.1.12，前面的issue中怎么还有12.1.14版本的。

**Comment by Deltafox79** [comment]
On v12.1.12 Windows English version algo is ok.. The problem is in the Chinese version?

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Yes. And now Navicat has obscured the public key too much, which makes it hard to write a patch solution.

**Comment by Deltafox79** [comment]
> 
> 
> @Deltafox79
> Yes. And now Navicat has obscured the public key too much, which makes it hard to write a patch solution.

Ok... but Time to time... have you try to use libcc.dll of english version on chinese version?

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
No. I'm afraid to say we'd better NOT do that. It may cause DLL hell.

**Comment by songchaoyuan** [comment]
官方是不是注意到这个帖子了,频繁修改

**Comment by songchaoyuan** [comment]
我从英文官网上下载的12.1.12 把其中的dll文件放到中文版安装目录下,没有作用,依然无法激活

**Comment by iddddg** [comment]
支持一下,持续观望

**Comment by DoubleLabyrinth** [comment]
![image](https://user-images.githubusercontent.com/16631994/51253193-a1d17580-19d8-11e9-9b2b-32b592e86004.png)

现在x64版本的已经可以了。

[navicat-keygen-for-x64-only.zip](https://github.com/DoubleLabyrinth/navicat-keygen/files/2764401/navicat-keygen-for-x64-only.zip)

附件是一份pre-release。只对x64版本的navicat premium有用，代码在[navicat-premium-win-12.1.12](https://github.com/DoubleLabyrinth/navicat-keygen/tree/navicat-premium-win-12.1.12)分支上。

具体用法：

1. 先打补丁

```shell
navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12"
```

路径记得换成自己的navicat安装路径，最后输出会有`MESSAGE: Patch has been done successfully.`字样，同时当前目录下会生成RegPrivateKey.pem，务必保管好。

2. 运行navicat-keygen.exe

```shell
navicat-keygen.exe -text ./RegPrivateKey.pem
```

之后就和readme里的一样了。

---

关于32位版本的navicat过段时间再说吧，先给你们应下急。

**Comment by Deltafox79** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/16631994/51253193-a1d17580-19d8-11e9-9b2b-32b592e86004.png)
> 
> 现在x64版本的已经可以了。
> 
> [navicat-keygen-for-x64-only.zip](https://github.com/DoubleLabyrinth/navicat-keygen/files/2764401/navicat-keygen-for-x64-only.zip)
> 
> 附件是一份pre-release。只对x64版本的navicat premium有用，代码在[navicat-premium-win-12.1.12](https://github.com/DoubleLabyrinth/navicat-keygen/tree/navicat-premium-win-12.1.12)分支上。
> 
> 具体用法：
> 
>     1. 先打补丁
> 
> 
> ```shell
> navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12"
> ```
> 
> 路径记得换成自己的navicat安装路径，最后输出会有`MESSAGE: Patch has been done successfully.`字样，同时当前目录下会生成RegPrivateKey.pem，务必保管好。
> 
>     1. 运行navicat-keygen.exe
> 
> 
> ```shell
> navicat-keygen.exe -text ./RegPrivateKey.pem
> ```
> 
> 之后就和readme里的一样了。
> 
> 关于32位版本的navicat过段时间再说吧，先给你们应下急。

perfect .. the public key you patched it in the points where we discussed days ago? best regards

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Yes. There are 111 patch points. 

For some substrings in the public key that are cross-referenced by many other functions, they are all loaded by the following pattern:
```asm
lea REG, QWORD PTR [RIP + xxxxx]
```
where `RIP + xxxxx` points to the substring and `xxxxx` is a offset. We can just search a string in `.rdata` section, and modify `xxxxx` so that `RIP + xxxxx` can point to the string we found.

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
I think for all libcc.dll x64, yes. 
But for libcc.dll x32, I'm afraid to say no. Because there's no `EIP + xxxxx` accessing under x32.

**Comment by Deltafox79** [comment]
> 
> 
> @Deltafox79
> I think for all libcc.dll x64, yes.
> But for libcc.dll x32, I'm afraid to say no. Because there's no `EIP + xxxxx` accessing under x32.

Also x32 appare to be use same method :

on ida libcc.dll x32 check **sub_11163180**

![immagine](https://user-images.githubusercontent.com/2518850/51277348-a6495e80-19d7-11e9-8dfb-c28299348d42.jpg)

Regards

**Comment by uranus829** [comment]
已成功激活，谢谢

**Comment by trackycn** [comment]
昨天在官网下载的最新英文版本好像也有这个问题, 调试了一下 Deltafox79 的代码, 发现公钥换了, 没有继续跟下去了。

**Comment by DoubleLabyrinth** [comment]
New release has been published. It should support Navicat Premium 12.1.12 now.

新的release已经发布了，现在应该支持Navicat Premium 12.1.12版本了。

**Comment by DoubleLabyrinth** [comment]
@affxw 
请你确保是官方原版再试。

**Comment by sevdays** [comment]
学习了。已成功安装

**Comment by sevdays** [comment]
感谢！！！！
