### ISSUE TITLE
win7 12.1.11激活失败

### ISSUE THREAD

**Issue by iwin4aids** [DoubleLabyrinth/navicat-keygen#217]
@function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: DecryptRSACipher::KeyType::PrivateKey fails.

12.1.11  按照流程最后报此错误 win7 64位

**Comment by programmerCCX** [comment]
win10也遇到同样的问题，激活失败

**Comment by iddddg** [comment]
请问12.1.11的安装包还在吗?

**Comment by DoubleLabyrinth** [comment]
我这边发布了新的release，你可以再试一下。
如果还有问题，希望能贴上完成的命令行输出
