### ISSUE TITLE
[FAILURE][Windows] Failure to locate Public Key in libscc

### ISSUE THREAD

**Issue by Marvvv123** [DoubleLabyrinth/navicat-keygen#218]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [ ] Navicat Premium
   - [1 ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: ______

2. What is your Navicat language version? Check one of the following:
   - [ 1] English
   - [ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: ______

3. What is your OS? Check one of the following:
   - [ 1] Windows
   - [ ] macOS
   - [ ] Linux

4. Can you post console output here? If don't have, leave it empty.
```
Please post here
```

5. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

6. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by Marvvv123** [comment]
Hi! Thank you so much for your reply. 
Currently I have tried your latest updated version but I am unable to activate the program. I downloaded the Navicat Premium trial version from the official website. I have attached an image of the problem below. Thank you!

![capture](https://user-images.githubusercontent.com/46595459/51451407-0ccfd300-1d70-11e9-858c-7d4b6ea7c218.PNG)

**Comment by DoubleLabyrinth** [comment]
It's obvious that your Navicat is English version.
So when you select product language, you should type `0`, not `1`.

**Comment by Marvvv123** [comment]
Alright I got it up and working. Thank you so much and sorry for the troubles caused!
