### ISSUE TITLE
win10 64 位 中文12.1.12 注册失败 ，但是英文版可以成功。不知如何处理

### ISSUE THREAD

**Issue by 6897889** [DoubleLabyrinth/navicat-keygen#219]
Microsoft Windows [版本 10.0.17763.253]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>cd D:\Program Files\PremiumSoft\navicat-keygen-for-x64

C:\WINDOWS\system32>d:

D:\Program Files\PremiumSoft\navicat-keygen-for-x64>navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
@SetPath LINE: 22
ERROR: GetFileAttributes failed. CODE: 0x00000003
The path you specified:
C:\Program Files\PremiumSoft\Navicat Premium 12

D:\Program Files\PremiumSoft\navicat-keygen-for-x64>navicat-patcher.exe "D:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
MESSAGE: Navicat.exe has been found.
MESSAGE: libcc.dll has been found.

MESSAGE: [Solution0] Keyword has been found: offset = +0x029a539c.
MESSAGE: [Solution1] Keywords[0] has been found: offset = +0x021f7390.
MESSAGE: [Solution1] Keywords[1] has been found: offset = +0x0074bd39.
MESSAGE: [Solution1] Keywords[2] has been found: offset = +0x021f70a0.
MESSAGE: [Solution1] Keywords[3] has been found: offset = +0x0074bd1f.
MESSAGE: [Solution1] Keywords[4] has been found: offset = +0x021f708c.
MESSAGE: Cannot find RSA public key in libcc.dll. Solution2 will be omitted.

Your RSA public key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOZGsX7UoDPuxCfEuw4i
yWDASpwaN19GaPNrTlWz6K7MKXGrAQpYD5gNZ8nGdfRgp52TErTHSNoRjgfpxGqK
ApPUISsIanGMcyf/H2b8pGuz1oF19kVKSyZTPaVLbE+1Cw7FULbI04bc64XnWSHo
aQAXrYKGpC7oDomRGMtx28figu3AHAk1UQrcCvE3+0ITTA7X8xaRwz6+gb+uLgCd
iXyRYDodG8i+kk1YIt3f2mt7jH+uEHqBYjIfvvo6g5MZz4KNz7Ewc6+sDyO8bmlX
eFnHo6YAgCcaHVvVtGNCxCd1O5wWHvUN985HHQYnFr7qzJaL9cPb735pP2hb0IXe
ywIDAQAB
-----END PUBLIC KEY-----

MESSAGE: Navicat.exe has been backed up successfully.
MESSAGE: libcc.dll has been backed up successfully.

//
// Begin Solution0
//
@+0x029A539C
Previous:
+0x00000000029A5390  72 00 66 00 6c 00 6f 00 77 00 00 00 2d 2d 2d 2d  r.f.l.o.w...----
+0x00000000029A53A0  2d 42 45 47 49 4e 20 50 55 42 4c 49 43 20 4b 45  -BEGIN PUBLIC KE
+0x00000000029A53B0  59 2d 2d 2d 2d 2d 0d 0a 4d 49 49 42 49 6a 41 4e  Y-----..MIIBIjAN
+0x00000000029A53C0  42 67 6b 71 68 6b 69 47 39 77 30 42 41 51 45 46  BgkqhkiG9w0BAQEF
+0x00000000029A53D0  41 41 4f 43 41 51 38 41 4d 49 49 42 43 67 4b 43  AAOCAQ8AMIIBCgKC
+0x00000000029A53E0  41 51 45 41 77 31 64 71 46 33 53 6b 43 61 41 41  AQEAw1dqF3SkCaAA
+0x00000000029A53F0  6d 4d 7a 73 38 38 39 49 0d 0a 71 64 57 39 4d 32  mMzs889I..qdW9M2
+0x00000000029A5400  64 49 64 68 33 6a 47 39 79 50 63 6d 4c 6e 6d 4a  dIdh3jG9yPcmLnmJ
+0x00000000029A5410  69 47 70 42 46 34 45 39 56 48 53 4d 47 65 38 6f  iGpBF4E9VHSMGe8o
+0x00000000029A5420  50 41 79 32 6b 4a 44 6d 64 4e 74 34 42 63 45 79  PAy2kJDmdNt4BcEy
+0x00000000029A5430  67 76 73 73 45 66 67 69 6e 76 0d 0a 61 35 74 35  gvssEfginv..a5t5
+0x00000000029A5440  6a 6d 33 35 32 55 41 6f 44 6f 73 55 4a 6b 54 58  jm352UAoDosUJkTX
+0x00000000029A5450  47 51 68 70 41 57 4d 46 34 66 42 6d 42 70 4f 33  GQhpAWMF4fBmBpO3
+0x00000000029A5460  45 65 64 47 36 32 72 4f 73 71 4d 42 67 6d 53 64  EedG62rOsqMBgmSd
+0x00000000029A5470  41 79 78 43 53 50 42 52 4a 49 4f 46 0d 0a 52 30  AyxCSPBRJIOF..R0
+0x00000000029A5480  51 67 5a 46 62 52 6e 55 30 66 72 6a 33 34 66 69  QgZFbRnU0frj34fi
+0x00000000029A5490  56 6d 67 59 69 4c 75 5a 53 41 6d 49 62 73 38 5a  VmgYiLuZSAmIbs8Z
+0x00000000029A54A0  78 69 48 50 64 70 31 6f 44 34 74 55 70 76 73 46  xiHPdp1oD4tUpvsF
+0x00000000029A54B0  63 69 34 51 4a 74 59 4e 6a 4e 6e 47 55 32 0d 0a  ci4QJtYNjNnGU2..
+0x00000000029A54C0  57 50 48 36 72 76 43 68 47 6c 31 49 52 4b 72 78  WPH6rvChGl1IRKrx
+0x00000000029A54D0  4d 74 71 4c 69 65 6c 73 76 61 6a 55 6a 79 72 67  MtqLielsvajUjyrg
+0x00000000029A54E0  4f 43 36 4e 6d 79 6d 59 4d 76 5a 4e 45 52 33 68  OC6NmymYMvZNER3h
+0x00000000029A54F0  74 46 45 74 4c 31 65 51 62 43 79 54 66 44 6d 74  tFEtL1eQbCyTfDmt
+0x00000000029A5500  0d 0a 59 79 51 31 57 74 34 4f 74 31 32 6c 78 66  ..YyQ1Wt4Ot12lxf
+0x00000000029A5510  30 77 56 49 52 35 6d 63 47 4e 37 58 43 58 4a 52  0wVIR5mcGN7XCXJR
+0x00000000029A5520  48 4f 46 48 53 66 31 67 7a 58 57 61 62 52 53 76  HOFHSf1gzXWabRSv
+0x00000000029A5530  6d 74 31 6e 72 6c 37 73 57 36 63 6a 78 6c 6a 75  mt1nrl7sW6cjxlju
+0x00000000029A5540  75 51 0d 0a 61 77 49 44 41 51 41 42 0d 0a 2d 2d  uQ..awIDAQAB..--
+0x00000000029A5550  2d 2d 2d 45 4e 44 20 50 55 42 4c 49 43 20 4b 45  ---END PUBLIC KE
+0x00000000029A5560  59 2d 2d 2d 2d 2d 0d 0a a2 8c df 98 7b 3c 3a 79  Y-----......{<:y
After:
+0x00000000029A5390  72 00 66 00 6c 00 6f 00 77 00 00 00 2d 2d 2d 2d  r.f.l.o.w...----
+0x00000000029A53A0  2d 42 45 47 49 4e 20 50 55 42 4c 49 43 20 4b 45  -BEGIN PUBLIC KE
+0x00000000029A53B0  59 2d 2d 2d 2d 2d 0d 0a 4d 49 49 42 49 6a 41 4e  Y-----..MIIBIjAN
+0x00000000029A53C0  42 67 6b 71 68 6b 69 47 39 77 30 42 41 51 45 46  BgkqhkiG9w0BAQEF
+0x00000000029A53D0  41 41 4f 43 41 51 38 41 4d 49 49 42 43 67 4b 43  AAOCAQ8AMIIBCgKC
+0x00000000029A53E0  41 51 45 41 74 4f 5a 47 73 58 37 55 6f 44 50 75  AQEAtOZGsX7UoDPu
+0x00000000029A53F0  78 43 66 45 75 77 34 69 0d 0a 79 57 44 41 53 70  xCfEuw4i..yWDASp
+0x00000000029A5400  77 61 4e 31 39 47 61 50 4e 72 54 6c 57 7a 36 4b  waN19GaPNrTlWz6K
+0x00000000029A5410  37 4d 4b 58 47 72 41 51 70 59 44 35 67 4e 5a 38  7MKXGrAQpYD5gNZ8
+0x00000000029A5420  6e 47 64 66 52 67 70 35 32 54 45 72 54 48 53 4e  nGdfRgp52TErTHSN
+0x00000000029A5430  6f 52 6a 67 66 70 78 47 71 4b 0d 0a 41 70 50 55  oRjgfpxGqK..ApPU
+0x00000000029A5440  49 53 73 49 61 6e 47 4d 63 79 66 2f 48 32 62 38  ISsIanGMcyf/H2b8
+0x00000000029A5450  70 47 75 7a 31 6f 46 31 39 6b 56 4b 53 79 5a 54  pGuz1oF19kVKSyZT
+0x00000000029A5460  50 61 56 4c 62 45 2b 31 43 77 37 46 55 4c 62 49  PaVLbE+1Cw7FULbI
+0x00000000029A5470  30 34 62 63 36 34 58 6e 57 53 48 6f 0d 0a 61 51  04bc64XnWSHo..aQ
+0x00000000029A5480  41 58 72 59 4b 47 70 43 37 6f 44 6f 6d 52 47 4d  AXrYKGpC7oDomRGM
+0x00000000029A5490  74 78 32 38 66 69 67 75 33 41 48 41 6b 31 55 51  tx28figu3AHAk1UQ
+0x00000000029A54A0  72 63 43 76 45 33 2b 30 49 54 54 41 37 58 38 78  rcCvE3+0ITTA7X8x
+0x00000000029A54B0  61 52 77 7a 36 2b 67 62 2b 75 4c 67 43 64 0d 0a  aRwz6+gb+uLgCd..
+0x00000000029A54C0  69 58 79 52 59 44 6f 64 47 38 69 2b 6b 6b 31 59  iXyRYDodG8i+kk1Y
+0x00000000029A54D0  49 74 33 66 32 6d 74 37 6a 48 2b 75 45 48 71 42  It3f2mt7jH+uEHqB
+0x00000000029A54E0  59 6a 49 66 76 76 6f 36 67 35 4d 5a 7a 34 4b 4e  YjIfvvo6g5MZz4KN
+0x00000000029A54F0  7a 37 45 77 63 36 2b 73 44 79 4f 38 62 6d 6c 58  z7Ewc6+sDyO8bmlX
+0x00000000029A5500  0d 0a 65 46 6e 48 6f 36 59 41 67 43 63 61 48 56  ..eFnHo6YAgCcaHV
+0x00000000029A5510  76 56 74 47 4e 43 78 43 64 31 4f 35 77 57 48 76  vVtGNCxCd1O5wWHv
+0x00000000029A5520  55 4e 39 38 35 48 48 51 59 6e 46 72 37 71 7a 4a  UN985HHQYnFr7qzJ
+0x00000000029A5530  61 4c 39 63 50 62 37 33 35 70 50 32 68 62 30 49  aL9cPb735pP2hb0I
+0x00000000029A5540  58 65 0d 0a 79 77 49 44 41 51 41 42 0d 0a 2d 2d  Xe..ywIDAQAB..--
+0x00000000029A5550  2d 2d 2d 45 4e 44 20 50 55 42 4c 49 43 20 4b 45  ---END PUBLIC KE
+0x00000000029A5560  59 2d 2d 2d 2d 2d 0d 0a a2 8c df 98 7b 3c 3a 79  Y-----......{<:y

//
// Begin Solution1
//
@+0x021F7390
Previous:
+0x00000000021F7390  44 37 35 31 32 35 42 37 30 37 36 37 42 39 34 31  D75125B70767B941
+0x00000000021F73A0  34 35 42 34 37 43 31 43 42 33 43 30 37 35 35 45  45B47C1CB3C0755E
+0x00000000021F73B0  37 43 43 42 38 38 32 35 43 35 44 43 45 30 43 35  7CCB8825C5DCE0C5
+0x00000000021F73C0  38 41 43 46 39 34 34 45 30 38 32 38 30 31 34 30  8ACF944E08280140
+0x00000000021F73D0  39 41 30 32 34 37 32 46 41 46 46 44 31 43 44 37  9A02472FAFFD1CD7
+0x00000000021F73E0  37 38 36 34 42 42 38 32 31 41 45 33 36 37 36 36  7864BB821AE36766
+0x00000000021F73F0  46 45 45 44 45 36 41 32 34 46 31 32 36 36 32 39  FEEDE6A24F126629
+0x00000000021F7400  35 34 31 36 38 42 46 41 33 31 34 42 44 39 35 30  54168BFA314BD950
+0x00000000021F7410  33 32 42 39 44 38 32 34 34 35 33 35 35 45 44 37  32B9D82445355ED7
+0x00000000021F7420  42 43 30 42 38 38 30 38 38 37 44 36 35 30 46 35  BC0B880887D650F5
After:
+0x00000000021F7390  44 37 35 31 32 35 42 37 30 37 36 37 42 39 34 31  D75125B70767B941
+0x00000000021F73A0  34 35 42 34 37 43 31 43 42 33 43 30 37 35 35 45  45B47C1CB3C0755E
+0x00000000021F73B0  37 43 43 42 38 38 32 35 43 35 44 43 45 30 43 35  7CCB8825C5DCE0C5
+0x00000000021F73C0  38 41 43 46 39 34 34 45 30 38 32 38 30 31 34 30  8ACF944E08280140
+0x00000000021F73D0  39 41 30 32 34 37 32 46 41 46 46 44 31 43 44 37  9A02472FAFFD1CD7
+0x00000000021F73E0  37 38 36 34 42 42 38 32 31 41 45 33 36 37 36 36  7864BB821AE36766
+0x00000000021F73F0  46 45 45 44 45 36 41 32 34 46 31 32 36 36 32 39  FEEDE6A24F126629
+0x00000000021F7400  35 34 31 36 38 42 46 41 33 31 34 42 44 39 35 30  54168BFA314BD950
+0x00000000021F7410  33 32 42 39 44 38 32 34 34 35 33 35 35 45 44 37  32B9D82445355ED7
+0x00000000021F7420  37 38 34 41 44 41 43 31 43 35 38 37 37 35 44 32  784ADAC1C58775D2

@+0x0074BD39
Previous:
+0x000000000074BD30  00 00 e8 b9 10 e0 ff 41 b8 fe ea bc 01 48 8d 15  .......A.....H..
After:
+0x000000000074BD30  00 00 e8 b9 10 e0 ff 41 b8 8a 73 20 05 48 8d 15  .......A..s .H..

@+0x021F70A0
Previous:
+0x00000000021F70A0  45 31 43 45 44 30 39 42 39 43 32 31 38 36 42 46  E1CED09B9C2186BF
+0x00000000021F70B0  37 31 41 37 30 43 30 46 45 32 46 31 45 30 41 45  71A70C0FE2F1E0AE
+0x00000000021F70C0  46 33 42 44 36 42 37 35 32 37 37 41 41 42 32 30  F3BD6B75277AAB20
+0x00000000021F70D0  44 46 41 46 33 44 31 31 30 46 37 35 39 31 32 42  DFAF3D110F75912B
+0x00000000021F70E0  46 42 36 33 41 43 35 30 45 43 34 43 34 38 36 38  FB63AC50EC4C4868
+0x00000000021F70F0  39 44 31 35 30 32 37 31 35 32 34 33 41 37 39 46  9D1502715243A79F
+0x00000000021F7100  33 39 46 46 32 44 45 32 42 46 31 35 43 45 34 33  39FF2DE2BF15CE43
+0x00000000021F7110  38 46 46 38 38 35 37 34 35 45 44 35 34 35 37 33  8FF885745ED54573
+0x00000000021F7120  38 35 30 45 38 41 39 46 34 30 45 45 32 46 46 35  850E8A9F40EE2FF5
+0x00000000021F7130  30 35 45 42 37 34 37 36 46 39 35 41 44 42 37 38  05EB7476F95ADB78
+0x00000000021F7140  33 42 32 38 43 41 33 37 34 46 41 43 34 36 33 32  3B28CA374FAC4632
+0x00000000021F7150  38 39 32 41 42 38 32 46 42 33 42 46 34 37 31 35  892AB82FB3BF4715
+0x00000000021F7160  46 43 46 45 36 45 38 32 44 30 33 37 33 31 46 43  FCFE6E82D03731FC
+0x00000000021F7170  33 37 36 32 42 36 41 41 43 33 44 46 31 43 33 42  3762B6AAC3DF1C3B
+0x00000000021F7180  43 36 34 36 46 45 39 43 44 33 43 36 32 36 36 33  C646FE9CD3C62663
+0x00000000021F7190  41 39 37 45 45 37 32 44 42 39 33 32 41 33 30 31  A97EE72DB932A301
+0x00000000021F71A0  33 31 32 42 34 41 37 36 33 33 31 30 30 43 38 43  312B4A7633100C8C
+0x00000000021F71B0  43 33 35 37 32 36 32 43 33 39 41 32 42 33 41 36  C357262C39A2B3A6
+0x00000000021F71C0  34 42 32 32 34 46 35 32 37 36 44 35 45 44 42 44  4B224F5276D5EDBD
+0x00000000021F71D0  46 30 38 30 34 44 43 33 41 43 34 42 38 33 35 31  F0804DC3AC4B8351
+0x00000000021F71E0  36 32 42 42 31 39 36 39 45 41 45 42 41 44 43 34  62BB1969EAEBADC4
+0x00000000021F71F0  33 44 32 35 31 31 44 36 45 30 32 33 39 32 38 37  3D2511D6E0239287
+0x00000000021F7200  38 31 42 31 36 37 41 34 38 32 37 33 42 39 35 33  81B167A48273B953
+0x00000000021F7210  33 37 38 44 33 44 32 30 38 30 43 43 30 36 37 37  378D3D2080CC0677
+0x00000000021F7220  37 45 38 41 32 33 36 34 46 30 32 33 34 42 38 31  7E8A2364F0234B81
+0x00000000021F7230  30 36 34 43 35 43 37 33 39 41 38 44 41 32 38 44  064C5C739A8DA28D
+0x00000000021F7240  43 35 38 38 39 30 37 32 42 46 33 37 36 38 35 43  C5889072BF37685C
+0x00000000021F7250  42 43 39 34 43 32 44 33 31 44 30 31 37 39 41 44  BC94C2D31D0179AD
+0x00000000021F7260  38 36 44 38 45 33 41 41 38 30 39 30 44 34 46 30  86D8E3AA8090D4F0
+0x00000000021F7270  42 32 38 31 42 45 33 37 45 30 31 34 33 37 34 36  B281BE37E0143746
+0x00000000021F7280  45 36 30 34 39 43 43 43 30 36 38 39 39 34 30 31  E6049CCC06899401
+0x00000000021F7290  32 36 34 46 41 34 37 31 43 30 31 36 41 39 36 43  264FA471C016A96C
+0x00000000021F72A0  37 39 38 31 35 42 35 35 42 42 43 32 36 42 34 33  79815B55BBC26B43
+0x00000000021F72B0  30 35 32 36 30 39 44 39 44 31 37 35 46 42 43 44  052609D9D175FBCD
+0x00000000021F72C0  45 34 35 35 33 39 32 46 31 30 45 35 31 45 43 31  E455392F10E51EC1
+0x00000000021F72D0  36 32 46 35 31 43 46 37 33 32 45 36 42 42 33 39  62F51CF732E6BB39
+0x00000000021F72E0  31 46 35 36 42 42 46 44 38 44 39 35 37 44 46 33  1F56BBFD8D957DF3
+0x00000000021F72F0  44 34 43 35 35 42 37 31 43 45 46 44 35 34 42 31  D4C55B71CEFD54B1
+0x00000000021F7300  39 43 31 36 44 34 35 38 37 35 37 33 37 33 45 36  9C16D458757373E6
+0x00000000021F7310  39 38 44 37 45 36 39 33 41 38 46 43 33 39 38 31  98D7E693A8FC3981
+0x00000000021F7320  35 41 38 42 46 30 33 42 41 30 35 45 41 38 43 38  5A8BF03BA05EA8C8
+0x00000000021F7330  37 37 38 44 33 38 46 39 38 37 33 44 36 32 42 34  778D38F9873D62B4
+0x00000000021F7340  34 36 30 46 34 31 41 43 46 39 39 37 43 33 30 45  460F41ACF997C30E
+0x00000000021F7350  37 43 33 41 46 30 32 35 46 41 31 37 31 42 35 46  7C3AF025FA171B5F
+0x00000000021F7360  35 41 44 34 44 36 42 31 35 45 39 35 43 32 37 46  5AD4D6B15E95C27F
+0x00000000021F7370  36 42 33 35 41 44 36 31 38 37 35 45 35 35 30 35  6B35AD61875E5505
+0x00000000021F7380  34 34 39 42 34 45 00 00 00 00 00 00 00 00 00 00  449B4E..........
After:
+0x00000000021F70A0  32 30 45 45 41 30 35 39 36 36 39 46 45 34 45 39  20EEA059669FE4E9
+0x00000000021F70B0  34 39 46 34 31 34 37 31 30 41 36 43 31 31 43 46  49F414710A6C11CF
+0x00000000021F70C0  36 38 42 35 33 31 38 42 34 34 35 44 32 44 30 43  68B5318B445D2D0C
+0x00000000021F70D0  41 38 35 34 37 31 45 39 44 43 33 38 32 46 32 37  A85471E9DC382F27
+0x00000000021F70E0  31 45 39 37 34 33 31 35 46 32 46 33 36 34 35 43  1E974315F2F3645C
+0x00000000021F70F0  32 36 31 33 42 46 36 30 36 36 39 35 38 34 43 46  2613BF60669584CF
+0x00000000021F7100  30 41 37 35 33 31 42 31 45 35 44 32 44 32 38 31  0A7531B1E5D2D281
+0x00000000021F7110  30 39 37 45 33 32 41 36 42 31 37 32 38 36 45 38  097E32A6B17286E8
+0x00000000021F7120  41 39 42 44 44 30 36 41 31 37 41 30 33 36 42 43  A9BDD06A17A036BC
+0x00000000021F7130  38 39 34 39 43 39 30 36 39 43 41 33 41 31 36 36  8949C9069CA3A166
+0x00000000021F7140  43 32 35 31 44 33 32 35 41 37 45 41 46 38 31 44  C251D325A7EAF81D
+0x00000000021F7150  42 32 37 32 43 46 34 45 32 37 37 43 43 34 38 37  B272CF4E277CC487
+0x00000000021F7160  44 36 42 41 43 42 38 33 43 31 30 35 39 42 42 43  D6BACB83C1059BBC
+0x00000000021F7170  30 44 34 35 46 34 39 43 42 42 36 45 41 32 43 30  0D45F49CBB6EA2C0
+0x00000000021F7180  45 38 30 33 33 30 33 39 43 41 35 37 35 41 39 33  E8033039CA575A93
+0x00000000021F7190  39 43 38 46 46 37 30 35 46 46 41 31 46 43 41 39  9C8FF705FFA1FCA9
+0x00000000021F71A0  44 44 35 33 46 44 31 30 34 34 37 45 45 38 44 32  DD53FD10447EE8D2
+0x00000000021F71B0  46 34 38 31 32 38 32 39 38 45 35 44 41 42 34 38  F48128298E5DAB48
+0x00000000021F71C0  33 46 37 41 31 35 30 30 43 34 35 35 41 46 45 33  3F7A1500C455AFE3
+0x00000000021F71D0  33 42 42 37 46 42 32 38 30 43 33 39 36 38 36 43  3BB7FB280C39686C
+0x00000000021F71E0  43 34 35 43 37 45 43 38 43 30 32 34 45 42 46 31  C45C7EC8C024EBF1
+0x00000000021F71F0  30 38 39 30 34 30 44 36 36 33 36 46 46 30 32 45  089040D6636FF02E
+0x00000000021F7200  30 45 32 41 36 31 30 39 32 31 36 38 41 35 43 42  0E2A61092168A5CB
+0x00000000021F7210  31 30 35 44 42 46 33 46 35 43 36 45 42 35 43 31  105DBF3F5C6EB5C1
+0x00000000021F7220  30 44 37 33 39 32 41 34 36 32 35 34 42 36 45 33  0D7392A46254B6E3
+0x00000000021F7230  34 44 44 34 33 36 35 46 37 37 38 45 44 31 39 39  4DD4365F778ED199
+0x00000000021F7240  41 35 32 43 36 41 42 39 33 31 34 31 36 34 35 33  A52C6AB931416453
+0x00000000021F7250  43 42 38 41 36 37 37 43 39 30 41 36 36 37 34 42  CB8A677C90A6674B
+0x00000000021F7260  41 35 44 35 34 36 42 32 35 43 44 45 43 39 43 32  A5D546B25CDEC9C2
+0x00000000021F7270  45 30 42 30 36 37 37 32 39 41 36 30 36 37 46 42  E0B067729A6067FB
+0x00000000021F7280  31 31 30 36 42 33 42 46 37 42 42 44 35 36 42 38  1106B3BF7BBD56B8
+0x00000000021F7290  38 38 42 35 33 32 31 34 38 34 37 37 39 35 37 30  88B5321484779570
+0x00000000021F72A0  30 34 30 42 32 30 39 35 43 44 34 31 30 44 33 42  040B2095CD410D3B
+0x00000000021F72B0  33 33 46 37 37 42 43 46 43 39 43 32 34 43 41 35  33F77BCFC9C24CA5
+0x00000000021F72C0  41 36 30 30 30 33 45 33 34 32 46 31 31 30 44 33  A60003E342F110D3
+0x00000000021F72D0  35 41 41 34 37 31 34 42 46 43 38 42 33 44 39 38  5AA4714BFC8B3D98
+0x00000000021F72E0  34 30 42 42 33 43 38 43 32 38 36 43 35 45 33 35  40BB3C8C286C5E35
+0x00000000021F72F0  33 44 35 44 45 43 34 33 35 31 41 32 37 45 36 45  3D5DEC4351A27E6E
+0x00000000021F7300  34 30 33 41 45 44 32 41 32 31 42 42 44 30 45 41  403AED2A21BBD0EA
+0x00000000021F7310  34 31 39 34 46 42 36 35 42 33 37 46 33 30 31 41  4194FB65B37F301A
+0x00000000021F7320  32 45 38 36 42 46 39 45 39 46 38 42 42 42 46 41  2E86BF9E9F8BBBFA
+0x00000000021F7330  41 32 34 30 30 34 31 30 41 42 43 37 38 33 33 42  A2400410ABC7833B
+0x00000000021F7340  33 43 43 41 41 43 36 36 46 32 37 46 38 37 33 39  3CCAAC66F27F8739
+0x00000000021F7350  39 30 45 32 44 39 37 42 42 33 36 41 37 30 41 35  90E2D97BB36A70A5
+0x00000000021F7360  43 39 45 34 45 33 36 34 37 43 33 41 44 30 46 41  C9E4E3647C3AD0FA
+0x00000000021F7370  41 37 31 36 38 32 30 41 30 42 44 43 31 35 43 41  A716820A0BDC15CA
+0x00000000021F7380  38 44 37 33 39 32 00 00 00 00 00 00 00 00 00 00  8D7392..........

@+0x0074BD1F
Previous:
+0x000000000074BD10  8d 0d ea 10 02 00 ff 15 ec 61 a3 01 90 41 b8 59  .........a...A.Y
+0x000000000074BD20  08 01 00 48 8d 15 ee 08 6c 02 48 8d 8c 24 70 01  ...H....l.H..$p.
After:
+0x000000000074BD10  8d 0d ea 10 02 00 ff 15 ec 61 a3 01 90 41 b8 08  .........a...A..
+0x000000000074BD20  47 00 00 48 8d 15 ee 08 6c 02 48 8d 8c 24 70 01  G..H....l.H..$p.

@+0x021F708C
Previous:
+0x00000000021F7080  31 32 32 35 4f 45 29 2e 00 00 00 00 39 32 39 33  1225OE).....9293
+0x00000000021F7090  33 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  3...............
After:
+0x00000000021F7080  31 32 32 35 4f 45 29 2e 00 00 00 00 36 34 33 30  1225OE).....6430
+0x00000000021F7090  38 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  8...............

Solution0 has been done successfully.
Solution1 has been done successfully.

D:\Program Files\PremiumSoft\navicat-keygen-for-x64>navicat-keygen.exe -text .\RegPrivateKey.pem
Select Navicat product:
0. DataModeler
1. Premium
2. MySQL
3. PostgreSQL
4. Oracle
5. SQLServer
6. SQLite
7. MariaDB
8. MongoDB
9. ReportViewer

(Input index)> 1

Select product language:
0. English
1. Simplified Chinese
2. Traditional Chinese
3. Japanese
4. Polish
5. Spanish
6. French
7. German
8. Korean
9. Russian
10. Portuguese

(Input index)> 1

(Input major version number, range: 0 ~ 15, default: 12)> 12

Serial number:
NAVN-DNSM-TOED-X57H

Your name: C1
Your organization: C1

Input request code (in Base64), input empty line to end:
HyivtPEL9C0BwDMajKAukhvrdIM12D4nEaHbFgrBMXNLvji7ObzFDwLl4Ml2lLUEz4dtvDhQpju03pI1PtFPybaLDORILnV1f28S47Jer0MjpQoWBB8+Yh4QrZvGmqUl7eM0ahFrniQ7acySzoARZr2Jyen9x6/EzqQoOUCHlA75wmp/Yq367ncj/XR38J18p9eVkw8YeEE9/B27KfcfYzay8KUsRlBRyCt/IzyC/TH7JeOUqOBOM+nWx1VedD4f+DbaeRGixrM/0ak+vP25ZtSGIAGLhblHyoC9Uq82idz9WJlv0S1+ewK/ygTOIHUxdE1V86ImP0qJoV9AEP1hnQ==

@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

D:\Program Files\PremiumSoft\navicat-keygen-for-x64>

**Comment by DoubleLabyrinth** [comment]
我已经知道了。#215

**Comment by 6897889** [comment]
怎么处理啊

**Comment by 6897889** [comment]
@DoubleLabyrinth 这个问题怎么处理啊

**Comment by DoubleLabyrinth** [comment]
这个问题我也在想办法。慢慢等吧

**Comment by Renshk** [comment]
Navicat 这么频繁的更新，看来是针对中文版的用户的反盗版了

**Comment by dragonflylee** [comment]
> 怎么处理啊

使用旧版本激活

**Comment by uranus829** [comment]
我也是激活不了！！

**Comment by DoubleLabyrinth** [comment]
https://github.com/DoubleLabyrinth/navicat-keygen/issues/215#issuecomment-454787894
我在这里写了一份pre-release，只对64位的navicat premium有用，大家可以先用用看。

**Comment by DoubleLabyrinth** [comment]
最新的release应该解决了这个问题，大家可以先试试看。
如果还有问题欢迎reopen
