### ISSUE TITLE
Navicat Premium 12.1.12激活失败

### ISSUE THREAD

**Issue by Safe-And-Sound** [DoubleLabyrinth/navicat-keygen#220]
提交机器码时返回@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 212
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.
机器码如下U1VHwLfy4Wk8N69PTcdHRr3cd9TvBUb4NU1pUz8FyCPyYD/3+7SGeV74CQiJcJCKaGRmrEC6Q31HODM66zwYbmZ6fazW6+9Q6jk9oQJCpO1tvPf+8RZtiiSQcUZyJf9x60qmPBEKBuZi3uqnRRo5CahzxaXTbbLCVZRL8pFvsksy0kOV/b0DF0gDPDxJRSu2vNksEA69kF00z6/LvrbaUpJ5fpDUTMbMFjInx/b+nGi1CRyupmPEJ7Ylm2O5nQkVFDRXo6vHr7hqO0jbkRqjRETv3nrt3PfhlOdrmnCBi69cIbeWhTMz3va59+4VKUfLtAAM62RGyxvyhaYEnZdkvg==

**Comment by songchaoyuan** [comment]
这次的破解估计难度加大了, 作者似乎还在研究,官方频繁更换,似乎在针对中文版反盗

**Comment by tianshen1981** [comment]
我也碰到相同的问题，哪里能获得之前的版本呢？

**Comment by geekwutom** [comment]
@Function: main LINE: 140
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by Safe-And-Sound** [comment]
https://pan.baidu.com/s/1AWBuTMB9ZXP2caAjD1Butg
版本为12.1.9

**Comment by DoubleLabyrinth** [comment]
https://github.com/DoubleLabyrinth/navicat-keygen/issues/215#issuecomment-454787894
我在这里写了一份pre-release，只对64位的navicat premium 12.1.12有用，大家可以先用用看。

**Comment by songchaoyuan** [comment]
> [#215 (comment)](https://github.com/DoubleLabyrinth/navicat-keygen/issues/215#issuecomment-454787894)
> 我在这里写了一份pre-release，只对64位的navicat premium 12.1.12有用，大家可以先用用看。

已经激活,谢谢群主,发现在原来基础上,只需要执行破解,打开后就是显示激活的

**Comment by DoubleLabyrinth** [comment]
最新的release应该可以了。用法没太大变化，见readme即可。

**Comment by Safe-And-Sound** [comment]
感谢

**Comment by saltprune** [comment]
特地注册号来感谢作者，WIN10,64位 12.1.12注册成功，注意第一条命令后面不带PEM文件。
