### ISSUE TITLE
mac navicat 12.1.12 激活失败

### ISSUE THREAD

**Issue by mistbor** [DoubleLabyrinth/navicat-keygen#227]
输入request code后，提示 ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by DoubleLabyrinth** [comment]
我已经更新了mac分支，12.1.15版本应该没有问题了。请仔细阅读mac分支的README。

**Comment by mistbor** [comment]
> 我已经更新了mac分支，12.1.15版本应该没有问题了。请仔细阅读mac分支的README。

感谢，我升级到12.1.15后成功破解了！
