### ISSUE TITLE
[FAILURE][Windows] BIO_new_file fails

### ISSUE THREAD

**Issue by Old-ape** [DoubleLabyrinth/navicat-keygen#228]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：12.1.12

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
MESSAGE: PatchSolution2 will be omitted.

MESSAGE: PatchSolution1: Keywords[0] has been found: offset = +0x021f7390.
MESSAGE: PatchSolution1: Keywords[1] has been found: offset = +0x0074bd39.
MESSAGE: PatchSolution1: Keywords[2] has been found: offset = +0x021f70a0.
MESSAGE: PatchSolution1: Keywords[3] has been found: offset = +0x0074bd1f.
MESSAGE: PatchSolution1: Keywords[4] has been found: offset = +0x021f708c.

ERROR: @ RSACipher.hpp - Line 172
BIO_new_file fails.

```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by dragonflylee** [comment]
BIO_new_file fails. 说明读取RSA私钥的时候失败了，可能是 你传的私钥路径里面有空格或其他东西
建议吧私钥放在根目录或者不用加上私钥参数，让程序自己生成私钥

也可以试试这个图形化的 [注册机](https://github.com/DoubleLabyrinth/navicat-keygen/files/2812341/Navicat.zip)

**Comment by mengyilingjian** [comment]
1,Navicat Premium
2,version--12.1
3,Simplified Chinese
4,Windows
5,
MESSAGE: PatchSoluti

MESSAGE: PatchSoluti
MESSAGE: PatchSoluti
MESSAGE: PatchSoluti
MESSAGE: PatchSoluti
MESSAGE: PatchSoluti

ERROR: @ RSACipher.h
BIO_new_file fails.
6,图形化的 注册机 下载了解压不了。
这是公司的电脑，我自己的电脑没有出现这个问题。麻烦帮忙看下什么问题。感谢！！

**Comment by dragonflylee** [comment]
@mengyilingjian 推荐使用 [7-Zip](https://sparanoid.com/lab/7z/download.html) 解压
