### ISSUE TITLE
12.1.12 版本 一直在生成 key 也没有错误输出

### ISSUE THREAD

**Issue by sunjiaqing** [DoubleLabyrinth/navicat-keygen#229]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: ______

2. What is your Navicat language version? Check one of the following:
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: ______

3. What is your OS? Check one of the following:
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

4. Can you post console output here? If don't have, leave it empty.
```
Please post here
```

5. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

6. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by DoubleLabyrinth** [comment]
Navicat和注册机是对应的吗？比如32位Navicat用for-x86的注册机、64位Navicat用for-64的注册机。

**Comment by sunjiaqing** [comment]
删除了重新安装了最新版就可以了
