### ISSUE TITLE
[macOS] make all fails

### ISSUE THREAD

**Issue by kollyQAQ** [DoubleLabyrinth/navicat-keygen#231]
我的 Navicat 版本你是12（具体版本不知道在哪看，现在已经进不去软件了）
Mac版本是10.13.2

```
➜  navicat-keygen git:(mac) ll
total 176
-rw-r--r--   1 kolly  staff    11K  2 11 15:32 HOW_DOES_IT_WORK.md
-rw-r--r--   1 kolly  staff    11K  2 11 15:32 HOW_DOES_IT_WORK.zh-CN.md
-rw-r--r--   1 kolly  staff    34K  2 11 15:32 LICENSE
-rw-r--r--   1 kolly  staff   1.7K  2 11 15:32 Makefile
-rw-r--r--   1 kolly  staff   9.8K  2 11 15:32 README.md
-rw-r--r--   1 kolly  staff   9.8K  2 11 15:32 README.zh-CN.md
drwxr-xr-x   2 kolly  staff    64B  2 11 16:28 bin
drwxr-xr-x   8 kolly  staff   256B  2 11 15:32 navicat-keygen
drwxr-xr-x  17 kolly  staff   544B  2 11 15:32 navicat-patcher
➜  navicat-keygen git:(mac) make all
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/PrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
In file included from ./navicat-patcher/CapstoneDisassembler.cpp:1:
In file included from ./navicat-patcher/CapstoneDisassembler.hpp:4:
./navicat-patcher/Exception.hpp:46:23: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    const std::string _ErrorString;
                      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from ./navicat-patcher/CapstoneDisassembler.cpp:1:
In file included from ./navicat-patcher/CapstoneDisassembler.hpp:4:
./navicat-patcher/Exception.hpp:54:33: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        _ErrorString(_ErrorCode.message()) {}
                                ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
2 errors generated.
In file included from ./navicat-patcher/KeystoneAssembler.cpp:1:
In file included from ./navicat-patcher/KeystoneAssembler.hpp:4:
./navicat-patcher/Exception.hpp:46:23: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    const std::string _ErrorString;
                      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from ./navicat-patcher/KeystoneAssembler.cpp:1:
In file included from ./navicat-patcher/KeystoneAssembler.hpp:4:
./navicat-patcher/Exception.hpp:54:33: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        _ErrorString(_ErrorCode.message()) {}
                                ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
2 errors generated.
make: *** [patcher] Error 1
```

**Comment by DoubleLabyrinth** [comment]
你的g++版本是多少？至少我的是
```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

这个情况下编译是没有问题的。如果你有这个编译器的话，你可以在Makefile里把第一行的CC改成这个编译器。

**Comment by kollyQAQ** [comment]
➜  MacOS g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by kollyQAQ** [comment]
linux 的编译不是太懂  我上面的有问题吗  要怎么改

**Comment by DoubleLabyrinth** [comment]
这样吧，你把`./navicat-patcher/Exception.hpp`的头部由原来的
```cpp
#pragma once
#include <stddef.h>
#include <system_error>
```
改成
```cpp
#pragma once
#include <stddef.h>
#include <system_error>
#include <string>
```
看下，从报错来看应该是缺少了<string>头文件

**Comment by kollyQAQ** [comment]
谢谢  可以了  还有个问题 就是我怎么看我 Navicat 的具体版本 我只能看到是12版本的

**Comment by kollyQAQ** [comment]
因为看您的教程我需要确定我Navicat Premium 版本是否< 12.0.24

**Comment by kollyQAQ** [comment]
好的 我先按高于这个版本的方法试一下  辛苦解答  新年快乐

**Comment by kollyQAQ** [comment]
不好意思 再麻烦下 

➜  bin git:(mac) ✗ ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

PatchSolution0 ...... Omitted.
PatchSolution1 ...... Omitted.
PatchSolution2 ...... Omitted.
MESSAGE: Patch abort. None of PatchSolutions applied.

这个是什么问题啊

**Comment by DoubleLabyrinth** [comment]
出现这个问题多半是你的Navicat已经被修改过了。如果你不记得什么时候改过，那还是重装Navicat吧

**Comment by kollyQAQ** [comment]
重装了还是报一样的错误。。。

**Comment by dragonflylee** [comment]
@kollyQAQ 最新版下载链接 http://download.navicat.com/download/navicat121_premium_cs.dmg

**Comment by kollyQAQ** [comment]
@dragonflylee 大哥好人 谢谢了

**Comment by DoubleLabyrinth** [comment]
重装还出问题不太可能吧？最新版应该是没问题的，我做过测试了。

**Comment by guozhongzhou** [comment]
我的 gcc版本为Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
但是编译也是出现g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/PrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
In file included from ./navicat-patcher/CapstoneDisassembler.cpp:1:
./navicat-patcher/CapstoneDisassembler.hpp:2:10: fatal error: 
      'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./navicat-patcher/KeystoneAssembler.cpp:1:
./navicat-patcher/KeystoneAssembler.hpp:2:10: fatal error: 
      'keystone/keystone.h' file not found
#include <keystone/keystone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./navicat-patcher/PatchSolution0.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:5:
./navicat-patcher/CapstoneDisassembler.hpp:2:10: fatal error: 
      'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./navicat-patcher/PatchSolution1.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:5:
./navicat-patcher/CapstoneDisassembler.hpp:2:10: fatal error: 
      'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./navicat-patcher/PatchSolution2.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:5:
./navicat-patcher/CapstoneDisassembler.hpp:2:10: fatal error: 
      'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from ./navicat-patcher/main.cpp:6:
In file included from ./navicat-patcher/PatchSolutions.hpp:5:
./navicat-patcher/CapstoneDisassembler.hpp:2:10: fatal error: 
      'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [patcher] Error 1

**Comment by dragonflylee** [comment]
@guozhongzhou 

请确认您有没有安装 `openssl capstone keystone rapidjson`，可以使用 [brew](https://brew.sh/index_zh-cn.html) 安装 

您也可以使用 https://github.com/DoubleLabyrinth/navicat-keygen/issues/223#issuecomment-469120900 编译好的静态链接版本

**Comment by codedart2018** [comment]
think you . mark

**Comment by virtueqwl** [comment]
![image](https://user-images.githubusercontent.com/36782225/67654496-b5a70080-f988-11e9-9ec7-34fd6f1ed02e.png)
请问这个是什么原因
