### ISSUE TITLE
windows12.1.15是否可以激活？

### ISSUE THREAD

**Issue by clxit** [DoubleLabyrinth/navicat-keygen#232]
又更新了版本，不知道windows的是否可以激活？

**Comment by dragonflylee** [comment]
@clxit 经测试，此次更新只是更换了 keyword 的分布，混淆算法并未改变。
可以使用 https://github.com/DoubleLabyrinth/navicat-keygen/issues/8#issuecomment-457481535 这里的注册机激活

**Comment by clxit** [comment]
> @clxit 经测试，此次更新只是更换了 keyword 的分布，混淆算法并未改变。
> 可以使用 [#8 (comment)](https://github.com/DoubleLabyrinth/navicat-keygen/issues/8#issuecomment-457481535) 这里的注册机激活

谢谢
