### ISSUE TITLE
啥回应都没有,

### ISSUE THREAD

**Issue by songchaoyuan** [DoubleLabyrinth/navicat-keygen#236]
网址如下,https://www.navicat.com.cn/sponsorship/education/student
如果是学生或者教师的就有福啦,提供您的教师教育邮箱或者是学生邮箱即可申请

**Comment by songchaoyuan** [comment]
刚刚windows版本的12.1.15发布了,使用作者软件激活成功,谢谢!

**Comment by l972383630** [comment]
11.2 能破解吗
