### ISSUE TITLE
请问替换公钥报错呢

### ISSUE THREAD

**Issue by ydtg1993** [DoubleLabyrinth/navicat-keygen#237]
```
    Info: Keyword offset = +0x02ed1bc8
    Info: std::string::append(const char*) offset = +02613e44
MESSAGE: Generating new RSA private key, it may take a long time.
ERROR: FileName ./navicat-patcher/RSACipher.hpp - Line 173
BIO_new_file fails.
```

**Comment by DoubleLabyrinth** [comment]
请贴出具体的命令行上下文

**Comment by ydtg1993** [comment]
./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

PatchSolution0 ...... Ready to apply.
    Info: Keyword offset = +0x02d3c48c
PatchSolution1 ...... Omitted.
PatchSolution2 ...... Ready to apply.
    Info: Target function offset = +0x00f650a2
    Info: Keyword offset = +0x02ed1bc8
    Info: std::string::append(const char*) offset = +02613e44
MESSAGE: Generating new RSA private key, it may take a long time.
ERROR: FileName ./navicat-patcher/RSACipher.hpp - Line 173
BIO_new_file fails.
shichuanlongdeMac-mini:bin shichuanlong$ ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

PatchSolution0 ...... Ready to apply.
    Info: Keyword offset = +0x02d3c48c
PatchSolution1 ...... Omitted.
PatchSolution2 ...... Ready to apply.
    Info: Target function offset = +0x00f650a2
    Info: Keyword offset = +0x02ed1bc8
    Info: std::string::append(const char*) offset = +02613e44
MESSAGE: Generating new RSA private key, it may take

**Comment by DoubleLabyrinth** [comment]
BIO_new_file失败的话可能是没有权限在当前目录下写，或者当前目录下RegPrivateKey.pem文件存在、但没有访问权限（如属主不对），请检查后再试。

**Comment by ydtg1993** [comment]
🙏谢谢大佬指教
