### ISSUE TITLE
一直卡在Generating new RSA privatekey，卡了2天多了

### ISSUE THREAD

**Issue by li-dw** [DoubleLabyrinth/navicat-keygen#238]
![image](https://user-images.githubusercontent.com/20960402/52985168-91744680-342d-11e9-942b-05835ae0c3d5.png)

**Comment by DoubleLabyrinth** [comment]
@li-dw 
4个PatchSolution全部忽略只能说明你的Navicat已经被修改过了，请重装Navicat再试。这个问题在 #223 里有人报告过，你可以看下。
