### ISSUE TITLE
[FAILURE]macOS] make all failure

### ISSUE THREAD

**Issue by solynyuan** [DoubleLabyrinth/navicat-keygen#239]
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/PrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'

**Comment by DoubleLabyrinth** [comment]
显然你的g++不支持c++17特性，请升级编译器再试

**Comment by solynyuan** [comment]
谢谢

**Comment by solynyuan** [comment]
升级到了7 还是报错呢

**Comment by solynyuan** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by solynyuan** [comment]
我用brew 升级到了 7 但是还是不支持

**Comment by solynyuan** [comment]
g++-8 (Homebrew GCC 8.2.0) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 

还是出错呢

**Comment by Milef** [comment]
这个编译器要怎么升呢？不太懂，只报了下边一行error，应该原因是同样的吧
error: invalid value 'c++17' in '-std=c++17'

**Comment by DoubleLabyrinth** [comment]
@Milef 
一般来讲你可以看下你的gcc是apple clang还是真正的GNU GCC。
```console
$ gcc --version
```
如果输出有`Apple LLVM version`字样，那就是apple clang，这个要升级你的Xcode才行。
如果有`Homebrew GCC`字样，那就要通过`brew upgrade gcc`升级。
如果都不是的话，那怎么升级恐怕还请google看看吧。

**Comment by Milef** [comment]
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
softwareupdate --list
Software Update Tool

Finding available software
No new software available.

**Comment by solynyuan** [comment]
我是点开mac系统更新 出现xcode那种要升级 然后升级就可以编译了

**Comment by Milef** [comment]
编译好了把系统从sierra升到mojave，然后xcode-select --install。
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

多谢两位 @solynyuan @DoubleLabyrinth
