### ISSUE TITLE
麻烦问一下能不能做个Navicat Data Modeler的破解

### ISSUE THREAD

**Issue by cntangt** [DoubleLabyrinth/navicat-keygen#24]
这个工具做数据库设计很好用，但是目前只有时间破解方法（试用时间破解），如果可以，非常感谢

**Comment by DoubleLabyrinth** [comment]
你可以看下issue #8，这是国外一个人写的navicat-keygen GUI版本，截图里有给Modeler的选项，你可以看下。

![atv9aql](https://user-images.githubusercontent.com/16631994/36847348-fe658954-1d98-11e8-9581-2ea122c84696.jpg)

**Comment by gwself** [comment]
试用期过了就不能用了额

**Comment by DoubleLabyrinth** [comment]
你很有可能只是输入了序列号，但没有完成离线激活部分。请继续完成离线激活部分看看

**Comment by 60999** [comment]
好像不支持：
D:\Program Files\PremiumSoft\Navicat Data Modeler>navicat-patcher.exe "D:\Program Files\PremiumSoft\Navicat Data Modeler\modeler.exe" .\RegPrivateKey.pem
@SetPath LINE: 27
ERROR: Path is not a directory.
The path you specified:
D:\Program Files\PremiumSoft\Navicat Data Modeler\modeler.exe

**Comment by qinkangdeid** [comment]
请问找到破解Data Modeler的方法了吗？

**Comment by wwb-89** [comment]
> 请问找到破解Data Modeler的方法了吗？

Navicat Premium里面集成了Data Modeler的功能啊，不需要找单独的破解。
