### ISSUE TITLE
Input request code (in Base64), input empty line to end: 

### ISSUE THREAD

**Issue by codedart2018** [DoubleLabyrinth/navicat-keygen#240]
这个什么时候返回结果呢！等了好久都没有返回！

`rabbitdeMacBook-Pro:bin rabbit$ ./navicat-keygen ./RegPrivateKey.pem 
Which is your Navicat Premium language?
0. English
1. Simplified Chinese
2. Traditional Chinese
3. Japanese
4. Polish
5. Spanish
6. French
7. German
8. Korean
9. Russian
10. Portuguese

(Input index)> 1
(Input major version number, range: 0 ~ 15, default: 12)> 12

Serial number:
NAVC-AV3D-AXSZ-U66X

Your name: rabbit
Your organization: rabbit

Input request code (in Base64), input empty line to end:
dawKYHK2VZPVq5ljH81ku1yW9b5AR7gkBg+S/jexfzE/4YSrjMWhIn9GFRCHYdaehCyOdBwlLWl0P0OespUI4sG3N2LweasyIC3rrSm5NJdHSfE42VCfbTap/HZpbYSyWmbEcD1VDlfkojdKUKFU0zojecKtxZ4iJAlgKqLszMDp6XlbR7Xkcl9Bx0s52YyXdeR932WCbfVRNvRkDjwkhqsx3rKj1iY9or1cgNjFcIxQGH27kb/ylpSMG9/e8Rwi4mHcoxcxIQNFNe53C4Z1lRVQjUGtGdX6bKrT+Lbwbhxf5SBRMguAqcKEtPidm3M3A0VfFVXaZW4NG5OSBVxy7Q==
`

**Comment by DoubleLabyrinth** [comment]
请仔细阅读README。

请求码是Navicat在选择手动激活时给出的，具体是多少还请你打开Navicat-->断网-->用注册机给定的Serial Number激活-->在弹出的对话框里选“手动激活”。这样应该就可以看到了。

**Comment by codedart2018** [comment]
我看到了 但是我输入后 等了好久都没有结果

**Comment by DoubleLabyrinth** [comment]
连按两下回车

**Comment by codedart2018** [comment]
@Function: main LINE: 140
ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.

**Comment by DoubleLabyrinth** [comment]
出现这个是说明你没有运行navicat-patcher，或者navicat-patcher运行没有成功。
如果你确定运行过navicat-patcher，麻烦贴出完整的命令行上下文

**Comment by codedart2018** [comment]
谢谢 我中间有个步骤走反了 贴出支付宝二维码来！&_& ^_^

**Comment by DoubleLabyrinth** [comment]
感谢你的好意，捐赠就不用了，大家用得开心就好。

**Comment by yanzefeng** [comment]
> 出现这个是说明你没有运行navicat-patcher，或者navicat-patcher运行没有成功。
> 如果你确定运行过navicat-patcher，麻烦贴出完整的命令行上下文

./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

PatchSolution0 ...... Ready to apply.
    Info: Keyword offset = +0x02d3c48c
PatchSolution1 ...... Omitted.
PatchSolution2 ...... Ready to apply.
    Info: Target function offset = +0x00f650a2
    Info: Keyword offset = +0x02ed1bc8
    Info: std::string::append(const char*) offset = +02613e44


我运行了这个命令还是，报这个140的错
