### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by TracyRyq** [DoubleLabyrinth/navicat-keygen#241]
$ cd navicat-patcher
$./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
-bash: ./navicat-patcher: No such file or directory

出现这个是为什么呢？

**Comment by TracyRyq** [comment]
我输入
 $ls bin/
navicat-keygen    navicat-patcher
也有这两个文件存在的

**Comment by zhanglin00129** [comment]
需要先编译，然后bin下面会看到可执行文件 
 $ make all 
 $ cd bin
 $./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

**Comment by zhanglin00129** [comment]
> 我输入
> $ls bin/
> navicat-keygen navicat-patcher
> 也有这两个文件存在的

进入bin文件夹执行

**Comment by TracyRyq** [comment]
哦哦 好的 谢谢
