### ISSUE TITLE
能不能给一个navicat for mac 12.0.18 的下载地址

### ISSUE THREAD

**Issue by REIGE** [DoubleLabyrinth/navicat-keygen#25]
我网上找的版本都和你版本不一样，激活按钮都不能点亮

**Comment by DoubleLabyrinth** [comment]
激活按钮不能点亮多半是因为版本不能匹配，比如你是英文版的navicat，但是你下的是给中文版navicat激活的注册机。

本repo的mac分支的README已经说明了mac下如何编译注册机以及如何使用，你可以参考说明再试。如果你不想编译，你可以到本repo的release里下载编译好的程序运行
