### ISSUE TITLE
Navicat Premium 版本 12.1，错误

### ISSUE THREAD

**Issue by wencyGit** [DoubleLabyrinth/navicat-keygen#252]
mac下下载最新Navicat Premium版本
wency$ codesign -f -s “wency” /Applications/Navicat\ Premium.app/
执行以上操作出现此错误 error: The specified item could not be found in the keychain.

请问这是什么原因呢？

**Comment by DoubleLabyrinth** [comment]
你确定你的Keychain.app（即钥匙串）里有wency这个证书吗？没有的话请先导入到keychain

**Comment by wencyGit** [comment]
@DoubleLabyrinth 请问你用什么来生成这个证书？

**Comment by wencyGit** [comment]
@DoubleLabyrinth 
我的目录下有 navicat-keygen  navicat-patcher wency.pem
wency.pem使用openssl x509 -text -noout -in wency.pem 生成
怎么将wency.pem导入到keychain呢？

**Comment by DoubleLabyrinth** [comment]
Keychain本身就可以生成证书。见 #50

**Comment by wencyGit** [comment]
@DoubleLabyrinth 
哈哈。。搞了一个下午终于破解了。
由于第一次使用mac 对此系统不了解。
说一下我按您的文档破解教程
在执行 ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium会生成一个新的RSA-2048私钥文件RegPrivateKey.pem
然后在访达（Finder）找到RegPrivateKey.pem双击打开，提示发生什么错。。。，别管，点击左上角钥匙串访问，选择证书助理 -> 创建证书
证书类型选择代码签名，身份类型选择自签名根证书，名称随便起，此名称便是文档$ codesign -f -s "foobar" /Applications/Navicat\ Premium.app/ 中对foobar，替换foobar即可。就这证书这里让我搞了一下午，现在终于破解

3Q

**Comment by HelloAndroidi** [comment]
win10 按照步骤一下子就激活成功了。
