### ISSUE TITLE
deepin 破解失败

### ISSUE THREAD

**Issue by LoserMr** [DoubleLabyrinth/navicat-keygen#253]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [√]Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：__最新的____

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [√ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [ ] macOS
   - [√ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
贴在这里
``` sudo wine navicat-patcher.exe '/home/yin_zhe/Downloads/navicat121_premium_cs_x64/Navicat' ./RegPrivateKey.pem

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）
sudo wine navicat-patcher.exe '/home/yin_zhe/Downloads/navicat121_premium_cs_x64/Navicat' ./RegPrivateKey.pem
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

MESSAGE: PatchSolution0 will be omitted.

ERROR: @ PatchSolution.hpp - Line 197
Invalid PE file.
0009:fixme:ver:GetCurrentPackageId (0x32fe24 (nil)): stub

**Comment by DoubleLabyrinth** [comment]
你确定你下的是for-x64的keygen而不是for-x86的keygen吗？

**Comment by LoserMr** [comment]
> 你确定你下的是for-x64的keygen而不是for-x86的keygen吗？

64位的 wine无效 32位对应32位软件可以破解成功

**Comment by DoubleLabyrinth** [comment]
那这样就是wine的问题。
反正for-x64的keygen只能给x64的navicat用，for-x86的keygen只能给x86的navicat用。务必保证版本对应。
至于怎么让wine运作，我也不知道。
