### ISSUE TITLE
Invalid PE file.

### ISSUE THREAD

**Issue by Cpaulyz** [DoubleLabyrinth/navicat-keygen#255]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
 Navicat MySQL

2. 你的Navicat版本号是多少？
   请写在这里：____12.1.17__

3. 你的Navicat产品语言版本是什么？选择下面一个：
Simplified Chinese

4. 你的操作系统是什么？选择下面一个：
   Windows

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
C:\Users\admin\Desktop\navicat-keygen-for-x86>navicat-patcher.exe "D:\Navicat"
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.
MESSAGE: PatchSolution0 will be omitted.

ERROR: @ PatchSolution.hpp - Line 197
Invalid PE file.
6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
你的Navicat是x86版本还是x64版本？

**Comment by kubeeliang** [comment]
你的Navicat产品类型是什么? 选择下面一个：
Navicat Premiun

你的Navicat版本号是多少？
请写在这里：__12.1.17(x64)

你的Navicat产品语言版本是什么？选择下面一个：
Simplified Chinese

你的操作系统是什么？选择下面一个：
Windows

你可以把命令行输出贴出来吗？如果你没有，请留空：
C:\Users\orderplus\Desktop\新建文件夹>navicat-patcher.exe "D:\Program Files\PremiumSoft\Navicat Premium 12" .\RegPrivateKey.pem
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

MESSAGE: PatchSolution0 will be omitted.

ERROR: @ PatchSolution.hpp - Line 197
Invalid PE file.

**Comment by DoubleLabyrinth** [comment]
@kubeeliang 
既然你的navicat是x64版本的，你确定你下载的是navicat-keygen-for-x64.zip而不是navicat-keygen-for-x86.zip？
