### ISSUE TITLE
12.0.22 简体中文64位版本，输入snkey之后无法点亮激活按钮

### ISSUE THREAD

**Issue by huantu284** [DoubleLabyrinth/navicat-keygen#26]
![image](https://user-images.githubusercontent.com/6276264/36958713-b29a9a54-2078-11e8-8656-104e445e6ee1.png)

**Comment by DoubleLabyrinth** [comment]
这个注册机是给navicat premium用的。你这个是navicat mysql。

如果你非要注册navicat mysql，请见#8
这个人写了一份navicat全系列的注册机，我想应该有用

**Comment by YuHangZM** [comment]
想使用 navicat for mysql ，你上面说的这个人是那个人？？？？

**Comment by YuHangZM** [comment]
想使用 navicat for mysql 12.0.26，你上面说的这个人是那个人？？？？

**Comment by DoubleLabyrinth** [comment]
开issue的，Deltafox79
