### ISSUE TITLE
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

### ISSUE THREAD

**Issue by EverydayLearning** [DoubleLabyrinth/navicat-keygen#263]
mac 在clone的时候出现error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60  这是什么问题

**Comment by DoubleLabyrinth** [comment]
这个问题和你的git或curl有关，不属于这个repo的问题。建议这个问题google搜索一下。
