### ISSUE TITLE
[FAILURE][MacOS] 编译失败

### ISSUE THREAD

**Issue by KeikoSong** [DoubleLabyrinth/navicat-keygen#264]
4. 你的操作系统是什么？选择下面一个：
   - [ ] macOS 10.12.6

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

编译失败

$ make all
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/PrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
make: *** [patcher] Error 1

请问是少安装了什么环境之类的吗？

**Comment by DoubleLabyrinth** [comment]
你的编译器不支持c++17特性，请升级编译器再试。

**Comment by KeikoSong** [comment]
請問怎麼升級編譯器呢？

**Comment by DoubleLabyrinth** [comment]
升级xcode

**Comment by KeikoSong** [comment]
試試看

另外看到一篇
http://cn.voidcc.com/question/p-naynqdpk-hr.html

不知道是否有幫助

**Comment by DoubleLabyrinth** [comment]
当然你可以试着修改下Makefile里的编译选项，也许`-std=c++17`换成`-std=c++1z`？不管怎样，编译通过即可。

**Comment by KeikoSong** [comment]
改好了～可以編譯成功～非常感恩！

不過我覺得這個如果對C++不太熟的人，要找這問題真的會不太清楚

**Comment by KeikoSong** [comment]
在編譯好的文件資料夾中執行
Keiko-MacBook:bin keikosong$ navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

會返回命令無效的回應
-bash: navicat-patcher: command not found

會是我編譯的檔案有問題嗎？

**Comment by DoubleLabyrinth** [comment]
navicat-patcher这个二进制程序是在clone下来的文件夹的bin文件夹下，你应该用cd命令进入bin文件夹然后运行navicat-patcher，即

```console
$ git clone -b mac https://github.com/DoubleLabyrinth/navicat-keygen.git
$ cd navicat-keygen
$ make all
...
..
$ cd ./bin   <-- 注意这里
$ ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
```

当然指定全路径也行。

**Comment by KeikoSong** [comment]
我改成全路徑方式執行了，非常感謝

**Comment by KeikoSong** [comment]
我覺得我真的很蠢...
從編譯開始每一步都有錯

當我下了指令
Keiko-MacBook:bin keikosong$ codesign -f -s "foobar" /Applications/Navicat\ Premium.app/
error: The specified item could not be found in the keychain.

因為我安裝的版本中沒有特別要備份什麼資料，當作全新安裝這樣嘗試破解

現在貌似回應是說鑰匙鏈中找不到資料？

**Comment by KeikoSong** [comment]
Your self-signed code-sign certificate name
這邊不太懂，怎麼知道我的證書名稱呢？

**Comment by DoubleLabyrinth** [comment]
首先有一点要告诉你，`foobar`一般是一个示例名，需要根据自己的情况做替换。
然后`Your self-signed code-sign certificate name`意思是“你的 __自签名__ 证书”，换句话说这个证书你是可以自己生成的，见https://github.com/DoubleLabyrinth/navicat-keygen/issues/50#issuecomment-416824334
