### ISSUE TITLE
不需断网的方式，直接让伺服器验证失败，转为手动启用

### ISSUE THREAD

**Issue by KeikoSong** [DoubleLabyrinth/navicat-keygen#265]
启用的时候，有一个可以设定代理的地方，伺服器位置随便填个数字，例如1.2.3.4，PORT也是随便，就可以使启用验证失效，就会跳出手动启用的选项了。

连Hosts都不需要改...

启用成功之后再把那个勾选取消掉即可

**Comment by hywhuangyuwei** [comment]
Linux下改无效代理服务器不可以。仍会提示激活次数达到上限。仍需要断网。
