### ISSUE TITLE
# navicat激活麻烦的替代方案

### ISSUE THREAD

**Issue by atovk** [DoubleLabyrinth/navicat-keygen#267]
大家可以尝试一下这款开源免费的软件 http://www.sequelpro.com/ 界面比较类似，切换应该没啥压力。

**Comment by jeeinn** [comment]
windows米有啊

**Comment by atovk** [comment]
> windows米有啊

workbanch 怎么样，我在ubuntu上用有点bug，windows 可以试试

**Comment by atovk** [comment]
我发现 sqquelpro 好久没有更新了，mac 下安装报错，需要在 xcode 里重新编译打包一下

**Comment by atovk** [comment]
> No MongoDB, no SQL Server, no.....
> No Linux, no Mac..
> Abandon it.

https://www.jetbrains.com/datagrip/
maybe this is option .
