### ISSUE TITLE
[FAILURE][ubuntu18.02] 破解12.1.18失败

### ISSUE THREAD

**Issue by xiaomingzhong** [DoubleLabyrinth/navicat-keygen#268]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：12.1.18

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [x] English
   - [ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [ ] macOS
   - [x] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
./navicat-patcher.sh
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

ERROR: @ _tmain.cpp - Line 39
ErrorCode = 0x00000003
ErrorString: Path not found.

Are you sure the path you specified is correct?
The path you specified:
Y:\navicat121_premium_en_x64\Navicat
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x23fce0 (nil)): stub
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
这个`navicat-patcher.sh`是 @zenuo 写的，请联系他来解决问题。

**Comment by zenuo** [comment]
@xiaomingzhong 
😥你好，请执行下面一行命令，并粘贴一下输出，谢谢
```bash
$ ls ~/.navicat64/dosdevices
```

**Comment by xiaomingzhong** [comment]
ls ~/.navicat64/dosdevices/
c:  d:  d::  y:  z:

**Comment by zenuo** [comment]
请问路径`~/.navicat64/dosdevices/y`下，有没有`navicat121_premium_en_x64`？

**Comment by xiaomingzhong** [comment]
ls ~/.navicat64/dosdevices/y\:
Android  Documents  flutter  navicat   Public  Templates  Videos
Desktop  Downloads  Music    Pictures  snap    tomcat7    vmware

navicat 是我改过的名字，我试一试不改文件夹名字@zenuo

**Comment by zenuo** [comment]
OK，目前的`navicat-patcher.sh`里的文件夹名称是写死为了`navicat121_premium_en_x64`，所以有如下错误：
```
ERROR: @ _tmain.cpp - Line 39
ErrorCode = 0x00000003
ErrorString: Path not found.

Are you sure the path you specified is correct?
The path you specified:
Y:\navicat121_premium_en_x64\Navicat
```

这里我再优化一下哈😀

**Comment by xiaomingzhong** [comment]
/navicat121_premium_en_x64$ ./navicat-patcher.sh 
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

ERROR: @ FileMapper.hpp - Line 57
ErrorCode = 0x00000020
ErrorString: Sharing violation.

fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x23fce0 (nil)): stub


我试了不改文件夹名字还是有这个问题

**Comment by zenuo** [comment]
Emm...请问运行这个脚本时，你有没有把Navicat关闭？

**Comment by xiaomingzhong** [comment]
Navicat 是开着的，@zenuo

**Comment by zenuo** [comment]
需要关闭Navicat哈；

因为navicat-patcher.exe会修改Navicat的某些文件，如果Navicat开着了，就会无法修改，报错`Sharing violation`；

关闭Navicat后再尝试一下？

**Comment by zenuo** [comment]
@xiaomingzhong 请问正常了吗？

**Comment by xiaomingzhong** [comment]
谢谢你！！！！！！！！！！！！！！！！！！@zenuo 解决了，操作步骤的问题

**Comment by zenuo** [comment]
好的，客气了；这个issus可以关闭了。
