### ISSUE TITLE
lib库问题

### ISSUE THREAD

**Issue by bequt** [DoubleLabyrinth/navicat-keygen#27]
没有用过vs编译，不知道vs自身有带上你的lib吗？准备进行一波编译。

**Comment by DoubleLabyrinth** [comment]
解决方案里的两个工程都依赖于OpenSSL库。
你可以在这里下载到：http://slproweb.com/products/Win32OpenSSL.html

只要在两个工程的属性-->VC++目录里设置好包含目录和库目录（注意x86和x64对应）即可

**Comment by bequt** [comment]
非常感谢。
