### ISSUE TITLE
ERROR: Failed to load RSA-2048 key.

### ISSUE THREAD

**Issue by Hao3o5** [DoubleLabyrinth/navicat-keygen#273]
执行到 ./navicat-keygen 2048key.pem  这一步的时候，报下面这个错：
@Function: main LINE: 52
ERROR: Failed to load RSA-2048 key.
求大神救救孩子，快折腾到凌晨4点了TT
…………………………………………………………
环境：Mac
软件及版本：Navicat for MySql 12.1
gcc 相关：~ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
(不知道什么原因这个版本的gcc 项目不能编过，改了makefile 文件的 gcc17 那行还是不行，最后只好用issue里一个同学提供的编译好的版本==)
主要是开头的问题，求大神救救孩子。

**Comment by DoubleLabyrinth** [comment]
这个2048key.pem文件的内容可以贴出来吗？
