### ISSUE TITLE
Download with 404 not found

### ISSUE THREAD

**Issue by ccw33** [DoubleLabyrinth/navicat-keygen#275]
在下载navicat-patcher.sh和navicat-keygen.sh时没有找到资源，下载是404 not found

curl -O -L https://raw.githubusercontent.com/DoubleLabyrinth/navicat-keygen/linux/bash/navicat-patcher.sh && \
chmod +x navicat-patcher.sh && \
curl -O -L https://raw.githubusercontent.com/DoubleLabyrinth/navicat-keygen/linux/bash/navicat-keygen.sh && \
chmod +x navicat-keygen.sh

**Comment by DoubleLabyrinth** [comment]
这种情况应该是你的网络问题，不妨试试挂个梯子？
