### ISSUE TITLE
[FAILURE][Ubuntu16.04LTS] ./navicat-patcher.sh: 17: ./navicat-patcher.sh: Bad substitution

### ISSUE THREAD

**Issue by duyanhan1995** [DoubleLabyrinth/navicat-keygen#277]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
     产品类型：Navicat Premium

2. 你的Navicat版本号是多少？
   请写在这里：___12.1.18___

3. 你的Navicat产品语言版本是什么？选择下面一个：
     简体中文

4. 你的操作系统是什么？选择下面一个：
     Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```shell
hi@hi-B360M-DS3H:~/soft/navicat121_premium_cs_x64$ ./navicat-patcher.sh 
./navicat-patcher.sh: 17: ./navicat-patcher.sh: Bad substitution
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
@zenuo

**Comment by zenuo** [comment]
@duyanhan1995 
请问在运行`navicat-patcher.sh`之前，有执行`start_navicat`吗？

**Comment by zenuo** [comment]
@duyanhan1995 

抱歉。根据[bash: Bad Substitution](https://stackoverflow.com/questions/20615217/bash-bad-substitution)的说法，请将`navicat-patcher.sh`的第一行由：

```bash
#!/bin/sh
```

改为：

```bash
#!/bin/bash
```

再试，如果正常，也请对`navicat-keygen.sh`做同样修改。

**Comment by zenuo** [comment]
@duyanhan1995 
请问如何了？

**Comment by duyanhan1995** [comment]
> @duyanhan1995
> 请问如何了？

你是不是更新了脚本，我直接用了最新的，然后就没有这个问题了

**Comment by zenuo** [comment]
> > @duyanhan1995
> > 请问如何了？
> 
> 你是不是更新了脚本，我直接用了最新的，然后就没有这个问题了

是的😿

**Comment by duyanhan1995** [comment]
> > > @duyanhan1995
> > > 请问如何了？
> > 
> > 
> > 你是不是更新了脚本，我直接用了最新的，然后就没有这个问题了
> 
> 是的😿

谢谢你啦，zenuo你真棒！！！:)

**Comment by zenuo** [comment]
> > > > @duyanhan1995
> > > > 请问如何了？
> > > 
> > > 
> > > 你是不是更新了脚本，我直接用了最新的，然后就没有这个问题了
> > 
> > 
> > 是的crying_cat_face
> 
> 谢谢你啦，zenuo你真棒！！！:)

😺谢谢
