### ISSUE TITLE
卡在了 Generating new RSA private key, it may take a long time.

### ISSUE THREAD

**Issue by zhaobingss** [DoubleLabyrinth/navicat-keygen#279]
Generating new RSA private key, it may take a long time.

**Comment by DoubleLabyrinth** [comment]
你能确定navicat是原版的吗？不能的话请删除navicat、重新安装。
如果你能确定，麻烦告知navicat版本号。

**Comment by fengzidk** [comment]
12.1.19.0

**Comment by DoubleLabyrinth** [comment]
@fengzidk 
我这边只有中文版的12.1.18，并且收不到12.1.19的更新，麻烦等一下吧。

**Comment by fengzidk** [comment]
我用在12.1.12上也是同样的效果

**Comment by DoubleLabyrinth** [comment]
@fengzidk 
你的情况是不是这个
https://github.com/DoubleLabyrinth/navicat-keygen/issues/223#issuecomment-463136643

**Comment by fengzidk** [comment]
@DoubleLabyrinth 12.1.12 确实是已经激活的版本,12.1.19.0 应该是第一次生成的私钥文件没找到,第二次生成时就挂了

**Comment by zhanglesheng** [comment]
> @DoubleLabyrinth 12.1.12 确实是已经激活的版本，12.1.19.0 应该是第一次生成的私钥文件没找到，第二次生成时就挂了


你可以重新在安装试一次，注意卸载要卸载干净，你可以这样操作，先生成密匙，直到输完版本号之后在打开软件，进行注册。

**Comment by zhanglesheng** [comment]
navicat 12 for myaql      12.1.19 成功 其他未测

**Comment by YoungDigua** [comment]
navicat premium 12.1.20也是卡在这里，重装后成功激活

**Comment by anubiszhou** [comment]
navicat premium 12.0.20 卡在这里，重装无效
