### ISSUE TITLE
Not a valid request code.

### ISSUE THREAD

**Issue by pengbs** [DoubleLabyrinth/navicat-keygen#28]
您好，我是win7 64位，下载的是navicat premium12.0.24版本，其他都正常，就是最后复制请求码后就出现Not a valid request code这个错误，导致没有生成激活码，求助
![tim 20180324162411](https://user-images.githubusercontent.com/13148394/37861943-dbafc2b4-2f7f-11e8-94a5-dbda5a49b953.png)

**Comment by DoubleLabyrinth** [comment]
请把RegPrivateKey.pem里的私钥和你的请求码以文本形式附上（不要截图）。

如果你已经关闭了console。请用备份的navicat.exe.backup恢复navicat.exe之后再试一次，并附上私钥和请求码

**Comment by pengbs** [comment]
附件已上传，非常感谢
[秘钥和请求码.txt](https://github.com/DoubleLabyrinth/navicat-keygen/files/1846014/default.txt)

**Comment by DoubleLabyrinth** [comment]
我检查了下你的私钥和请求码，发现无法用私钥解密请求码。

我能给出的意见就是：
1. 如果你的navicat是12.0.24以后的版本，请务必说下，我会更新版本、重新测试。
2. 如果不是，请用备份恢复navicat.exe，就在navicat的安装目录，备份文件navicat.exe.backup，然后重新打补丁。
3. 如果还是不行，有可能因为你的navicat在C:\Program Files下，请用管理员模式下的控制台再试。
4. 再不行就用Resource Hacker检查下navicat.exe里的RCData类型、名为“ACTIVATIONPUBKEY”的资源是不是能和私钥对上号，不能的话直接用Resource Hacker把私钥手动替换掉，再重新navicat-keygen激活

**Comment by pengbs** [comment]
非常感谢，按第2点重新操作就好了

**Comment by SissiMeow** [comment]
非常感谢！用Resource Hacker把ACTIVATIONPUBKEY里面的公钥替换成了RegPrivateKey.pem里面的私钥之后终于成功了，之前试过了重装/删注册表/恢复备份等等一系列操作都没有用

**Comment by wuzhaobo-IT** [comment]
你好为什么我用Resource Hacker 替换保存保持无效原始文件

**Comment by DoubleLabyrinth** [comment]
@wuzhaobo-IT 
Resource Hacker替换已经是很久以前的办法了，navicat早就不从resource里读取公钥了。

**Comment by wuzhaobo-IT** [comment]
那 Not a valid request code 这个有什么好的解决办法么

**Comment by DoubleLabyrinth** [comment]
@wuzhaobo-IT 
最新的release可以激活最新版本的navicat呀。如果不行，麻烦把navicat-patcher和navicat-keygen的输出都贴出来。
