### ISSUE TITLE
manjaro-deepin 12.1.18 找不到路径

### ISSUE THREAD

**Issue by WilliamTian0987** [DoubleLabyrinth/navicat-keygen#281]
```
Wine cannot find the ncurses library (libncurses.so.5).
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

ERROR: @ _tmain.cpp - Line 39
ErrorCode = 0x00000003
ErrorString: 找不到路径。

Are you sure the path you specified is correct?
The path you specified:
Y:\navicat\Navicat
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x22fce0 (nil)): stub
```
另:
在 ~/.navicat64/dosdevices/ 下 有 c y z三个盘符,但是都找不到对应的navicat路径

**Comment by DoubleLabyrinth** [comment]
@zenuo

**Comment by wenwenbaba** [comment]
me too.
online wait :)

**Comment by zenuo** [comment]
@WilliamTian0987 
你好，请问安装包解压路径在哪里？

**Comment by zenuo** [comment]
@wenwenbaba 
你好，使用Windows的话，请按照[文档](https://github.com/DoubleLabyrinth/navicat-keygen/blob/windows/README_FOR_WINDOWS.zh-CN.md)操作，这个Issue是在Linux下的错误。

**Comment by wenwenbaba** [comment]
我是按照windows的文档操作的。
![image](https://user-images.githubusercontent.com/38455727/58413036-5c216980-80aa-11e9-9a08-9ed4a0ca3125.png)

**Comment by zenuo** [comment]
@wenwenbaba 
请将红框所示的符号，更换成「半角的双引号」再试：
![image](https://user-images.githubusercontent.com/22318999/58413368-28930f00-80ab-11e9-8b56-70d418195d21.png)

参考：
```
navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12"
```

**Comment by wenwenbaba** [comment]
@zenuo 
谢谢，我也发现是这个问题。

**Comment by zenuo** [comment]
@wenwenbaba 
客气了，使用愉快。

**Comment by zenuo** [comment]
@WilliamTian0987 
请执行：
```
ls -l ~/.navicat64/dosdevices/
```

贴一下输出，谢谢。

**Comment by WilliamTian0987** [comment]
@zenuo 
![深度截图_选择区域_20190528082220](https://user-images.githubusercontent.com/48847346/58443019-cb867000-8121-11e9-83b2-95d1286feb31.png)
执行结果是:
lrwxrwxrwx 1 william william 33  4月 22  2018 c: -> /home/william/.navicat64/drive_c/
lrwxrwxrwx 1 william william 13  4月 22  2018 y: -> /home/william
lrwxrwxrwx 1 william william  1  4月 22  2018 z: -> /
昨天忘记带笔记本回去了...今天才看到

**Comment by WilliamTian0987** [comment]
@zenuo 解压包的路径在 Navicat的安装路径
![image](https://user-images.githubusercontent.com/48847346/58443058-12746580-8122-11e9-8453-35075eaa5bf5.png)

**Comment by zenuo** [comment]
好的，原因是目前的navicat-patcher.sh脚本假定安装路径在家目录下，所以暂时请你先将navicat文件夹移动到家目录，执行完破解步骤，再移动到/opt；

我尝试修复一下这个问题。

**Comment by zenuo** [comment]
@WilliamTian0987 
刚刚用的手机回复，故没有@，现在如何了。

**Comment by WilliamTian0987** [comment]
@zenuo 好的 我试试,感谢

**Comment by WilliamTian0987** [comment]
@zenuo 
![image](https://user-images.githubusercontent.com/48847346/58443653-db07b800-8125-11e9-927e-201aa68aac34.png)
移动到了/home/user 目录下,然后进入执行 还是一样的提示 找不到路径
![image](https://user-images.githubusercontent.com/48847346/58443661-f1ae0f00-8125-11e9-8ca5-8db900cb8a4a.png)

**Comment by zenuo** [comment]
@WilliamTian0987 
请将`~/navicat`及其子文件的属主修改为`william`，然后不使用`sudo`，再试试，命令为：
```
sudo chown -R william ~/navicat
./navicat-patcher.sh
```

**Comment by WilliamTian0987** [comment]
@zenuo 似乎可以了,原来权限也有关系,我再试试看 谢谢您

**Comment by WilliamTian0987** [comment]
@zenuo 已经成功,谢谢!这个我就关闭啦

**Comment by zenuo** [comment]
@WilliamTian0987  客气了，使用愉快。
