### ISSUE TITLE
替换公钥报错

### ISSUE THREAD

**Issue by 610278470** [DoubleLabyrinth/navicat-keygen#282]
```
./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

ERROR: FileName ./navicat-patcher/main.cpp - Line 92
ErrorCode = 0x00000002
ErrorString: No such file or directory
```

**Comment by zenuo** [comment]
试试：
```
./navicat-patcher "/Applications/Navicat Premium.app/Contents/MacOS/Navicat Premium"
```

**Comment by 610278470** [comment]
一样的错误

**Comment by 610278470** [comment]
之前第一次成功了，激活的时候报错：ERROR: Decrypt<RSACipher::KeyType::PrivateKey> fails.然后我在Keychain.app里面搜navicat删除了保存的链接，再重新替换公钥就发生了这种情况，重新下载navicat-keygen编译也失败

**Comment by zenuo** [comment]
@DoubleLabyrinth 请看下这个问题。

**Comment by DoubleLabyrinth** [comment]
@610278470 
麻烦运行
```
$ ls /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
```
看下这个文件还在不在。不在的话我也不知道是什么原因删除了（至少不会是程序的问题，因为程序里没有删除文件的代码），请麻烦重装navicat

**Comment by 610278470** [comment]
可以了，是少了这个文件，不过昨天不小心联网打开了navicat，导致现在就算断网也看不到注册窗口了。。这个是不是只能等14天试用期过了才能离线激活

**Comment by DoubleLabyrinth** [comment]
@610278470 
你可以试着将系统时间调到14之后看看。

**Comment by 610278470** [comment]
谢谢 激活成功

**Comment by BIGBbox** [comment]
Macintosh:~ Xxxxx$  ls /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
/Applications/Navicat Premium.app/Contents/MacOS/Navicat Premium
Macintosh:~ Xxxxx$ ./navicat-patcher "/Applications/Navicat Premium.app/Contents/MacOS/Navicat Premium"
-bash: ./navicat-patcher: No such file or directory
Macintosh:~ Xxxxx$


能帮忙看下这个吗
