### ISSUE TITLE
不能验证产生密钥

### ISSUE THREAD

**Issue by zhangwenge** [DoubleLabyrinth/navicat-keygen#284]
@Function: void __cdecl Process(class RSACipher *,int,int) LINE: 203
ERROR: Base64Decode fails.

**Comment by zhangwenge** [comment]
@zenuo 我的系统也是manjaro xfce 但是不行

**Comment by zenuo** [comment]
@zhangwenge 
请问是在执行`navicat-keygen.sh`时报错吗？是否是粘贴时没有粘贴正确的内容？

**Comment by zhangwenge** [comment]
是的在执行脚本的时候

**Comment by zhangwenge** [comment]
![MF8A 2}W1Q@PHB%BEIW_U00](https://user-images.githubusercontent.com/24795434/58849707-fe021100-86bd-11e9-9162-6d1003a7f518.png)

**Comment by zhangwenge** [comment]
执行到这步的时候卡住了，我按回车就会出现上面的错误

**Comment by zenuo** [comment]
请检查一下您粘贴的`Request Code`，是否与Navicat的`Request Code`相同？

**Comment by zhangwenge** [comment]
@zenuo 好了 你用的什么终端呀，我发现是我粘贴request code没有搞好

**Comment by zenuo** [comment]
![image](https://user-images.githubusercontent.com/22318999/58853000-45db6500-86cb-11e9-9d85-651be806975a.png)

**Comment by zhangwenge** [comment]
Unhandled exception: unimplemented function CRYPT32.dll.CryptImportPublicKeyInfoEx2 called in 64-bit code (0x000000007bc5fc7a).
Register dump:
 rip:000000007bc5fc7a rsp:00000000113bcc40 rbp:00000000113bcd80 eflags:00000202 (   - --  I   - - - )
 rax:000000007bc5fc30 rbx:ffffffffffffffff rcx:00000000113bcc60 rdx:0000000004161202
 rsi:0000000004174460 rdi:0000000004174494  r8:0000000040000000  r9:0000000000000000 r10:0000000000000002
 r11:00000000135aa9ee r12:0000000000000000 r13:0000000013596a77 r14:00000000134538f8 r15:00000000113bcd60
Stack dump:
System information:
    Wine build: wine-2.0.1
    Platform: x86_64
    Version: Windows XP
    Host system: Linux
    Host version: 4.19.45-1-MANJARO

运行之后wine报错了

**Comment by zhangwenge** [comment]
@zenuo  但是我用deepin-wine 启动 32位的可以，就是没法破解

**Comment by zenuo** [comment]
请问navicat的图形窗口是否能正常工作？若是的话，wine报错可以忽略。

**Comment by zhangwenge** [comment]
图像窗口不能工作，我目前用deepin-wine来启动32位的navicat但是没有被激活

**Comment by zenuo** [comment]
您的Navicat是什么版本？

**Comment by zhangwenge** [comment]
navicat121_premium_cs_x64，大神要不你远程我电脑写一个基于deepinwine的脚本

**Comment by zenuo** [comment]
您的系统是`Manjaro Deepin`吗？

**Comment by zenuo** [comment]
可以执行下`screenfetch`然后截图吗？

**Comment by zhangwenge** [comment]
![image](https://user-images.githubusercontent.com/24795434/58859877-657b8900-86dd-11e9-905f-8fd73d13b578.png)

**Comment by zhangwenge** [comment]
我之前是直接下载 32位的navicate.exe 直接用 deepin-wine 命令启动 之前安装了 deepin-qq

**Comment by zenuo** [comment]
只是下载了`navicat.exe`？不行的，因为还需要其他的库文件(安装目录的子文件夹Navicat下的dll我文件)；为了节省时间精力，建议您从官网下载完整安装包，然后按照[README_FOR_LINUX.zh-CN.md](https://github.com/DoubleLabyrinth/navicat-keygen/blob/windows/README_FOR_LINUX.zh-CN.md)操作。

**Comment by zhangwenge** [comment]
我后面是按照你们的说明去官网下载的，也破解成功了，就是启动navicate后去链接数据库，wine就报错后面navicate就直接退出了

**Comment by zenuo** [comment]
可以提供一下启动、报错过程的录屏吗？

**Comment by zhangwenge** [comment]
![深度录屏_选择区域_20190604155245](https://user-images.githubusercontent.com/24795434/58861510-1e8f9280-86e1-11e9-95fa-cdf19dc9d117.gif)

**Comment by zenuo** [comment]
我刚才在本地重新走了一遍，没有出现问题；麻烦你删除`/opt/navicat121_premium_en_x64`、`~/.navicat64`、`~/Navicat`后，在您的家目录下再走一遍流程，看看是否复现。

**Comment by zhangwenge** [comment]
我安装的时候选择的是中文，但是navicat-patcher.sh这个脚本的英文我修改了脚本，要不不能执行
![深度截图_选择区域_20190604163027](https://user-images.githubusercontent.com/24795434/58863975-7a104f00-86e6-11e9-93eb-0e5a382c69e1.png)
我把字符修改成中文可以正常执行

**Comment by zenuo** [comment]
改了这一处后，激活是否成功？运行navicat时的图形窗口的问题是否复现？

**Comment by zhangwenge** [comment]
刚刚试试了，没有激活 wine也会崩溃，我准备重新去下载navicat，在按装试试，感觉有些东西没有卸载干净

**Comment by zhangwenge** [comment]
我重装系统重新装现在好了

**Comment by zenuo** [comment]
好的，若没有其它问题，则可以关闭本issue了哈。
