### ISSUE TITLE
ubuntu18下破解错误

### ISSUE THREAD

**Issue by yangyang20** [DoubleLabyrinth/navicat-keygen#287]
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

MESSAGE: PatchSolution0 will be omitted.

MESSAGE: PatchSolution3 will be omitted.

MESSAGE: PatchSolution2 will be omitted.

MESSAGE: PatchSolution1 will be omitted.

MESSAGE: Generating new RSA private key, it may take a long time.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
ERROR: @ RSACipher.hpp - Line 127
ErrorCode = 0x24064064
ErrorString: error:24064064:random number generator:RAND_bytes:PRNG not seeded
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x23fce0 (nil)): stub

**Comment by zenuo** [comment]
@yangyang20 
你好，请问安装包是什么版本？是否从官网下载？

**Comment by DoubleLabyrinth** [comment]
@yangyang20 @zenuo 
这种情况已经是打了补丁之后又打补丁。https://github.com/DoubleLabyrinth/navicat-keygen/issues/223#issuecomment-463136643
麻烦重装navicat再试

**Comment by yangyang20** [comment]
好的,我把navicat卸载重装试下,,我是官网下的最新版本

**Comment by yangyang20** [comment]
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0

又报了这个错误,请问帮我看一下

**Comment by zenuo** [comment]
@yangyang20 
可忽略。

**Comment by yangyang20** [comment]
./navicat-keygen.sh
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
执行到这一步时没有出现选择Navicat产品类别、语言以及输入主版本号,还是报错

**Comment by r0ks** [comment]
需要安装libpng12这个包
ubuntu18.04已不再提供这个包，需要在/etc/apt/sources.list文件中添加一行:
deb http://security.ubuntu.com/ubuntu xenial-security main
然后执行apt update
apt install libpng12（或libpng12-0，有点记不清了）
之后即可正常执行keygen-patcher.sh与keygen-keygen.sh

**Comment by phpsaux** [comment]
I have the same problem, some onr solve this?
