### ISSUE TITLE
[FAILURE][Debian 4.9] 运行出错!

### ISSUE THREAD

**Issue by Cuiruhui** [DoubleLabyrinth/navicat-keygen#288]
1. 你的Navicat产品类型是什么? 选择下面一个：
   - [ √ ] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：__12.0.24____

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [ √ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [ ] macOS
   - [ √ ] Linux - Debian 4.9.168

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
/opt/navicat120_premium_cs_x64$ sudo ./navicat-patcher.sh
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

ERROR: @ FileMapper.hpp - Line 57
ErrorCode = 0x00000020
ErrorString: Sharing violation.

fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ver:GetCurrentPackageId (0x22fce0 (nil)): stub
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by zenuo** [comment]
@Cuiruhui 
你好，执行`navicat-patcher.sh`时，请关闭`Navicat`。

**Comment by Cuiruhui** [comment]
@zenuo 
谢谢您指出我的错误,我关掉后又出现下面的错误:
/opt/navicat120_premium_cs_x64$ sudo ./navicat-patcher.sh
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder

MESSAGE: PatchSolution0 will be omitted.

MESSAGE: PatchSolution3 will be omitted.

MESSAGE: PatchSolution2 will be omitted.

MESSAGE: PatchSolution1 will be omitted.

MESSAGE: Generating new RSA private key, it may take a long time.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)

请问这种情况是什么原因造成的,有什么办法解决吗?

**Comment by zenuo** [comment]
这是wine的报错，可以忽略，对本项目的激活无影响；创建`RSA private key`需要比较长的时间，请问创建成功没？

**Comment by DoubleLabyrinth** [comment]
@Cuiruhui @zenuo 
如果出现4个PatchSolution都omitted，那就是navicat打了补丁之后又打了补丁。https://github.com/DoubleLabyrinth/navicat-keygen/issues/223#issuecomment-463136643
请重装navicat再试。

**Comment by Cuiruhui** [comment]
@zenuo @DoubleLabyrinth 
谢谢回复,问题已经解决. 
经DoubleLabyrinth提醒,前期确实打过补丁,重新安装后一切都OK了~

**Comment by alukaa** [comment]
deepin15.10 上也有这个问题,PNG because unable to find libpng12.so.0,可以这样临时解决下
```
sudo ln -s /lib/i386-linux-gnu/libpng16.so.16 /usr/lib/libpng12.so.0

```

**Comment by Netease-163** [comment]
> deepin15.10 上也有这个问题,PNG because unable to find libpng12.so.0,可以这样临时解决下
> 
> ```
> sudo ln -s /lib/i386-linux-gnu/libpng16.so.16 /usr/lib/libpng12.so.0
> ```

加了软连接依然不起作用 deepin15.10.2

**Comment by alukaa** [comment]
有报错，不影响流程
