### ISSUE TITLE
mac 生成公钥失败

### ISSUE THREAD

**Issue by jing117** [DoubleLabyrinth/navicat-keygen#291]
make all 后 执行 ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium 后 是这样的 不知道哪里有问题 
```
bin git:(mac) ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 3.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

PatchSolution0 ...... Omitted.
PatchSolution1 ...... Omitted.
PatchSolution2 ...... Omitted.
MESSAGE: Patch abort. None of PatchSolutions applied.
```

**Comment by jing117** [comment]
12.1.22  是因为版本太新了吗

**Comment by china-enoch** [comment]
> 12.1.22 是因为版本太新了吗

你需要在 navicat-keygen/bin 目录下去执行。但是我执行到生成注册码的时候报错了。我也是 12.1.22 版本

**Comment by jing117** [comment]
> > 12.1.22 是因为版本太新了吗
> 
> 你需要在 navicat-keygen/bin 目录下去执行。我也是 12.1.22 这个版本。安装成功了。有什么你也可以问我。

是在这个目录执行的  要不会提示找不到./navicat-patcher    是把这个项目clone下来 然后直接make all编译  再执行  ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
但是显示的 不对 不知道是不是 少了什么步骤

**Comment by DoubleLabyrinth** [comment]
@jing117 
你的navicat已经被修改过了，请你删掉navicat并重装，确保是官方原版。
（很有可能你之前打过了补丁，结果忘了）

**Comment by jing117** [comment]
> @jing117
> 你的navicat已经被修改过了，请你删掉navicat并重装，确保是官方原版。
> （很有可能你之前打过了补丁，结果忘了）

成功了  非常感谢！

**Comment by jing117** [comment]
已解决 成功安装12.1.22 版本
