### ISSUE TITLE
请问12.1.23不支持嘛

### ISSUE THREAD

**Issue by GnixSung** [DoubleLabyrinth/navicat-keygen#295]
请问12.1.23不支持嘛

**Comment by kyle18th** [comment]
肯定支持啊，我刚刚才搞好Mac上的。

**Comment by Nirvana-Chen** [comment]
我电脑上的12.1.23注册码始终没有验证成功，不知道是哪里的问题

**Comment by Nirvana-Chen** [comment]
google了一下，确认问题了，官网下载的dmg需要确认版本，en是英文版，cs是简体中文

**Comment by BIGBbox** [comment]
好难搞啊。。。

**Comment by BIGBbox** [comment]
Cipher commands (see the `enc' command for more details)
aes-128-cbc       aes-128-ecb       aes-192-cbc       aes-192-ecb       
aes-256-cbc       aes-256-ecb       base64            bf                
bf-cbc            bf-cfb            bf-ecb            bf-ofb            
camellia-128-cbc  camellia-128-ecb  camellia-192-cbc  camellia-192-ecb  
camellia-256-cbc  camellia-256-ecb  cast              cast-cbc          
cast5-cbc         cast5-cfb         cast5-ecb         cast5-ofb         
chacha            des               des-cbc           des-cfb           
des-ecb           des-ede           des-ede-cbc       des-ede-cfb       
des-ede-ofb       des-ede3          des-ede3-cbc      des-ede3-cfb      
des-ede3-ofb      des-ofb           des3              desx              
rc2               rc2-40-cbc        rc2-64-cbc        rc2-cbc           
rc2-cfb           rc2-ecb           rc2-ofb           rc4               
rc4-40            

Macintosh:bin Xu_XIONG$ /Applications/Navicat Premium.app/Contents/Resources/rpk
-bash: /Applications/Navicat: No such file or directory
到这里进行不下去了，哪里出问题了啊

**Comment by DoubleLabyrinth** [comment]
@BIGBbox 
从你在多个issue下的回复来看，你似乎是在尝试执行`openssl genrsa -out RegPrivateKey.pem 2048`或`openssl rsa -in RegPrivateKey.pem -pubout -out rpk`。

不过我先问你，你确定你的navicat premium版本是小于 __12.0.24__ 的吗？据我所知，这个版本是一年多前的版本，我不太相信你手上还有这个版本。

如果不是，并且你成功执行上面两条命令中的任意一条，麻烦删掉navicat，全部重来。因为这会覆盖掉navicat-patcher给你的私钥文件。私钥丢了就已经救不回来了。如果没有成功执行上面的两条命令，那么跳过openssl这一步，因为我在README写的非常清楚了，只有12.0.24版本以下的navicat才需要生成rpk文件。

如果你的navicat是12.0.24版本以下的，那么
```
接着用刚生成的rpk文件替换
/Applications/Navicat Premium.app/Contents/Resources/rpk
```
这一步并不是一个命令，你需要手动替换。用mv命令，或者拖曳过去都行。

**Comment by BIGBbox** [comment]
我的刚好是12.1.24的版本

**Comment by DoubleLabyrinth** [comment]
@BIGBbox 
12.0.24版本和12.1.24版本一样吗？

**Comment by BIGBbox** [comment]
> @BIGBbox
> 12.0.24版本和12.1.24版本一样吗？

请问我这个版本能用吗

**Comment by BIGBbox** [comment]
> > @BIGBbox
> > 12.0.24版本和12.1.24版本一样吗？
> 
> 请问我这个版本能用吗

我重新操作然后跳过那个步骤

**Comment by DoubleLabyrinth** [comment]
你这个版本可以用。但是你不需要执行openssl那个命令，因为那是给版本号小于12.0.24的navicat用户用的。

**Comment by BIGBbox** [comment]
> 你这个版本可以用。但是你不需要执行openssl那个命令，因为那是给版本号小于12.0.24的navicat用户用的。

谢谢

**Comment by BIGBbox** [comment]
> 你这个版本可以用。但是你不需要执行openssl那个命令，因为那是给版本号小于12.0.24的navicat用户用的。

Macintosh:bin Xu_XIONG$ codesign -f -s "foobar" /Applications/Navicat\ Premium.app/
error: The specified item could not be found in the keychain.
Macintosh:bin Xu_XIONG$ 
麻烦看再看下个这个问题，🙏

**Comment by DoubleLabyrinth** [comment]
foobar只是例子，这个要换成你keychain里的代码签名证书的名字

**Comment by BIGBbox** [comment]
> @BIGBbox
> foobar只是例子，这个要换成你keychain里的代码签名证书的名字

这个是在钥匙串里新建一个证书，然后吧名字放到footar里，是这个意思吗

**Comment by DoubleLabyrinth** [comment]
对，用你的代码签名证书的名字替换foobar

**Comment by BIGBbox** [comment]
是把那个请求码粘贴到NavicatKeygen.hpp这个文件里吗，没看见keygen那个文件啊

**Comment by BIGBbox** [comment]
其中输错了一步这么办啊，能撤回吗，还是要从头来过啊
