### ISSUE TITLE
编译的时候出个问题是什么原因呀  - -！

### ISSUE THREAD

**Issue by QuinnGK** [DoubleLabyrinth/navicat-keygen#296]
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/PrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher @

**Comment by DoubleLabyrinth** [comment]
请贴出完整的console输出。

**Comment by mars-chen** [comment]
➜  navicat-keygen git:(mac) make all
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone -lplist++ ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/X64ImageInterpreter.cpp ./navicat-patcher/HelperIsResolvedTo.cpp ./navicat-patcher/HelperPrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
error: invalid value 'c++17' in '-std=c++17'
make: *** [patcher] Error 1

**Comment by DoubleLabyrinth** [comment]
@mars-chen 
你的编译器不支持c++17特性，请升级编译器再试。
