### ISSUE TITLE
[FAILURE][windows10 家庭中文版] 在激活Navicat Essentials Premium 12.1.20 64位 中文简体时输入序列号，手动激活按钮还是不可选中状态

### ISSUE THREAD

**Issue by oreuuz** [DoubleLabyrinth/navicat-keygen#298]
1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：Navicat Essentials Premium

2. 你的Navicat版本号是多少？
   请写在这里：12.1.20（64-bit）

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：Simplified Chinese

4. 你的操作系统是什么？选择下面一个：Windows
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
贴在这里
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   我在这台电脑上测试多次发现无法激活，于是在一台全新的win10电脑上（之前未安装过navicate）测试同样失败了.(RegPrivateKey.pem，和激活码可以正常生成)

**Comment by DoubleLabyrinth** [comment]
navicat12.0.20应该是没有问题的，我现在就在用。你可以说下你这边具体的表现是什么吗？

**Comment by DoubleLabyrinth** [comment]
为什么不直接用navicat premium呢，Essentials版本只是简化版。

**Comment by oreuuz** [comment]
感谢您的回应：
       我尝试过使用navicat premium 12 发现在使用的过程中存在连接数据库后第一次打开表或者存储过程或者执行查询命令的时候，navicat premium的这个窗口会卡死，查看数据库的进程其中不存在死锁的表，将navicat premium的连接时间设置为30秒，但是那个卡死的窗口会一直执行，过了30秒，窗口下方的状态栏中显示的查询时间会一直增加，这个时候程序无法关，只能通过任务管理器杀死进程的方式才能关闭程序。这个问题在Essentials版本上没有出现。

**Comment by DoubleLabyrinth** [comment]
刚才下了Essentials看了下，是可以激活的，但是得用navicat-keygen.exe的高级模式，即增加`-adv`参数。下面是我激活的样例
```console
$ navicat-keygen.exe -text -adv RegPrivateKey.pem
(Navicat Product ID, 0x00 ~ 0xFF)> 0x67
(Navicat Language Signature 0, 0x00 ~ 0xFF)> 0xce
(Navicat Language Signature 1, 0x00 ~ 0xFF)> 0x32
(Input major version number, range: 0 ~ 15, default: 12)> 12

Serial number:
NAVF-DWXK-KFDG-F4UP

...
...
// 后面和readme里的一样
```

**Comment by oreuuz** [comment]
太感谢您了，稍后我测试下。

**Comment by oreuuz** [comment]
感谢大佬，完美激活了。

**Comment by dragonflylee** [comment]
@oreuuz 其实关掉 选项-编辑器-使用自动完成代码 就不会产生卡顿问题了

Essentials 阉割掉了这个功能
