### ISSUE TITLE
有Mac的解方法吗？

### ISSUE THREAD

**Issue by Shomer-Lan** [DoubleLabyrinth/navicat-keygen#3]
看着吾爱破解的说明试了N多次，依旧没有搞定！

**Comment by DoubleLabyrinth** [comment]
你在哪里出现了问题请直接说明，不要就说句没有搞定了事，对我们开发者来说没有任何信息是很让我们为难的。

**Comment by Shomer-Lan** [comment]
您好：
  非常抱歉！在此表示歉意，昨天(2017年12月20日)没能在GitHub的留言中详细叙述遇到的问题便急急提交，请见谅。是这样的：
背景简述：
安装的Navicat Premium版本，是从官网下载的最新macOS Navicat Premium版本 12。
安装环境，是Mac pro电脑；系统版本，是macOS High Sierra版本 10.13.2。
操作步骤_1：
1. Navicat Premium安装完成并替换文件(rpk)。
2. 打开Navicat Premium，输入序列号(NAVF-ZCE3-FDCB-46BX)，且“名”和“组织”无法填写。
3. 系统提示“现在激活来完成Navicat的激活进程。Please activate  before  2018/01/18”，且“激活”按钮激活。
4. 点击“激活”按钮，加载中……。
5. 激活失败。提示“激活失败。原因可能是由于已达到激活次数的上限。请检查你是否已在卸载或重新安装 Navicat 前取消激活许可证密钥”。
6. 点击“手动激活”，获得请求码。
7. 终端(Terminals)进入所在目录，运行 ./navicat-keygen private.pem。几次尝试运行，分别提示“没有该文件”、“是一个空目录”、“没有操作权限”。
8. 激活失败，结束。
操作步骤_2：
1. Navicat Premium安装完成并替换文件(rpk)。
2. 终端(Terminals)进入所在目录，运行 ./navicat-keygen private.pem。几次尝试运行，分别提示“没有该文件”、“是一个空目录”、“没有操作权限”。
3. 激活失败，结束。

若有问题，随时沟通；若有言说不明，望海涵，我们继续沟通：）

**Comment by DoubleLabyrinth** [comment]
> 终端(Terminals)进入所在目录，运行 ./navicat-keygen private.pem。几次尝试运行，分别提示“没有该文件”、“是一个空目录”、“没有操作权限”。

这里能不能提供下截图？按道理讲应该是可以的，从你的描述来看你可能的问题是进错了目录或者敲错了命令，我需要你提供下截图确认下你的操作。

ps：你给的叙述真的太详细了，能见到你这样的反馈者真的是福分:-)

**Comment by Shomer-Lan** [comment]
谢谢！
抱歉，终端运营后没能再现昨天的提示，同时出现了新的反馈。

**Comment by Shomer-Lan** [comment]
截图发你了，但GitHub上好像没有展示出来。你邮箱内有收到吗？

**Comment by DoubleLabyrinth** [comment]
很抱歉并没有收到，请在github的本issue页面中提交截图（截图拖到评论区就可以了，preview可以看到预览），似乎邮箱回复好像没用。

**Comment by Shomer-Lan** [comment]
截图如下：
<img width="678" alt="default" src="https://user-images.githubusercontent.com/23181092/34199504-f361a722-e5a8-11e7-97d2-b441f2dd5e06.png">

**Comment by DoubleLabyrinth** [comment]
情况应该是你的mac上没有OpenSSL组件，你需要安装好OpenSSL组件之后重新编译代码。但是我觉得你应该不具备这样的能力。所以你还是替换完rpk文件之后将navicat生成的请求码贴出来，我帮你生成一份激活码吧。

**Comment by Shomer-Lan** [comment]
那真是太感谢了！！！有劳了，请求码如下：
HrH0zUO8p2JyV6oe+6CuqlqcjtqsOhHkMBjVC/YuWRmcD6vC2KZE95hIXqe5TXgcY7VgEkzFJcFu
1pitfS6HTn9lrHRkTsHE07Ro8ycz8jfQwpf00liBvAjbUY9j8TlsPeKSfAQqzeCsObRAPvk8yOq7
FYkCgpxCG8cAZYHBP7t/WfvZTs7VXlHTNGyMAXOnQH5XHGj/LnDUOBSK8PyJdR/S3mTij7lU2jTx
5sgGjOAc/oVF+FanXLztnrF+ANvN4K+sTlmG+lBylQe3mDAAb/hUpLhyKcMiaKvDE0Rs4gwwVeMl
jWe1uA+SfjH6DQqDVF5RIhQx+/QnMXk+IlmlIA==

**Comment by DoubleLabyrinth** [comment]
你似乎没有替换对应的rpk文件，因为你的请求码我没法解密。
请确认替换之后在贴出新的请求码

**Comment by Shomer-Lan** [comment]
劳烦帮忙再试下看。不知道是不是替换的过程中出错了，这次我是直接删除了原来的rpk文件后，把附件包里的rpk放进去的。请求码如下：
fRN2/5eSDo+9C/x90YX1AeoxI0eq2J1V9mQzx+kRWRWOot072JFMJm0ZjdaG3ETyr9K8+EMYd4Ju
4sQ2ZJu/rLpwffvwMH39QLRrCuwSrGfAzXlsjUlV0fJPTSsglrXaqaANMqO60u3lJ2kGPptiJDkH
iSuicITyN55Oy8Rpauc98oIsXObGSVVPSAJVKSAJIaEouAOmIc/qbznsBL4+HrYCZxXpGRcFrIoR
VpVlbhkK3wfAM3CkH+n/EcjCPJ1+h/pPUoooe8/WrVuQGksn6hHtfkPpjHSBRj2cAmolyQGLYDyL
MVRWuetmgvmcW8cpp2NKixZUovNCPIThK/bzxQ==

**Comment by DoubleLabyrinth** [comment]
Wx8Ig+j6OBPqGF5czHJA9mphf81E9QLcjE2lyADBus+UZdt/YcO+/Vj+L72xP5MlxbX+nArkZu9tb6ceIxwrYoQLbSfF+qcZHEbO0s65tnzQodYG+4mEXxAGi6YtY4UzscdNLivngGZ2hpM0oqdOwHiDJC7qqUegHgLlB+YLIPuJovk2XI0+vAZ0Ol5tBSOSbsINsR0+qpvj1/MVozG4/AmTFAp/qTH8zhbG3mvJnbxt4aR/ILMitTJMbRAT4k0Wqf3tI15yo6ruKXlk6fJzJMElfdtPN3ni7am0XUAscbZ9MuSiDajf3Awfuc2fmmDAbBmlh5UPnJsCG0sXkNuOaQ==

**Comment by Shomer-Lan** [comment]
非常感谢！！！搞定了：）

> 在 2017年12月20日，下午6:05，Double Sine <notifications@github.com> 写道：
> 
> Wx8Ig+j6OBPqGF5czHJA9mphf81E9QLcjE2lyADBus+UZdt/YcO+/Vj+L72xP5MlxbX+nArkZu9tb6ceIxwrYoQLbSfF+qcZHEbO0s65tnzQodYG+4mEXxAGi6YtY4UzscdNLivngGZ2hpM0oqdOwHiDJC7qqUegHgLlB+YLIPuJovk2XI0+vAZ0Ol5tBSOSbsINsR0+qpvj1/MVozG4/AmTFAp/qTH8zhbG3mvJnbxt4aR/ILMitTJMbRAT4k0Wqf3tI15yo6ruKXlk6fJzJMElfdtPN3ni7am0XUAscbZ9MuSiDajf3Awfuc2fmmDAbBmlh5UPnJsCG0sXkNuOaQ==
