### ISSUE TITLE
12.0.25 x64 EN 诡异无法激活

### ISSUE THREAD

**Issue by wzxjohn** [DoubleLabyrinth/navicat-keygen#30]
1. 替换资源后，用 Resource Hacker 看 exe 文件的私钥已经改变，与 patch 程序生成的相符
2. 用 kengen 始终提示解密 Request Code 失败

感觉新版是不是不从这里取 Key 了。。。

**Comment by DoubleLabyrinth** [comment]
已经知道了，有时间我会用IDA看下

**Comment by Deltafox79** [comment]
@DoubleLabyrinth @dragonflylee

Difference v12.0,24 to 12.0.25

**12.0.24**

1) 12.0.24 offset public Key in Resource

https://i.imgur.com/P2FkpfQ.jpg

2) 12.0.24 Rcx Register use same offset for Public Key in Resource

https://i.imgur.com/yurNLHr.jpg

**12.0.25**

1) 12.0.25 offset public Key in Resource

https://i.imgur.com/QksPmN3.jpg

2) 12.0.25 Rcx Register use dump/debug offset for Public Key not resource offset

https://i.imgur.com/y8pO9Hd.jpg

Regards

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Yes, I've found that. It seems that Navicat now do not load public key from resource. I found that it load string from `libcc.dll` and then decrypt string to public key. 

The encrypted public key string is located at `libcc.dll` and seems to be splitted to three part:
1. `92933` 
@ __base_addr + 0x1A12D8C__
2. `E1CED09B9C2186BF71A70C0FE2F1E0AEF3BD6B75277AAB20DFAF3D110F75912BFB63AC50EC4C48689D1502715243A79F39FF2DE2BF15CE438FF885745ED54573850E8A9F40EE2FF505EB7476F95ADB783B28CA374FAC4632892AB82FB3BF4715FCFE6E82D03731FC3762B6AAC3DF1C3BC646FE9CD3C62663A97EE72DB932A301312B4A7633100C8CC357262C39A2B3A64B224F5276D5EDBDF0804DC3AC4B835162BB1969EAEBADC43D2511D6E023928781B167A48273B953378D3D2080CC06777E8A2364F0234B81064C5C739A8DA28DC5889072BF37685CBC94C2D31D0179AD86D8E3AA8090D4F0B281BE37E0143746E6049CCC06899401264FA471C016A96C79815B55BBC26B43052609D9D175FBCDE455392F10E51EC162F51CF732E6BB391F56BBFD8D957DF3D4C55B71CEFD54B19C16D458757373E698D7E693A8FC39815A8BF03BA05EA8C8778D38F9873D62B4460F41ACF997C30E7C3AF025FA171B5F5AD4D6B15E95C27F6B35AD61875E5505449B4E`
 @ __base_addr + 0x1A12DA0__
3. `D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C58ACF944E082801409A02472FAFFD1CD77864BB821AE36766FEEDE6A24F12662954168BFA314BD95032B9D82445355ED7BC0B880887D650F5`
@ __base_addr + 0x1A13090__

But the complete encrypted string is:
`D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C58ACF944E082801409A02472FAFFD1CD77864BB821AE36766FEEDE6A24F12662954168BFA314BD95032B9D82445355ED7BC0B880887D650F5`__`29158142`__`E1CED09B9C2186BF71A70C0FE2F1E0AEF3BD6B75277AAB20DFAF3D110F75912BFB63AC50EC4C48689D1502715243A79F39FF2DE2BF15CE438FF885745ED54573850E8A9F40EE2FF505EB7476F95ADB783B28CA374FAC4632892AB82FB3BF4715FCFE6E82D03731FC3762B6AAC3DF1C3BC646FE9CD3C62663A97EE72DB932A301312B4A7633100C8CC357262C39A2B3A64B224F5276D5EDBDF0804DC3AC4B835162BB1969EAEBADC43D2511D6E023928781B167A48273B953378D3D2080CC06777E8A2364F0234B81064C5C739A8DA28DC5889072BF37685CBC94C2D31D0179AD86D8E3AA8090D4F0B281BE37E0143746E6049CCC06899401264FA471C016A96C79815B55BBC26B43052609D9D175FBCDE455392F10E51EC162F51CF732E6BB391F56BBFD8D957DF3D4C55B71CEFD54B19C16D458757373E698D7E693A8FC39815A8BF03BA05EA8C8778D38F9873D62B4460F41ACF997C30E7C3AF025FA171B5F5AD4D6B15E95C27F6B35AD61875E5505449B4E`__`6767392933`__

You can see the bold part, __`29158142`__ and __`6767392933`__, is missing. So far I do not know how that missing part is generated.

By the way, you can decrypt that encrypted string by my another repo:
https://github.com/DoubleLabyrinth/how-does-navicat-encrypt-password

The key is __`b'23970790'`__

example:
```cmd
E:\GitHub>git clone https://github.com/DoubleLabyrinth/how-does-navicat-encrypt-password.git
...
E:\GitHub>cd how-does-navicat-encrypt-password\python3
E:\GitHub\how-does-navicat-encrypt-password\python3>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from NavicatCrypto import *
>>> cipher = Navicat11Crypto(b'23970790')
>>> print(cipher.DecryptString('D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C58ACF944E082801409A02472FAFFD1CD77864BB821AE36766FEEDE6A24F12662954168BFA314BD95032B9D82445355ED7BC0B880887D650F529158142E1CED09B9C2186BF71A70C0FE2F1E0AEF3BD6B75277AAB20DFAF3D110F75912BFB63AC50EC4C48689D1502715243A79F39FF2DE2BF15CE438FF885745ED54573850E8A9F40EE2FF505EB7476F95ADB783B28CA374FAC4632892AB82FB3BF4715FCFE6E82D03731FC3762B6AAC3DF1C3BC646FE9CD3C62663A97EE72DB932A301312B4A7633100C8CC357262C39A2B3A64B224F5276D5EDBDF0804DC3AC4B835162BB1969EAEBADC43D2511D6E023928781B167A48273B953378D3D2080CC06777E8A2364F0234B81064C5C739A8DA28DC5889072BF37685CBC94C2D31D0179AD86D8E3AA8090D4F0B281BE37E0143746E6049CCC06899401264FA471C016A96C79815B55BBC26B43052609D9D175FBCDE455392F10E51EC162F51CF732E6BB391F56BBFD8D957DF3D4C55B71CEFD54B19C16D458757373E698D7E693A8FC39815A8BF03BA05EA8C8778D38F9873D62B4460F41ACF997C30E7C3AF025FA171B5F5AD4D6B15E95C27F6B35AD61875E5505449B4E6767392933'))
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1dqF3SkCaAAmMzs889I
qdW9M2dIdh3jG9yPcmLnmJiGpBF4E9VHSMGe8oPAy2kJDmdNt4BcEygvssEfginv
a5t5jm352UAoDosUJkTXGQhpAWMF4fBmBpO3EedG62rOsqMBgmSdAyxCSPBRJIOF
R0QgZFbRnU0frj34fiVmgYiLuZSAmIbs8ZxiHPdp1oD4tUpvsFci4QJtYNjNnGU2
WPH6rvChGl1IRKrxMtqLielsvajUjyrgOC6NmymYMvZNER3htFEtL1eQbCyTfDmt
YyQ1Wt4Ot12lxf0wVIR5mcGN7XCXJRHOFHSf1gzXWabRSvmt1nrl7sW6cjxljuuQ
awIDAQAB
-----END PUBLIC KEY-----

```

**Comment by Deltafox79** [comment]
Yes I have found same hex string here :

https://i.imgur.com/PkCbsVH.jpg

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Yes. But what you found is located at heap. 
We must find the corresponding data that is located at static segment, so that we can replace the public key

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Aha! I've found it. It seems that the missing parts are written as immediate values, and use string format function to convert them to string:

![capture](https://user-images.githubusercontent.com/16631994/38013989-ab1822fa-3299-11e8-975f-b7e8dc9ffb62.PNG)

**Comment by Deltafox79** [comment]
Goodmorning...  Yesterday I went to sleep .. I will also update my Patch Gui ... Good job v12.0.26 is online..

**Comment by Deltafox79** [comment]
@DoubleLabyrinth 

how to Encrypt newline Char in your tool? 

Example :
`print(cipher.EncryptString('-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1dqF3SkCaAAmMzs889I\nqdW9M2dIdh3jG9yPcmLnmJiGpBF4E9VHSMGe8oPAy2kJDmdNt4BcEygvssEfginv\na5t5jm352UAoDosUJkTXGQhpAWMF4fBmBpO3EedG62rOsqMBgmSdAyxCSPBRJIOF\nR0QgZFbRnU0frj34fiVmgYiLuZSAmIbs8ZxiHPdp1oD4tUpvsFci4QJtYNjNnGU2\nWPH6rvChGl1IRKrxMtqLielsvajUjyrgOC6NmymYMvZNER3htFEtL1eQbCyTfDmt\nYyQ1Wt4Ot12lxf0wVIR5mcGN7XCXJRHOFHSf1gzXWabRSvmt1nrl7sW6cjxljuuQ\nawIDAQAB\n-----END PUBLIC KEY-----'))`

give a wrong result :

> D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C5471B19D234DCA35499304C5F83477F0ED83BCF15B58C4AF62EF335A8F27664CA951B2B03AAA4B7812E1664DB921C2FAF9AD359B6398D21338C58BBA0173E077F1B0E82F6B4D4791DF58257C7DD45DA1A490DEE66D0F943B906F6490DBFD55264F437DD78B4703F7A72F7559127CD09F66EFF13CCF68E1126C2665FF6EC82A53A49E18D270ABBEA27BAC36759EEA4D6B8DF8FD19C73D48B87B484C359B07644CE68F67D2718F34E898FFC3963BEB3119F64D54832FB1151E6C171CA9BA20E933C4D04DDDFB082CA10112A73F416EEE5EE89CAC083AB41A079363F76420528949DE34C9A7A9B698DB0389DA64A8CC1F547AC9B442DF69141FEF7066FE4D557E73719C51317B2747B2D96E9D93F1AA963C0501B905C57DBB303E50E8BB635AA53E37C1EB8521232AC1D278F05F9C9BB57A36B63F59D0F96829C595135071B460CF0D2126E50B3A4332B8973C60B7802757F14FCF38B53F50F3106C65682D45FA47566D8DA8209847C296987FB6AF9C6747F01B7D3833E70282F96BAA2AFC765350248DF385005DBDFE8BD7AF11161AEC0F52F65320850F045CF6B050E9BC69E89F7C44BE82F8754D97587

Regards

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Well, use `\r\n`
example: `'xxxxxxx\r\nxxxxx\r\nxxxxx'`

**Comment by Deltafox79** [comment]
@DoubleLabyrinth 

After Patching libcc.dll 

I have this error on Startup navicat 👍 
https://i.imgur.com/G26EeMr.jpg

Probably there is another check on this library... the pE Header Checksum is irrelevant

Regards

**Comment by Deltafox79** [comment]
My String Crypted is : 

D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C58ACF944E082801409A02472FAFFD1CD77864BB821AE36766FEEDE6A24F12662954168BFA314BD95032B9D82445355ED7AB66D367D1B770D4 **B46909DD** C3F07110323C2705E3DB8C6884BFC0BAE355C9EE7427E7D8206596EAF6FE2E59EFD5590FC1128470F2114BBBBB0A34A3C954FC5FD23719BA868B00B5A069CAD3CB434C8BB1EC387E9ECCB2F630F345529EB98E9086555601799A5C0D57C516F54D21DBFE95D2ADF625D633388925B9C200EA395A8E14396018E0D4A8AD7A190084288834261B5A5CDC2A075AE602303DA0EBB5757C0E4F43E8BF8E21C8C72142096973B013FF3C6CCB31F029B328B92146F0CA7A5FB2165F92BE3504082797EC1EA51731FA3A6BFB3D701B2E787BD751649F46016A27B0AA831627D8F6D4B1B1EDBA3B058ADA25232921CF3C4347DBAE2E682A9F8AB1F2FB14C67ADCC7BEE546682E85DD56CF9980E71AF75ABCE4FA5E39F9854F6E0E8ED39E61A991D17D09063830B42D0A612030316BFA8DA64E36A13F17E9EA5C01DFC20F1183E7D4D35315473D49210F439DB6E5359F5474C2CE4E4A9089E07FA8D635E956C89485B0010866C276410D42DEB847D7B9443E48209532F198 **21E39** EEA8D

I have already Hex value B46909DD  21E39

**Comment by Deltafox79** [comment]
All Work on 12.0.26 Keygen v3.3 Coming Soon..

https://i.imgur.com/BpSjTRn.jpg

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Good job. 
By the way, does your Navicat's `Check for Update` function work fine? 
I patched my `libcc.dll` at version 12.0.25, and now cannot check for update to 12.0.26.

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Sorry my bad. Maybe it is my network problem because using original libcc.dll cannot check for update either.

**Comment by Deltafox79** [comment]
@DoubleLabyrinth

Ok. Yes work fine for me... Regards

**Comment by UnaHe** [comment]
很不错！坐等mac 版本

**Comment by Deltafox79** [comment]
New v3.4 Gui Patch/Keygen Avaiable

Fix a bug on x32 Version.. Link Above..

**Comment by xz00311** [comment]
我正在在写比较难看的UI界面，但是到key那里受到本身语言的限制，必须批处理要一条命令完成，如果你的借口能改能这样那就该多好

**Comment by DoubleLabyrinth** [comment]
@xz00311 
额，你是用什么语言写的？

**Comment by xz00311** [comment]
我是用AU3的，或者加我QQ聊吧5327546

**Comment by DoubleLabyrinth** [comment]
@xz00311 
你的意思是说，你的AU3没有办法和console程序交互是吗？或者说没法往里一个程序的stdin里写入？

**Comment by dragonflylee** [comment]
@xz00311 GUI Version done https://github.com/DoubleLabyrinth/navicat-keygen/issues/73
