### ISSUE TITLE
navicat 12.1.20激活失败

### ISSUE THREAD

**Issue by caifenglin** [DoubleLabyrinth/navicat-keygen#300]
navicat 12.1.20激活失败

**Comment by DoubleLabyrinth** [comment]
具体表现是什么呢？

**Comment by caifenglin** [comment]
就是生成的验证码显示叉号，我跟着步骤代理无效的ip生产那一串激活码，输入依然无法激活发自我的华为手机From my Huawei phone-------- 原始邮件 --------主题：Re: [DoubleLabyrinth/navicat-keygen] navicat 12.1.20激活失败 (#300)发件人：Double Sine 收件人：DoubleLabyrinth/navicat-keygen 抄送：caifenglin ,Author 具体表现是什么呢？

**Comment by DoubleLabyrinth** [comment]
如果是显示叉号，那么应该是你在keygen里没选对navicat的版本或者语言。
具体什么情况得看你的console输出才行。

**Comment by caifenglin** [comment]
发自我的华为手机好的，谢谢啊，我有空再试试，仔细记录下-------- 原始邮件 --------主题：Re: [DoubleLabyrinth/navicat-keygen] navicat 12.1.20激活失败 (#300)发件人：Double Sine 收件人：DoubleLabyrinth/navicat-keygen 抄送：caifenglin ,Author 如果是显示叉号，那么应该是你在keygen里没选对navicat的版本或者语言。

具体什么情况得看你的console输出才行。

**Comment by liubo909652** [comment]
我也遇到了这个问题，请问你后面解决了么？

**Comment by JoeyGaojingxing** [comment]
![image](https://user-images.githubusercontent.com/15071824/61862389-645a2180-af00-11e9-9fe2-ac36b2d5db99.png)
![image](https://user-images.githubusercontent.com/15071824/61862402-6d4af300-af00-11e9-8779-7c27aa7f7621.png)
12.1.20 激活失败 +1

**Comment by JoeyGaojingxing** [comment]
英文版激活成功

**Comment by king-wyx** [comment]
![image](https://user-images.githubusercontent.com/20113166/61884738-55d72e80-af2f-11e9-858a-97b750ee910c.png)

**Comment by king-wyx** [comment]
我的也激活失败

**Comment by king-wyx** [comment]
https://www.jianshu.com/p/5f693b4c9468  我用这个注册机成功激活了
