### ISSUE TITLE
premium 12.1.23 success

### ISSUE THREAD

**Issue by wangdongxun** [DoubleLabyrinth/navicat-keygen#301]
1.最新版本没有rpk文件，请跳过旧版教程
2.如果失败，可以试试重新按照

**Comment by weinianta** [comment]
是mac版的吗？

**Comment by hanrongliao** [comment]
我的mac失败了

**Comment by weinianta** [comment]
我全部删除卸载之后，重新安装激活。目前12.1.23已经激活

**Comment by zxcvbnm3057** [comment]
I used it on 12.1.22 just now and I am surprised it worked.
