### ISSUE TITLE
[FAILURE][Linux] Navicat中文版 点击激活报错

### ISSUE THREAD

**Issue by FORYJJ** [DoubleLabyrinth/navicat-keygen#302]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：______

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [ ] macOS
   - [x] Linux

中文版没有办法激活 ，点击激活 报错
![image](https://user-images.githubusercontent.com/42793947/61618731-07f8c700-aca0-11e9-8347-a6a91533b41f.png)

**Comment by FORYJJ** [comment]
解决了  ，断网就可以了；英文版不需要断网

**Comment by DoubleLabyrinth** [comment]
仔细看readme，你应该先断网。
