### ISSUE TITLE
Mac 10.14.6 下12.1.24激活失败

### ISSUE THREAD

**Issue by yihuali** [DoubleLabyrinth/navicat-keygen#306]
前面的步骤都好，就是在bin下执行 ./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium 按下Enter后，出现：

```
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************
Press Enter to continue or Ctrl + C to abort.
[-] ./navicat-patcher/main.cpp:134 -> 
    open failed.
    Not a directory
```

**Comment by DoubleLabyrinth** [comment]
仔细看readme，用法已经变了。
你应该用
```console
$ ./navicat-patcher /Applications/Navicat\ Premium.app/
```

**Comment by yihuali** [comment]
^_^ 谢谢！

**Comment by BIGBbox** [comment]
Macintosh:bin Xu_XIONG$ openssl ral -in RegPrivateKey.pem -pubout -out rpk
openssl:Error: 'ral' is an invalid command.

然后下面就这样了
Macintosh:bin Xu_XIONG$ /Applications/Navicat Premium.app/Contents/Resources/rpk
-bash: /Applications/Navicat: No such file or directory
请问下是哪里操作出问题了啊？
