### ISSUE TITLE
[FAILURE][MacOS] BIO_new_file failed.

### ISSUE THREAD

**Issue by Green-zh** [DoubleLabyrinth/navicat-keygen#308]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: ______

2. What's your Navicat version number?
   Please write here: 12.1

3. What is your Navicat language version? Check one of the following:
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: ______

4. What is your OS? Check one of the following:
   - [ ] Windows
   - [x] macOS
   - [ ] Linux

5. Can you post console output here? If don't have, leave it empty.
```
./navicat-keygen ./RegPrivateKey.pem
***************************************************
*       Navicat Keygen by @DoubleLabyrinth        *
*                  Version: 4.0                   *
***************************************************

[-] ./navicat-keygen/../common/RSACipher.hpp:160 ->
    BIO_new_file failed.
```

6. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

7. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by DoubleLabyrinth** [comment]
出现这个问题可能是
1. `RegPrivateKey.pem`的路径错误。
2. 压根就没有`RegPrivateKey.pem`这个文件。
3. 你没有`RegPrivateKey.pem`的访问权限。
请逐一排查再试。

**Comment by DoubleLabyrinth** [comment]
Please check
1. The path to `RegPrivateKey.pem` is correct.
2. `RegPrivateKey.pem` exists.
3. You have right to access `RegPrivateKey.pem`.

**Comment by Green-zh** [comment]
已完成激活，非常感谢！

Activation completed. Thank you very much!

「Double Sine <notifications@github.com>」在 2019年8月8日 週四，下午1:52 寫道：
