### ISSUE TITLE
能不能出一个navicat  for mysql 12.0.26 版本？

### ISSUE THREAD

**Issue by YuHangZM** [DoubleLabyrinth/navicat-keygen#31]

**Comment by Deltafox79** [comment]
New Patch/Keygen Gui v3.3 Online...

https://i.imgur.com/8rz4X4A.jpg

https://mega.nz/#!w8oTAQLb!B3RuQuWvaeQH38LZxpMsLfLoOYdoFtE4f10z1h6NXto

Regards

**Comment by ExerciseBook** [comment]
为啥要出一个专门版。。。这个pro版本不好吗。。

**Comment by YuHangZM** [comment]
@Deltafox79  thanks a lot ,sir !

**Comment by Deltafox79** [comment]
new v3.4 Online.. Link Above.. 

Fix for x32 Version

**Comment by izauddin** [comment]
Is there any other link for the keygen 3.4 gui ?, the above in mega is not there any more..

**Comment by Deltafox79** [comment]
Link fixed
