### ISSUE TITLE
[FAILURE][ubuntu 19.04] libpng12.so.0 err

### ISSUE THREAD

**Issue by 0x2d3c** [DoubleLabyrinth/navicat-keygen#311]
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder

**Comment by DoubleLabyrinth** [comment]
@zenuo

**Comment by zenuo** [comment]
此报错可以忽略。

在 周日, 8月 11, 2019 在 4:44 下午, Double Sine <notifications@github.com> 来信：

**Comment by zenuo** [comment]
@0x2d3c 
若不能正常激活，再贴一下错误日志。看起来是wine的错误日志，可以忽略。

**Comment by 0x2d3c** [comment]
> @0x2d3c
> 若不能正常激活，再贴一下错误日志。看起来是wine的错误日志，可以忽略。

我手动安装了libpng12, 已经激活最新版本的Navicat Premium
