### ISSUE TITLE
[FAILURE][macOS] main.cpp open failed

### ISSUE THREAD

**Issue by seyvoue** [DoubleLabyrinth/navicat-keygen#312]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [ ] Navicat Premium
   - [ ] Navicat MySQL
   - [x] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：2.1.21

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [x] English
   - [ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [x] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
./navicat-patcher /Applications/Navicat\ Data\ Modeler.app
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

[-] ./navicat-patcher/main.cpp:134 ->
    open failed.
    No such file or directory
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
mac分支只支持Navicat Premium，不支持Navicat Data Modeler。

**Comment by seyvoue** [comment]
好吧。那有什么办法 可以搞定 mac 端的 Navicat Data Modeler。 @DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
我也没有办法，我已经很久不弄Navicat Data Modeler了。不过 @dragonflylee 可能知道某些东西。

**Comment by realchoi** [comment]
@DoubleLabyrinth 我是 Navicat Premium 最新版本，也报这个错误唉。
