### ISSUE TITLE
[FAILURE][MacOs] codesign error

### ISSUE THREAD

**Issue by nathan-zhu** [DoubleLabyrinth/navicat-keygen#314]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：12.1.20

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [ ] Simplified Chinese
   - [x] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [x] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
codesign -f -s'nathan' /Applications/Navicat\ Premium.app                                                                       
error: The specified item could not be found in the keychain.
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
你确定在你的keychan里有`nathan`这个证书？

**Comment by nathan-zhu** [comment]
再按看证书名字？

**Comment by DoubleLabyrinth** [comment]
keychain里啊，就是“钥匙链”这个内置应用

**Comment by nathan-zhu** [comment]
是再kechain里找navicat这个认证的证书吗，没有这个名字的

**Comment by DoubleLabyrinth** [comment]
这个证书是你自己创建的自签名代码签名证书，你要手动信任这份自签名代码签名证书，然后用这个证书给打过补丁的navicat签名。关于如何创建自签名的代码签名证书，这个请你google吧

**Comment by nathan-zhu** [comment]
好的，收到，多谢。
