### ISSUE TITLE
[windows10家庭中文版] 激活navicate 12.21失败

### ISSUE THREAD

**Issue by lengjun666** [DoubleLabyrinth/navicat-keygen#315]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ √] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：_____

2. 你的Navicat版本号是多少？
   请写在这里：___12.21___

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [ √] Simplified Chinese
   - [x] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [√ ] Windows
   - [ ] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
贴在这里
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   运行正常，在获取到激活码后，打开navicat 时，程序闪退

**Comment by DoubleLabyrinth** [comment]
如果你是navicat mysql 12.1.21的版本，很抱歉，我已经找不到这个版本了。我只能弄到最新的12.1.22版本，但是激活完全没有任何问题。建议彻底删除navicat mysql然后再试。
