### ISSUE TITLE
[FAILURE][windows10]激活失败 第一步补丁就执行失败

### ISSUE THREAD

**Issue by binghuanlanhu** [DoubleLabyrinth/navicat-keygen#317]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: ______

2. What's your Navicat version number?
   Please write here: ______

3. What is your Navicat language version? Check one of the following:
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: ______

4. What is your OS? Check one of the following:
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

5. Can you post console output here? If don't have, leave it empty.
```
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*           Release date: Jan 19 2019             *
***************************************************

Press Enter to continue or Ctrl + C to abort.

MESSAGE: PatchSolution0 will be omitted.

ERROR: @ PatchSolution.hpp - Line 197
```

6. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

7. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by DoubleLabyrinth** [comment]
x86的keygen对应x86版本的navicat，x64版本的keygen对应x64位的navicat。不要弄混了。
