### ISSUE TITLE
macOS 10.15 make all 报错

### ISSUE THREAD

**Issue by wuearl** [DoubleLabyrinth/navicat-keygen#318]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [ *] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：___12.1___

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [ *] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [ ] Windows
   - [ *] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
 make all             
g++ -std=c++17 -O2 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -lcapstone -lkeystone -lplist++ ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/X64ImageInterpreter.cpp ./navicat-patcher/HelperIsResolvedTo.cpp ./navicat-patcher/HelperPrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
./navicat-patcher/main.cpp:4:10: fatal error: 'plist/plist++.h' file not found
#include <plist/plist++.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [patcher] Error 1
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
贴在这里
```

7. 如果你有其他信息要提供的，请写在这里：
   （如果你没有，请留空。）

**Comment by DoubleLabyrinth** [comment]
你有好好读readme吗？你需要用homebrew装个libplist库
