### ISSUE TITLE
Mac 最后一步出错

### ISSUE THREAD

**Issue by zwscool** [DoubleLabyrinth/navicat-keygen#319]
./navicat-patcher/main.cpp:4:10: fatal error: 'plist/plist++.h' file not found
#include <plist/plist++.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [patcher] Error 1

**Comment by DoubleLabyrinth** [comment]
请仔细读readme，你需要用homebrew安装libplist库
