### ISSUE TITLE
SHA256 do not match.

### ISSUE THREAD

**Issue by alisaAsa** [DoubleLabyrinth/navicat-keygen#32]
D:\Program Files (x86)\PremiumSoft\Navicat Premium 12\navicat-keygen>navicat-patcher.exe "D:\Program Files (x86)\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem
ERROR: SHA256 do not match.
Failed!

**Comment by DoubleLabyrinth** [comment]
So far, this keygen is for navicat premium simplified chinese only. Other version is on todo list

**Comment by alisaAsa** [comment]
Give me your version of url

**Comment by DoubleLabyrinth** [comment]
If you are urgent to activate, you can download a better keygen developed by @Deltafox79, at issue #30.
direct link: https://mega.nz/#!4k5BCRaL!l-8juQc99yHn1lS3KmrK9dGZJn6-VJpibhAzcYIJ2ZQ

**Comment by alisaAsa** [comment]
Give me your version

**Comment by alisaAsa** [comment]
I need CN

**Comment by DoubleLabyrinth** [comment]
Just download from Navicat's official website and then use `check for update` to update to 12.0.26.
https://navicat.com.cn/download/navicat-premium

My version is also from update. So far the official does not publish 12.0.26 download link.

**Comment by alisaAsa** [comment]
So I need to update it

**Comment by alisaAsa** [comment]
alright，I am trying again

**Comment by DoubleLabyrinth** [comment]
Oh, I forgot something. Please make sure you use Navicat Premium __x64__ version

**Comment by alisaAsa** [comment]
![image](https://user-images.githubusercontent.com/16953053/38123597-9cb429ae-340e-11e8-8f07-39669f561248.png)
Help!!!

**Comment by DoubleLabyrinth** [comment]
Change your system time to one day between 2018/03/15 to 2018/03/27

**Comment by DoubleLabyrinth** [comment]
And I want to ask one question. What version is your Navicat?
I successfully activated both Navicat Premium x64 CN 12.0.25 and 12.0.26 with my keygen. And my keygen should be compatible for versions below 12.0.25. I think you shouldn't have that error.

**Comment by alisaAsa** [comment]
![image](https://user-images.githubusercontent.com/16953053/38123887-70a60ab0-3410-11e8-9db8-ff95dd18fee6.png)
thank you！！！！
