### ISSUE TITLE
[FAILURE][Win10] Navicat corrupted

### ISSUE THREAD

**Issue by Mestarry** [DoubleLabyrinth/navicat-keygen#320]
在运行 `navicat-patcher.exe` (Windows, Wine in Linux) 或者 `navicat-patcher` (macOS)之前，你应该确保你的Navicat是官方版本，即未被任何第三方修改，同时也应确保你的Navicat安装目录下没有 `*.backup` 文件。

如果激活依然失败了，你可以提交一份失败报告。请填写下面的内容：

1. 你的Navicat产品类型是什么? 选择下面一个：
   - [x] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] 其他，请写在这里：______

2. 你的Navicat版本号是多少？
   请写在这里：12.1.22

3. 你的Navicat产品语言版本是什么？选择下面一个：
   - [ ] English
   - [x] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] 其他，请写在这里：______

4. 你的操作系统是什么？选择下面一个：
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

5. 你可以把命令行输出贴出来吗？如果你没有，请留空：
```
```

6. 如果 __请求码__ 或者 __激活码__ 出现了，请把 `RegPrivateKey.pem` 的内容贴在这里：
```
```

7. 如果你有其他信息要提供的，请写在这里：

```
navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12"
```
执行第一句之后告诉我没有权限，然后就没有继续执行了，之后从示例中找了Serial number:
NAVO-2ORP-IN5A-GQEE再注册输入过，然后再打开软件就出现异常，卸载之后也不能恢复。
![微信截图_20190825212733](https://user-images.githubusercontent.com/50688428/63650630-2e1df500-c77f-11e9-9324-5e53e96049de.png)
![微信截图_20190825212811](https://user-images.githubusercontent.com/50688428/63650640-4c83f080-c77f-11e9-9751-10a9ffb0167c.png)

**Comment by Mestarry** [comment]
打开软件后会

**Comment by DoubleLabyrinth** [comment]
建议删除`HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\`下所有`Registration`打头的键看下。

**Comment by DoubleLabyrinth** [comment]
另外请善用Github的Preview功能，发消息之前用Preview检查格式。

**Comment by Mestarry** [comment]
解决了，谢谢
