### ISSUE TITLE
[FAILURE][window10] Exception EComponentError in module navicat.exe at 0000000000137D3A.is not a valid component name.

### ISSUE THREAD

**Issue by Mestarry** [DoubleLabyrinth/navicat-keygen#321]
BEFORE `navicat-patcher.exe` (Windows, Wine in Linux) or `navicat-patcher` (macOS) is run, you should make sure that your Navicat is official version, which means it has not been modified by anyone, and you should also make sure there's no `*.backup` files in Navicat installation folder.

If you still meet a failure, you can submit a failure report and please fill in the following:

1. What is your Navicat product? Check one of the following:
   - [ ] Navicat Premium
   - [ ] Navicat MySQL
   - [ ] Navicat Data Modeler
   - [ ] Navicat Report Viewer
   - [ ] Other, please write here: ______

2. What's your Navicat version number?
   Please write here: ______

3. What is your Navicat language version? Check one of the following:
   - [ ] English
   - [ ] Simplified Chinese
   - [ ] Traditional Chinese
   - [ ] Other, please write here: ______

4. What is your OS? Check one of the following:
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

5. Can you post console output here? If don't have, leave it empty.
```
Please post here
```

6. If __Request Code__ or __Activation Code__ is shown, please post the content of `RegPrivateKey.pem` here:
```
Please post here
```

7. If you have other information to provide, please write here.
   (If you don't have, leave it empty.)

**Comment by DoubleLabyrinth** [comment]
Close for duplicate in #320
