### ISSUE TITLE
Mac版本 激活失败

### ISSUE THREAD

**Issue by ygzhong000** [DoubleLabyrinth/navicat-keygen#324]
1、最后一步获取激活码失败？？！！
我装的是navicat 12.1.24，系统版本是macOS 10.14.6
错误信息：./navicat-keygen/../common/RSACipher.hpp:244 ->
    RSA_private_decrypt failed.
    pkcs decoding error

**Comment by DoubleLabyrinth** [comment]
你是不是运行了`openssl genrsa -out RegPrivateKey.pem 2048`这一句？运行了就删掉navicat，全部重来，并且不要再运行这一句了，因为这一句只是给navicat premium 12.0.24以前的版本用的。

**Comment by ygzhong000** [comment]
是的，的确执行了openssl genrsa -out RegPrivateKey.pem 2048
和 openssl rsa -in RegPrivateKey.pem -pubout -out rpk，版本大于12.1.24就不用执行这两条命令了，已激活成功！！！Thanks！！！

**Comment by DoubleLabyrinth** [comment]
是12.0.24，不是12.1.24，麻烦看清楚一点。12.0.24是很早以前的版本，大约一年前吧。

**Comment by ygzhong000** [comment]
对对！！眼拙
