### ISSUE TITLE
@xiaolong520lei

### ISSUE THREAD

**Issue by xiaolong520lei** [DoubleLabyrinth/navicat-keygen#328]
@xiaolong520lei 
只能说私钥不对。具体是什么原因，麻烦开issue并把console的上下文贴出来。

_Originally posted by @DoubleLabyrinth in https://github.com/DoubleLabyrinth/navicat-keygen/issues/223#issuecomment-529751503_

**Comment by xiaolong520lei** [comment]
hi  @DoubleLabyrinth 
我就是按照https://blog.csdn.net/wangyaodong915/article/details/82958372
这个地址中的流程走的，我的本地装的navicat是中文版的最新版本，
![image](https://user-images.githubusercontent.com/29653188/64582847-6fd6ae80-d3c1-11e9-9565-30697f1a7758.png)
我操作的时候也是断网打开的navicat，然后就提示Failed to decrypt data.

**Comment by DoubleLabyrinth** [comment]
patcher的输出呢？

**Comment by DoubleLabyrinth** [comment]
这个教程是很早版本的吧？请删掉navicat，对着mac分支的readme重新操作。

**Comment by xiaolong520lei** [comment]
好的，我试试吧！thank you!

**Comment by xiaolong520lei** [comment]
@DoubleLabyrinth 谢谢大佬，重新下载安装navicat， 按钮您的步骤完美破解！非常感谢！

**Comment by xiaolong520lei** [comment]
不好意思，又出问题啦
![image](https://user-images.githubusercontent.com/29653188/64586975-7e789200-d3d0-11e9-9f30-c2549cb1a08c.png)
![image](https://user-images.githubusercontent.com/29653188/64586989-85070980-d3d0-11e9-94f4-6cb7358cecf2.png)
下一步该怎么操作

**Comment by DoubleLabyrinth** [comment]
不对啊，你这个keygen用的是我mac分支的代码吗？我的代码生成的序列号不可能是NFR版本的。

**Comment by xiaolong520lei** [comment]
我就是git 下来的啊
 git clone -b windows --single-branch https://github.com/DoubleLabyrinth/navicat-keygen.git
不对吗？

**Comment by DoubleLabyrinth** [comment]
那这个你这个序列号能贴出来吗？就是那个`NAVF-ZCE3-FDCB-****`，把后面盖住的部分贴出来。

**Comment by xiaolong520lei** [comment]
NAVA-FB6A-T76E-VRDL

**Comment by DoubleLabyrinth** [comment]
首先你那张截图里的序列号肯定不是我的keygen生成的。我推测图片里的序列号是`NAVF-ZCE3-FDCB-46BX`，那是我很早以前留的一个序列号。这个序列号解码后最后一字节是0xfe，而我代码里的值是0x32，所以肯定不是我的代码生成的。

`NAVA-FB6A-T76E-VRDL`应该是可以用的，换这个就好。不过你得在注册窗口先取消激活。

**Comment by xiaolong520lei** [comment]
最上面的截图是之前用错的了，我后来用的就是这个NAVA-FB6A-T76E-VRDL来操作激活的，别看最上面的图，最上面的图是我之前弄的，这个东西没有改本地文件的地方来修改这个时间的吗？

**Comment by xiaolong520lei** [comment]
又重新走了一下，这次真的好了，哈哈，谢谢啦
