### ISSUE TITLE
Patcher v4.0 - BIO_new_file failed

### ISSUE THREAD

**Issue by Deltafox79** [DoubleLabyrinth/navicat-keygen#329]
Hi mr DoubleLabyrinth

I have Compiled and Test Today latest Patcher v**4.0** on Navicat v**12.1.22** EN

**Whit** Admin Privilege give this Error : 

> ...
> 9MFnK+wyuueljQFuUnK6sS+nN29eG4J3a14V6+gNPwkpfKGan9m2ady4BTAmB+R2
> bQIDAQAB
> -----END PUBLIC KEY-----
> 
> [-] .\common\RSACipher.hpp:134 ->
>     [-] BIO_new_file failed.
> PS C:\> 

Regards

**Comment by DoubleLabyrinth** [comment]
Hi.
Could you post full console context? Especially your command line.

**Comment by Deltafox79** [comment]
> 
> 
> Hi.
> Could you post full console context? Especially your command line.

Here the txt whit all console Text..

[Test_4.0.txt](https://github.com/DoubleLabyrinth/navicat-keygen/files/3598736/Test_4.0.txt)


Regards

**Comment by DoubleLabyrinth** [comment]
I cannot reproduce your failure. In my computer, it works fine with administrator privilege.
```
C:\> .\navicat-patcher.exe 'C:\Program Files\PremiumSoft\Navicat Premium 12'
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************
...
...
...
[*] +023e66d8: 77 49 44 41 ---> 51 49 44 41
[*] +0165f91c: 51 41 ---> 51 41
[*] +0165f921: 42 ---> 42

[*] New RSA-2048 private key has been saved to
C:\\RegPrivateKey.pem

*******************************************************
*           PATCH HAS BEEN DONE SUCCESSFULLY!         *
*                  HAVE FUN AND ENJOY~                *
*******************************************************
C:\>
```

I don't think this is a problem of my patcher. Maybe in your computer, `C:\` is protected and even administrator cannot create a file in `C:\` directory. 

Maybe you can run patcher and attach a debugger before pressing `Enter`. Then set up a breakpoint on `CreateFile` and continue. If `CreateFile` return `FALSE` you can read `NtCurrentTeb()->LastErrorValue` and figure it out why.

**Comment by Deltafox79** [comment]
The problem was Windows PowerShell even if launched with admin permissions. Regards
