### ISSUE TITLE
关于OpenSSL问题我提供个参考

### ISSUE THREAD

**Issue by sunwe** [DoubleLabyrinth/navicat-keygen#33]
刚在52pojie看了你的说明。我也是win7，原来是clone 源码下来，自编译的，OpenSSL使用的是Win64OpenSSL-1_1_0g，单独装的。这次源码直接编译不成功，提示libcrypto64MTd.lib没找到。我尝试在OpenSSL lib下找，确实没有，在lib/VC下有个libcryptoMTd.lib，我提到lib下，改成了libcrypto64MTd.lib。然后编译成功。但是在patcher时提示libcc.dll已存在backup（可以确定的是，我每次先删除这个backup然后再执行patcher的）。以上信息算是参考，因为没有52pojie账号，只能在这回复了。
非常感谢大神提供的免费工具。

**Comment by DoubleLabyrinth** [comment]
你换那个lib是可以的，这个没有问题。

如果提示已存在backup，只可能是确实存在文件。因为备份文件的代码是在`/navicat-patcher/common.cpp`里。

```cpp
BOOL BackupFile(LPCTSTR file_path) {
        size_t file_path_len = _tcslen(file_path);

        TCHAR* backup_file_path = new TCHAR[file_path_len + 16]();
        _stprintf_s(backup_file_path, file_path_len + 16, TEXT("%s%s"), file_path, TEXT(".backup"));

        if (!CopyFile(file_path, backup_file_path, TRUE)) {
            switch (GetLastError()) {
                case ERROR_FILE_NOT_FOUND:
                    _tprintf_s(TEXT("@[BackupFile]: Cannot find %s.\r\n"), file_path);
                    break;
                case ERROR_FILE_EXISTS:
                    _tprintf_s(TEXT("@[BackupFile]: Backup file already exists.\r\n"));
                    break;
                case ERROR_ACCESS_DENIED:
                    _tprintf_s(TEXT("@[BackupFile]: Access denied, please run as administrator.\r\n"));
                    break;
                default:
                    _tprintf_s(TEXT("Unknown error. CODE: 0x%08x @[BackupFile -> CopyFile]\r\n"), GetLastError());
            }
            delete[] backup_file_path;
            return FALSE;
        }

        _tprintf_s(TEXT("@[BackupFile]: %s has been backed up.\r\n"), file_path);
        delete[] backup_file_path;
        return TRUE;
    }
```

这里有一个`ERROR_FILE_EXISTS`项，已存在只可能是这个原因。要实在不行你看看能不能在这个函数的入口下断点，看下传入的参数到底是啥

**Comment by sunwe** [comment]
我重新clone了项目，重新安装了navicat进行编译，另外复制了你发布包里的RegPrivateKey.pem。
以下是全过程。
<img src="http://liaoyuansoft.com.img.800cdn.com/error/error1.png">编译的几个警告，我觉得这里问题不大。报错信息：
@[BackupFile]: D:\Program Files\PremiumSoft\Navicat Premium 12\libcc.dll has been backed up.
----------Start to do patch 0----------
At offset +0x01a12090, write:
"D75125B70767B94145B47C1CB3C0755E7CCB8825C5DCE0C58ACF944E082801409A02472FAFFD1CD77864BB821AE36766FEEDE6A24F12662954168BFA314BD95032B9D82445355ED7784ADAC1C58775D2"

<img src="http://liaoyuansoft.com.img.800cdn.com/error/error2.png">执行patcher 写入时的错误。

<img src="http://liaoyuansoft.com.img.800cdn.com/error/error3.png">打开navicat时报错。

**Comment by DoubleLabyrinth** [comment]
抱歉，问题找到了。是我使用WriteFile这个API不当。v1.5已经修正

**Comment by sunwe** [comment]
漂亮！
