### ISSUE TITLE
刚刚测试出现的小问题

### ISSUE THREAD

**Issue by bequt** [DoubleLabyrinth/navicat-keygen#34]
![无标题1.png](https://i.loli.net/2018/03/31/5abeee6c58ed3.png)
![无标题.png](https://i.loli.net/2018/03/31/5abeee6d29299.png)
不知道是啥情况。

**Comment by DoubleLabyrinth** [comment]
抱歉，问题找到了。是我使用WriteFile这个API不当。v1.5已经修正

**Comment by bequt** [comment]
@DoubleLabyrinth  非常感谢。thanks
