### ISSUE TITLE
navcat12.1.22,第6步未得到code,提示如下信息

### ISSUE THREAD

**Issue by wodegyk** [DoubleLabyrinth/navicat-keygen#340]
[-] .\common\RSACipher.hpp:239 ->
    RSA_private_decrypt failed.
    Hints: Are your sure you DO provide a correct private key?

**Comment by DoubleLabyrinth** [comment]
只能说私钥不对，具体情况请提供console上下文

**Comment by wodegyk** [comment]
我把命令前加的./去掉就可以了。。。


------------------ 原始邮件 ------------------
发件人: "Double Sine"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 中午11:21
收件人: "DoubleLabyrinth/navicat-keygen"<navicat-keygen@noreply.github.com>;
抄送: "王华林"<453148576@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DoubleLabyrinth/navicat-keygen] navcat12.1.22,第6步未得到code,提示如下信息 (#340)




只能说私钥不对，具体情况请提供console上下文
