### ISSUE TITLE
Add text to "Generating new RSA private key, it may take a long time..."

### ISSUE THREAD

**Issue by NightWarGames** [DoubleLabyrinth/navicat-keygen#342]
It is always a little unnerving using a keygen / patcher and not knowing if you are giving yourself a virus. I think one thing that could make it less so would be adding a little text / progress info to the step: "Generating new RSA private key, it may take a long time..." to let people know what is actually happening.

On my PC, it has been going for almost an hour with a 3.5GHz and 64GB RAM and running on average around 12% processor usage. Since that is long enough to encrypt a hard drive, I started looking at what was actually happening during that time in the code and feel that info such as:
Comparing generated private keys to Navicat
Attempting 2839/minute
3830029387 keys attempted
Still looking for match

Or is there a way to accelerate it? When using some programs they have you wiggle the mouse to generate some randomness to incorporate into the generation process. What about using GPU if available to multithread?

I have used it before, but it just seems to be taking longer this time and so I thought I would suggest this as a way of making it more friendly.

**Comment by DoubleLabyrinth** [comment]
I seems that you are quite unlucky today :-) 

Generally, RSA private key searching would be done in half a minute and no more than 3 minutes if you use 32-bits Navicat, which is the result of tests on my Surface Book 2 machine. 

Of course, maybe there is something changed. Can you tell me what Navicat version you use?
