### ISSUE TITLE
macos 12.1.27好像没有离线激活这个选项了

### ISSUE THREAD

**Issue by vinurs** [DoubleLabyrinth/navicat-keygen#345]

**Comment by vinurs** [comment]
![image](https://user-images.githubusercontent.com/37489300/66879777-5d6c1800-eff2-11e9-81ff-09791a024234.png)

**Comment by JK-Xia** [comment]
遇到同意的问题，应该标准出来，已不能 被激活

**Comment by vinurs** [comment]
😂难道以后只能用破解版的了

**Comment by DoubleLabyrinth** [comment]
你确定在使用navicat-keygen的时候选择了正确的语言版本吗？从你的截图来看你用的是英文版的navicat，你是不是在keygen里选成中文的了？

**Comment by vinurs** [comment]
这个确实，我好像选择到是简体中文，不过之前到版本我也是这样激活到没有啥问题啊，我试试选英文到

**Comment by vinurs** [comment]
@DoubleLabyrinth 我换成了英文的可以了，我是直接通过brew安装的，谢了
