### ISSUE TITLE
输入Base64 Request Code以后提示 Failed to decrypt data.而没有输出激活码是怎么回事？

### ISSUE THREAD

**Issue by whatisjava** [DoubleLabyrinth/navicat-keygen#346]
mac cataline系统，navicat版本号12.1.27 -Premium

**Comment by DoubleLabyrinth** [comment]
你运行了patcher吗？patcher的console输出可否贴出来？

**Comment by DoubleLabyrinth** [comment]
你这个用的是旧版的代码吧，麻烦重装navicat、然后到mac分支下载新版代码，然后对照readme再试。

**Comment by whatisjava** [comment]
这次输入request code以后报这个错
[-] ./navicat-keygen/../common/RSACipher.hpp:244 ->
    RSA_private_decrypt failed.
    pkcs decoding error

**Comment by whatisjava** [comment]
噢，可以了，参考另一个issue里说的，装完了navicat先别打开，等需要填激活码的时候再打开就可以了
