### ISSUE TITLE
win10 计划备份无效，但是 win7  可以？？？？？

### ISSUE THREAD

**Issue by YuHangZM** [DoubleLabyrinth/navicat-keygen#35]
看到你知道怎么破解，应该也了解我的这个问题吧？

**Comment by DoubleLabyrinth** [comment]
请麻烦说下哪一步出了问题

**Comment by YuHangZM** [comment]
哪里都没有问题，操作正确，但是在win 10  中是不生效的。随便找了一个操作链接
https://blog.csdn.net/qq_34646449/article/details/73957851
能否亲自试一下。？？？？？

**Comment by DoubleLabyrinth** [comment]
我还以为你是打错了字说激活备份无效。。。

关于这个问题，我也不是很清楚，我不用这个功能。我能给的建议是去控制面板的计划任务里检查下是否有对应的条目和是否触发过，以及在任务属性里查看下触发条件，还有触发时命令参数是否设置对了。

ps:请不要发和本项目无关的issue，不然别人看到了会感觉很奇怪的ヽ(￣ω￣(￣ω￣〃)ゝ
如果非要谈请邮件联系xiao_ai_yu@live.cn

**Comment by YuHangZM** [comment]
抱歉，本不想发的。碰运气白。

**Comment by YuHangZM** [comment]
已解决！
