### ISSUE TITLE
navicat激活失败!原因：已达激活次数上限

### ISSUE THREAD

**Issue by hd1993** [DoubleLabyrinth/navicat-keygen#350]
![2019-10-30 (1)](https://user-images.githubusercontent.com/13757102/67833321-4f081b00-fb1f-11e9-9091-8b5ffdfa82f1.png)

**Comment by DoubleLabyrinth** [comment]
你断网了吗？

**Comment by hd1993** [comment]
没有，还真是断网之后就可以获取到请求码了，已经成功激活，谢谢！
