### ISSUE TITLE
最后一步生成激活码失败，麻烦看下

### ISSUE THREAD

**Issue by quanwei4382** [DoubleLabyrinth/navicat-keygen#353]
![image](https://user-images.githubusercontent.com/18027328/68069548-41ab9480-fd9c-11e9-9f5e-02bf8c770586.png)
![image](https://user-images.githubusercontent.com/18027328/68069555-5daf3600-fd9c-11e9-9df7-9d03668161a9.png)
我的navicat premium版本是12.1.27

**Comment by DoubleLabyrinth** [comment]
你用的是旧版的keygen代码，请到mac分支使用新版的代码再试。

**Comment by quanwei4382** [comment]
操作成功，感谢大佬
