### ISSUE TITLE
mac系统使用 navicat-keygen来生成 序列号 和 激活码出错

### ISSUE THREAD

**Issue by cynthia1101** [DoubleLabyrinth/navicat-keygen#354]
mac系统10.14.5 执行到 navicat-keygen来生成 序列号 和 激活码
![image](https://user-images.githubusercontent.com/5037700/68079472-20db5180-fe25-11e9-8ff5-87e6c9a5ee85.png)
请问这是什么错误啊？怎么解决？

**Comment by DoubleLabyrinth** [comment]
你确定`./RegPrivateKey`存在吗？
