### ISSUE TITLE
[-] ./navicat-patcher/main.cpp:134 ->      open failed.     Not a directory

### ISSUE THREAD

**Issue by wwhai** [DoubleLabyrinth/navicat-keygen#356]
![image](https://user-images.githubusercontent.com/20577297/68124867-4c585c00-ff4b-11e9-9bca-6006459bf69f.png)

**Comment by quinls** [comment]
我的是，10.15.1 也是这样

**Comment by DoubleLabyrinth** [comment]
麻烦仔细看readme，你需要指定一个路径，而不是一个文件。

**Comment by wqh0109663** [comment]
./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

**Comment by wqh0109663** [comment]
同样也是这个错误

**Comment by wqh0109663** [comment]
mac10.15.1   Premium 12.1.27

**Comment by saviourdog** [comment]
same
