### ISSUE TITLE
make all 编译错误，提示fatal error: 'type_traits' file not found

### ISSUE THREAD

**Issue by ZeroneLuo** [DoubleLabyrinth/navicat-keygen#358]
系统环境：macOS Mojava 10.14.3版本

make all编译报错，错误如下：

g++ -std=c++17 -O2 \
-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib \
  \
  \
  \
-lcrypto -lcapstone -lkeystone -lplist++ ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/X64ImageInterpreter.cpp ./navicat-patcher/HelperIsResolvedTo.cpp ./navicat-patcher/HelperPrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/CapstoneDisassembler.cpp:1:
In file included from ./navicat-patcher/CapstoneDisassembler.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/KeystoneAssembler.cpp:1:
In file included from ./navicat-patcher/KeystoneAssembler.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/X64ImageInterpreter.cpp:1:
./navicat-patcher/X64ImageInterpreter.hpp:5:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/HelperIsResolvedTo.cpp:3:
In file included from ./navicat-patcher/CapstoneDisassembler.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
1 warning generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/PatchSolution0.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/PatchSolution1.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/PatchSolution2.cpp:1:
In file included from ./navicat-patcher/PatchSolutions.hpp:3:
./navicat-patcher/../common/ResourceOwned.hpp:2:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ./navicat-patcher/main.cpp:4:
In file included from /usr/local/include/plist/plist++.h:26:
In file included from /usr/local/include/plist/Array.h:25:
In file included from /usr/local/include/plist/Structure.h:25:
/usr/local/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [patcher] Error 1

网上没有找到解决办法

**Comment by DoubleLabyrinth** [comment]
`g++ -v`的结果贴出来

**Comment by ZeroneLuo** [comment]
Configured with: --prefix=/Applications/Xcode 4.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode 4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode 4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by DoubleLabyrinth** [comment]
你这个xcode版本太老了吧。
这样吧，你修改下Makefile，在所有`-std=c++17`后面加上参数`-std=libc++`，如果还不行，建议升级xcode。

**Comment by ZeroneLuo** [comment]
xcode的版本是10.1 也老么？升级到最新版本？

**Comment by DoubleLabyrinth** [comment]
你的xcode不是xcode 4吗？如果不是的话，那我也没办法了，或者换GNU GCC试试？

**Comment by ZeroneLuo** [comment]
> 你的xcode不是xcode 4吗？如果不是的话，那我也没办法了，或者换GNU GCC试试？

![image](https://user-images.githubusercontent.com/16714846/68443743-d89aa580-020f-11ea-844e-791ad4d15593.png)

难受，香菇

**Comment by ZeroneLuo** [comment]
不按照xcode，是不是就不能使用这个

**Comment by DoubleLabyrinth** [comment]
也不是非要xcode，一般情况下macos的c++编译器gcc就是xcode自带的apple-clang。但是从你的结果来看，似乎你的apple-clang没有c++11标准库的type_traits，这就很奇怪了，我怀疑你的xcode是一路升级上去的，有一些东西没有更新或安装。所以如果你实在不想换xcode，那么就用homebrew安装gnu版本的gcc、然后编译看看。

**Comment by ZeroneLuo** [comment]
我搞定了，我卸载了Xcode，安装了xcode-select，然后重新指定了路径。就OK了
