### ISSUE TITLE
运行patcher替换掉公钥报错

### ISSUE THREAD

**Issue by 200841113** [DoubleLabyrinth/navicat-keygen#365]
1 git clone -b mac --single-branch https://github.com/DoubleLabyrinth/navicat-keygen.git
2 cd navicat-keygen
3 make all
4 cd navicat-patcher
5 ./navicat-patcher /Applications/Navicat\ Premium.app/
提示-bash: ./navicat-patcher: No such file or directory
6 make release
make: *** No rule to make target release'. Stop. 
7 git checkout mac 
Already on 'mac' Your branch is up to date with 'origin/mac'. 
8 make release make: *** No rule to make target release'. Stop.
请问这是什么原因 我克隆的是mac分支啊，编译make release不存在

**Comment by DoubleLabyrinth** [comment]
好好看readme，不要对照别人的教程，别人给你的东西是过时的

**Comment by 200841113** [comment]
> 好好看readme，不要对照别人的教程，别人给你的东西是过时的

看mac分支下，readme 执行 ./navicat-patcher /Applications/Navicat\ Premium.app/ 
报错-bash: ./navicat-patcher: No such file or directory

执行步骤
1 git clone -b mac --single-branch https://github.com/DoubleLabyrinth/navicat-keygen.git
2 cd navicat-keygen
3 make all
4 ./navicat-patcher /Applications/Navicat\ Premium.app/ 报错

**Comment by DoubleLabyrinth** [comment]
那你确定有`/Applications/Navicat\ Premium.app/`这个文件夹吗？还是说你的navicat premium是安装在别的地方？亦或是你用的根本就不是navicat premium而是navicat mysql之类的？

**Comment by 200841113** [comment]
/Applications/NavicatPremium 我有这个文件夹啊 安装的navicat premium 不是navicat mysql for mac

发自我的iPhone

> 在 2019年11月15日，19:00，Double Sine <notifications@github.com> 写道：
> 
> /Applications/Navicat\ Premium

**Comment by DoubleLabyrinth** [comment]
`/Applications/NavicatPremium` 和 `/Applications/Navicat\ Premium.app/` 并不一样。
请把路径换成你电脑上navicat premium的路径。

**Comment by 200841113** [comment]
> `/Applications/NavicatPremium` 和 `/Applications/Navicat\ Premium.app/` 并不一样。
> 请把路径换成你电脑上navicat premium的路径。

使用 ./navicat-patcher /Applications/Navicat Premium.app
提示 -bash: ./navicat-patcher: is a directory

**Comment by DoubleLabyrinth** [comment]
我觉得你可能需要学习如何使用命令行。

从你的提示来看，你的当前目录不在bin文件夹，所以运行navicat-patcher两个办法：
```console
$ ./bin/navicat-patcher /Applications/Navicat\ Premium.app
```
要么
```console
$ cd bin
$ ./navicat-patcher /Applications/Navicat\ Premium.app
```

另外`Navicat Premium.app`中间有空格，你必须在空格前加反斜杠来转义空格，否则路径会被拆成两个参数。

**Comment by 200841113** [comment]
> 我觉得你可能需要学习如何使用命令行。
> 
> 从你的提示来看，你的当前目录不在bin文件夹，所以运行navicat-patcher两个办法：
> 
> ```
> $ ./bin/navicat-patcher /Applications/Navicat\ Premium.app
> ```
> 
> 要么
> 
> ```
> $ cd bin
> $ ./navicat-patcher /Applications/Navicat\ Premium.app
> ```
> 
> 另外`Navicat Premium.app`中间有空格，你必须在空格前加反斜杠来转义空格，否则路径会被拆成两个参数。

谢谢，没有加入PATH环境变量，我去试试

**Comment by 200841113** [comment]
> > 我觉得你可能需要学习如何使用命令行。
> > 从你的提示来看，你的当前目录不在bin文件夹，所以运行navicat-patcher两个办法：
> > ```
> > $ ./bin/navicat-patcher /Applications/Navicat\ Premium.app
> > ```
> > 
> > 
> > 要么
> > ```
> > $ cd bin
> > $ ./navicat-patcher /Applications/Navicat\ Premium.app
> > ```
> > 
> > 
> > 另外`Navicat Premium.app`中间有空格，你必须在空格前加反斜杠来转义空格，否则路径会被拆成两个参数。
> 
> 谢谢，没有加入PATH环境变量，我去试试

谢谢 已经激活成功了。我认为readme还是没有写的详细，尤其是对我这种刚使用mac的人来说，很多地方都不清楚。windows 激活简单直接替换一个文件即可
