### ISSUE TITLE
生成一份自签名的代码证书，并总是信任该证书。出现错误

### ISSUE THREAD

**Issue by Waterman1997** [DoubleLabyrinth/navicat-keygen#370]
~/D/n/bin> codesign -f -s "foofdgbar" /Applications/Navicat\ Premium.app/
error: The specified item could not be found in the keychain.

**Comment by Waterman1997** [comment]
> ~/D/n/bin> codesign -f -s "foofdgbar" /Applications/Navicat\ Premium.app/
> error: The specified item could not be found in the keychain.

证书已经好了，现在的错误是
[-] ./navicat-keygen/../common/RSACipher.hpp:251 ->
    RSA_private_decrypt failed.
    pkcs decoding error

**Comment by DoubleLabyrinth** [comment]
patcher的console输出请贴出来

**Comment by Z-hb** [comment]
我朋友刚刚给我发了激活码，结果没有用到我下载的东西

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Double Sine <notifications@github.com>
发送时间: Saturday, November 23, 2019 10:55:58 AM
收件人: DoubleLabyrinth/navicat-keygen <navicat-keygen@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [DoubleLabyrinth/navicat-keygen] 生成一份自签名的代码证书，并总是信任该证书。出现错误 (#370)


patcher的console输出请贴出来

―

**Comment by Waterman1997** [comment]
> patcher的console输出请贴出来

卸载，重新来一遍成功了，🙏感谢
