### ISSUE TITLE
mac os 下，navicat-keygen除了支持navicat premium,还支持其他系列 最新版 navicat mysql、mongodb、sqllite、postgresql、oracle、mariadb吗？

### ISSUE THREAD

**Issue by zhanggc** [DoubleLabyrinth/navicat-keygen#372]
mac os 下，navicat-keygen除了支持navicat premium,还支持其他系列 最新版 navicat mysql、mongodb、sqllite、postgresql、oracle、mariadb吗？

**Comment by DoubleLabyrinth** [comment]
仅支持navicat premium

**Comment by zhanggc** [comment]
@DoubleLabyrinth windows下，navicat-keygen除了支持navicat premium,还支持其他系列 最新版 navicat mysql、mongodb、sqllite、postgresql、oracle、mariadb吗？

**Comment by DoubleLabyrinth** [comment]
@zhanggc
windows下是全版本支持的
