### ISSUE TITLE
生成的序列号错了

### ISSUE THREAD

**Issue by sevenNightL** [DoubleLabyrinth/navicat-keygen#375]
![1574686809403](https://user-images.githubusercontent.com/27542146/69542571-aab2b080-0fc6-11ea-81b9-802664f8f0ee.jpg)

**Comment by DoubleLabyrinth** [comment]
你的navicat是中文版，不要在keygen里选English。

**Comment by DoubleLabyrinth** [comment]
只有中文版才有这个激活界面

**Comment by sevenNightL** [comment]
> 你的navicat是中文版，不要在keygen里选English。

谢谢，下班回家试试。

**Comment by sevenNightL** [comment]
> 只有中文版才有这个激活界面

![image](https://user-images.githubusercontent.com/27542146/69629107-fdec3800-1086-11ea-9f36-2202a4603f44.png)
15版本的现在还不可以吗
