### ISSUE TITLE
老哥 mac 版的用哪个

### ISSUE THREAD

**Issue by tangqy666** [DoubleLabyrinth/navicat-keygen#38]
吾爱破解论坛账号忘了 下载不了 看你GitHub资源库里面没有你说的rpk文件

**Comment by DoubleLabyrinth** [comment]
请到参阅本repo的mac分支https://github.com/DoubleLabyrinth/navicat-keygen/tree/mac 的README
我已经在README里写了rpk文件的生成方法，就在最下面的How to use

**Comment by tangqy666** [comment]
12.0.24 中文版, 在/Contents/Resources 中已经没有rpk了
