### ISSUE TITLE
Hints: Are your sure you DO provide a correct private key?

### ISSUE THREAD

**Issue by fengmangseo** [DoubleLabyrinth/navicat-keygen#381]
```*] Select Navicat product:
0. DataModeler
1. Premium
2. MySQL
3. PostgreSQL
4. Oracle
5. SQLServer
6. SQLite
7. MariaDB
8. MongoDB
9. ReportViewer

Input index)> 1

*] Select product language:
0. English
1. Simplified Chinese
2. Traditional Chinese
3. Japanese
4. Polish
5. Spanish
6. French
7. German
8. Korean
9. Russian
10. Portuguese

Input index)> 1

*] Input major version number:
range: 0 ~ 15, default: 12)> 12.1

*] Serial number:
AVI-Z3MX-7B5V-MV5O

*] Your name: d3
*] Your organization: d3
*] Input request code in Base64: (Input empty line to end)
v73ZF9g8lf5f4fGZtMq4pAKQndGVroByvsRZNgC6Qbas8pLaSXiTNMrFVAs+nyeeNkrj2g8kc2g3cDL4oLR7pisUGNj6hbhn8JPJtpmR3Gww85y0pygW0VM
vCeLo39aSSh61I13B9ecZ5FpaD7906+7UyzeiWvYErnHq5BhwyruId51YMabxcmxH+iHTGnmEb5HEp5nD0Hqa3qLalnweXfgIZkZjBpajuCEro8J1M9RZKY
f1hRNr/oHLjuONzyYDLMsKg5vokmcFV66zZ4Uxwto3zw8g52P6yghs/xsfmXVrx9lxqP9C+l2N4MfMGeQd6xNiLaORJR8RJRTDknA==

-] .\common\RSACipher.hpp:239 ->
   RSA_private_decrypt failed.
   Hints: Are your sure you DO provide a correct private key?
S C:\Navicat Premium 12>
```

**Comment by fengmangseo** [comment]
我测试了几十遍 \
`[*] Input request code in Base64: (Input empty line to end)
hH5iXr52hvhd2oYQGIybStZYzAN+XPMFLT3UHXenkf36GCm895kowy412zRPnjD46jqgJhBsC9xlqOos644rvqVVQaNAARPJKIGqvUdaKJf8sDM+nbLNB8ff
nQK1uscvtwgqQbI0IlE6Vw+uUgotahF/mDC/IZuBYlBhMgXs283coOVZ4mPGkeBBPLYIxoeer8YM38zjV5LlhgxQeIaSulIaiB0K6b1D5NX92/WLfdHj07p7
gJrlmUFWLz1qYgPYP3ThQhJLY0gJHs5WOLyyMvAouN71ietgVkb2Cp1SbMFUPOw8bDMstjHsrc/Fxam6NlsghhK83upEI3qE2mU4PQ==

[-] .\common\RSACipher.hpp:239 ->
    RSA_private_decrypt failed.
    Hints: Are your sure you DO provide a correct private key?`

双击回车就失败

**Comment by fengmangseo** [comment]
上一步执行的结果

[*] New RSA-2048 private key has been saved to
C:\\RegPrivateKey.pem

**Comment by DoubleLabyrinth** [comment]
你有没有在打了补丁之后又打补丁？

**Comment by zhu6621** [comment]
[-] .\common\RSACipher.hpp:239 ->
RSA_private_decrypt failed.
Hints: Are your sure you DO provide a correct private key?

**Comment by zhu6621** [comment]
我的也是这样，v4.1版本

**Comment by zhu6621** [comment]
12.1.25 mysql版本

**Comment by fengmangseo** [comment]
我有个破解版 我用了另外一个破解版 可能是我打过其他版本的破解版 我有个10版本的
