### ISSUE TITLE
执行命令行报错

### ISSUE THREAD

**Issue by xinghunzhiye** [DoubleLabyrinth/navicat-keygen#39]
执行：navicat-patcher "C:\Program Files\PremiumSoft\Navicat Premium 12" D:\Re
gPrivateKey.pem
日志：
@[BackupFile]: C:\Program Files\PremiumSoft\Navicat Premium 12\libcc.dll has bee
n backed up.
Failed to set target file of BIO. CODE: 0x02001002 @[ReadRSAPrivateKeyFromFile -
> BIO_read_filename]
Failed!

请看一下什么问题

**Comment by DoubleLabyrinth** [comment]
你确定D:\RegPrivateKey.pem是存在的吗？

**Comment by xinghunzhiye** [comment]
D:\RegPrivateKey.pem不存在。
下面这样执行就可以了。
navicat-patcher "C:\\Program Files\\PremiumSoft\\Navicat Premium 12" 
navicat-keygen RegPrivateKey.pem
