### ISSUE TITLE
mac 15.0.4 homebrew 版本

### ISSUE THREAD

**Issue by baosongZhang** [DoubleLabyrinth/navicat-keygen#393]
./navicat-patcher /Applications/Navicat\ Premium.app/
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

[*] Your Navicat version: 15.0.4

[-] PatchSolution0 ...... Omitted.
[-] PatchSolution1 ...... Omitted.
[-] PatchSolution2 ...... Omitted.
[-] Patch abort. None of PatchSolutions will be applied.
    Are you sure your Navicat has not been patched before?

**Comment by baosongZhang** [comment]
[-] ./navicat-keygen/../common/RSACipher.hpp:251 ->
    RSA_private_decrypt failed.
    pkcs decoding error

**Comment by DoubleLabyrinth** [comment]
mac分支已经更新
