### ISSUE TITLE
版本15 make all 报错

### ISSUE THREAD

**Issue by goodleo** [DoubleLabyrinth/navicat-keygen#395]
![image](https://user-images.githubusercontent.com/7307798/70625057-94f6e980-1c5c-11ea-884a-08e800ff98f4.png)

大神，我的mac版本是10.14.6的，咋出来10.15呢？帮忙看一下

**Comment by DoubleLabyrinth** [comment]
`std::filesystem` 要求macOS 10.15版本以上，见Apple的[release note](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes?preferredLanguage=occ).

你现在只有几个办法：
1. 修改`navicat-patcher/Misc.cpp`里的代码，把std::filesystem相关的部分换掉。
2. 换编译器。
3. 升级系统。

**Comment by cop007** [comment]
<img width="869" alt="pic" src="https://user-images.githubusercontent.com/22148646/70715103-8a078c00-1d24-11ea-81b2-4ead39e3fa15.png">
大神 搭车问一下我这也报错了 请问是不是我哪里姿势不对 感谢！

**Comment by DoubleLabyrinth** [comment]
@cop007 
修改Makefile，把 `OPENSSL_INCLUDE_PATH` 和 `OPENSSL_LIB_PATH` 换成你电脑上openssl的include、lib路径。

**Comment by cop007** [comment]
@DoubleLabyrinth 已经完美解决了 非常感谢！
