### ISSUE TITLE
Support navicat 15

### ISSUE THREAD

**Issue by vanthao03596** [DoubleLabyrinth/navicat-keygen#396]
Please add support navicat 15 for linux

**Comment by DoubleLabyrinth** [comment]
See [linux](https://github.com/DoubleLabyrinth/navicat-keygen/tree/linux) branch.

**Comment by xudqiang93** [comment]
thanks!
it works very nice.

**Comment by vanthao03596** [comment]
> See [linux](https://github.com/DoubleLabyrinth/navicat-keygen/tree/linux) branch.

Thank's you so much. I work like charm.
