### ISSUE TITLE
Navicat 12 x64 English version

### ISSUE THREAD

**Issue by Benjamin-Qin** [DoubleLabyrinth/navicat-keygen#4]
请问在哪里可以找到snKey 中data[5] 与data[6] 中对应英语版本的相应数值，需要通过什么途径?

**Comment by DoubleLabyrinth** [comment]
你需要通过ida反编译到对应的snKey验证函数上，说实话一时半会儿说不清。

如果你是要英文版，data[5]和data[6]可能分别是0xac、0x88，至少在navicat v12.0.19 Mac英文版下是确认通过的。

**Comment by Benjamin-Qin** [comment]
感谢。已验证0xAC，0x88在Navicat v12.0.20 x64 Win 英文版下可用。
