### ISSUE TITLE
12.0.26无法打开libcc.dll

### ISSUE THREAD

**Issue by lidejiang1986** [DoubleLabyrinth/navicat-keygen#40]
12.0.26版本是否无法使用此方法？
第一步就报错
Failed to open libcc.dll. CODE: 0x00000020 @[patcher::Solution1::Do -> CreateFile]

**Comment by DoubleLabyrinth** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

```
ERROR_SHARING_VIOLATION
32 (0x20)
The process cannot access the file because it is being used by another process.
```

请你确保没有程序再使用libcc.dll，很有可能你的navicat还开着

**Comment by lidejiang1986** [comment]
简直是太棒了，确实是，
