### ISSUE TITLE
Is wine necessary to use with linux?

### ISSUE THREAD

**Issue by rightaway** [DoubleLabyrinth/navicat-keygen#41]
For both the keygen program and the navicat installation files themselves.

Can the linux downloadable installation files be used or are the windows ones necessary even on linux?

**Comment by DoubleLabyrinth** [comment]
both are ok, because they use the same `libcc.dll` and `navicat.exe`

**Comment by rightaway** [comment]
Thanks! So for the keygen I need to use wine, but for running the program itself I can use the installation files meant for linux (and not wine)?

Once I've unlocked the program offline, and later I decide to reformat my system and reinstall everything, is there a way to do it without having to unlock the program again? If I back up certain files/directories before the reformat, and restore them after, would it be possible not to have to do the unlocking every time I reformat? Which files/directories would these be?

**Comment by DoubleLabyrinth** [comment]
1. Well, Navicat Premium in linux, at least 12.0.x version, also needs wine to run. You can use the wine that Navicat Premium provided to run keygen. So I do not think I have to write a keygen that do not rely on wine.

2. Of course you can. For version < 12.0.25, backup `navicat.exe`. For version >= 12.0.25, backup `libcc.dll`. But when you restore, you should ensure that those backup-ed files should match the Navicat Premium version you newly installed. And you still have to run keygen (not patcher) again, to activate Navicat.
