### ISSUE TITLE
12.0.24 patch后无法打开已保存的数据库连接

### ISSUE THREAD

**Issue by Anebrithien** [DoubleLabyrinth/navicat-keygen#44]
预设条件

1. 正常patch, keygen操作后
2. 软件版本`navicat 12.0.24`，简体中文版
3. 系统版本`macOS 10.13.4`

操作步骤

1. 打开navicat，添加一条MySQL连接，勾选保存密码，点击测试连接，后点保存
2. 重复“打开连接”、“关闭连接”数次，后⌘+Q退出
3. 再次打开navicat，打开之前添加的连接
4. 编辑连接，但不做任何改动，直接点击测试连接

预期结果

1. 测试连接通过，保存成功
2. 可以正常打开/关闭连接，退出成功
3. 可以打开连接
4. 测试连接通过

实际结果

3. 无法打开连接，也没有其他异状
4. 测试失败，提示`1045 - Access denied for user 'xxx'@'x.x.x.x' (using password: NO)`

处理方法

1. 推测为保存的密码有问题，重新输入密码，点击测试连接，通过。在退出应用前持续有效，退出后则问题复现。或者不勾选保存密码，每次打开连接重新输入密码，则无此问题。
2. 替换回原始的`Navicat Premium` 可执行文件，再打开之前添加的连接，无此问题。

**Comment by DoubleLabyrinth** [comment]
已经复现，问题正在找。

**Comment by DoubleLabyrinth** [comment]
查明了，应该是代码签名的问题。

Navicat会将数据库的密码保存在keychain当中，对于代码签名无效的程序，MacOS的的规则好像是允许程序把密码写入keychain，但不允许程序读取keychain。所以打了patcher之后，Navicat在试图连数据库的时候无法从keychain中读取到数据库密码，但是又不报错，直接将一个空密码传入，所以导致`1045 - Access denied for user 'xxx'@'x.x.x.x' (using password: NO)`

解决办法就是你自己生成一个代码签名证书并设置为always trust，或用自己苹果开发者账号的代码签名证书对navicat进行重签名即可。
```bash
$ codesign -f -s "your code-sign certificate name" /Applications/Navicat\ Premium.app
```

当然如果你用苹果开发者账号的代码签名证书进行签名，这应该严重违反Apple规定，所以你选择这样做记得千万别将签名后的navicat散布到网上，不然一旦被发现肯定证书肯定被Apple吊销。当然即使这样做我也不保证万无一失，总之后果自负。

**Comment by Anebrithien** [comment]
原来如此，多谢了。使用自签名解决了

**Comment by forestlcoder** [comment]
你好，我想问一下codesign命令中自签名的认证内容如何确定？
codesign -f -s "Your self-signed code-sign certificate name" <path to Navicat Premium.app>

**Comment by DoubleLabyrinth** [comment]
@forestlcoder 
引号里的内容是你的代码签名证书的名称。
关于如何创建一个代码签名证书请见
https://support.apple.com/kb/PH7173?locale=zh_CN&viewlocale=zh_CN

**Comment by sharelinux** [comment]
@Anebrithien @DoubleLabyrinth  我生成证书却无法签名。 自签名证书能给一个实例吗？

**Comment by Lindom** [comment]
自签过一次，过几天又不行了

**Comment by MrSuntb** [comment]
你好，我生成了证书，也用证书做了签名，但是还是无法保存密码？ 有没有可能是我签名没有成功？ 怎么判断是否签名成功？
$ codesign -f -s arvin /Applications/Navicat\ Premium.app
/Applications/Navicat Premium.app: replacing existing signature

**Comment by Anebrithien** [comment]
```shell
codesign -d -v /Applications/Navicat\ Premium.app
```
