### ISSUE TITLE
...RegPrivateKey.pem

### ISSUE THREAD

**Issue by ASIjacket** [DoubleLabyrinth/navicat-keygen#47]
请问
 navicat-patcher.exe "D:\Program Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem
使用的RegPrivateKey.pem 是什么
单纯的搜索速度感人

**Comment by DoubleLabyrinth** [comment]
这是一个好问题。
是这样的，如果你看了README，你会知道navicat的公钥是被加密后储存在libcc.dll里的。加密后的结果是一个hex字符串，而且这个字符串被分割成了5部分——3个字符串和2个立即数，程序运行时会用sprintf按照`"%s%d%s%d%s"`的格式将这5部分拼接。

现在我们要替换掉这个加密的公钥，所以我们得不断搜索找到合适的RSA密钥，使得该RSA密钥的公钥加密后的结果能满足上面所说的`"%s%d%s%d%s"`的格式，讲真这东西确实不好找，RegPrivateKey.pem就是我当时搜索出来的满足条件的RSA密钥。记得当时花了5分多钟吧，这还是release模式下的，debug模式下半个小时都搜不到。我想大家都不想搜索吧，所以直接内置了一个满足条件的RSA密钥。
