### ISSUE TITLE
在12.0.27版本上失败

### ISSUE THREAD

**Issue by siluolv2357** [DoubleLabyrinth/navicat-keygen#49]
12.0.27版本执行navicat-patcher.exe “。。。”会提示faild

**Comment by DoubleLabyrinth** [comment]
这么快就出了12.0.27啊。等我有时间看看吧

**Comment by wxlg1117** [comment]
12.0.27简体中文 windows版本可以用Navicat_Keygen_Patch_v3.4_By_DFoX_URET.exe ,但是最新的12.0.25简体中文mac版本不知道怎么搞:
![qq 20180425175718](https://user-images.githubusercontent.com/9752596/39238945-25f875c8-48b2-11e8-9ef4-758a81c2d5d5.jpg)

**Comment by DoubleLabyrinth** [comment]
@wxlg1117 
如果可以用那个注册机激活的话，看样子激活机制没有变化。那个注册机作者我认识，激活机制变了他肯定会和我说。

如果你们不介意的话，你们可以修改`navicat-keygen/navicat-patcher/_tmain.cpp`第53行加一个
```cpp
else if (NavicatMajorVersion == 0x000C0000 && NavicatMinorVersion == 0x001B0000) {        // for navicat ver = 12.0.27
        status = patcher::Solution1::Do(libcc_dll_path.c_str(), argc == 3 ? argv[2] : nullptr);
}
```
然后自己编译看看，我现在没有12.0.27的navicat（不知道为什么navicat一直升级不了，学校网络有问题），自己测试可能要过一段时间。

**Comment by SteelShot** [comment]
I have recompiled both of the executables with the else if added and it seems to work like a charm,

![capture](https://user-images.githubusercontent.com/5291010/39260045-2489358a-48b0-11e8-94d7-b7161b949833.PNG)

**Comment by DoubleLabyrinth** [comment]
@siluolv2357 @wxlg1117 
`windows` branch has been updated. You can download the binary from
https://github.com/DoubleLabyrinth/navicat-keygen/releases/tag/v1.6

Just help yourself.
