### ISSUE TITLE
linux系统下如何编译

### ISSUE THREAD

**Issue by as7212325** [DoubleLabyrinth/navicat-keygen#5]
deepin的linux系统 只有java和qt以及go没有vs 如何转换你这个东东

**Comment by DoubleLabyrinth** [comment]
很抱歉，linux下Navicat的激活机制我还没研究过，我没有办法给出linux下的解决方案

**Comment by as7212325** [comment]
好吧 看来我只能装个wine来模拟环境激活了

**Comment by ihipop** [comment]
是一样的。抛开破解这话题，纯技术讨论下：Linux下的navicat是内置了一个Wine，跑的就是exe的Navicat，尝试直接拿Windows下的试用版扔到Linux版的Navicat里面内置的Wine环境跑，一点问题没有。可能只是公钥不同。

但是从感情上来说，我们应该是只对这里面的实现细节感兴趣，财务自由的情况下，真的想买下所有生产力工具的Ultimate License (开玩笑，财务自由了还上班干嘛-=-)

另外跑题一下， @as7212325  我现在也是全面在Deepin Linux下开发，Wine跑过一段时间的Navicat，现在主要还是日用 dbeaver https://github.com/dbeaver/dbeaver
