### ISSUE TITLE
mac,12.0.24 注册成功,不能保存密码

### ISSUE THREAD

**Issue by liyunde** [DoubleLabyrinth/navicat-keygen#50]
mac 10.12.6
12.0.24 注册成功
不能保存密码, navicat重启以后,
mysql连接出现1045,1045 - Access denied for user 
ORA-01005: null password given; logon denied
需要重新输入密码,以后可以连接
请问有什么办法解决

**Comment by DoubleLabyrinth** [comment]
看来你还是没有仔细看README。
不能保存密码的原因我在issue #44 里说了，你可以看一下

**Comment by liyunde** [comment]
多谢,使用自签证书,解决,当时没有找到这条信息,非常感谢

**Comment by DoubleLabyrinth** [comment]
@sharelinux 
1. 首先请确保你有一个代码签名证书，不管是花钱买的还是自生成的。
   关于如何生成自签名的代码证书：
   1. 首先你要建立一个代码签名的CA，没有CA的话你是发不了证书的。
      <img width="757" alt="screen shot 2018-08-29 at 12 40 39" src="https://user-images.githubusercontent.com/16631994/44765753-cdb6a080-ab88-11e8-9440-fae48f227e5d.png">
   2. 在弹出的窗口里随你填，但User Certificate那一项必须是code signing（中文的话，应该是代码签名）
      <img width="728" alt="screen shot 2018-08-29 at 12 43 47" src="https://user-images.githubusercontent.com/16631994/44765866-59303180-ab89-11e8-8914-a3638d35e873.png">
      之后应该可以一路ok，反正你看着填吧。
   3. 最后的话应该会生成一个代码签名的CA证书，记得把它放到system的keychains里，并设置为always trust，如图
      <img width="710" alt="screen shot 2018-08-29 at 12 47 46" src="https://user-images.githubusercontent.com/16631994/44765987-dfe50e80-ab89-11e8-8d8d-ae22ab610239.png">
      这份证书是我之前就生成的，这里给个样例。  
      之后的话呢，你直接拿这个CA证书签名就行。  
     记得记住你的证书名，在这里是`PhantomCrack Root Certificate Authority`

2. 有了代码签名证书就直接到控制台里用codesign签名：
<img width="976" alt="screen shot 2018-08-29 at 12 55 30" src="https://user-images.githubusercontent.com/16631994/44766176-d90acb80-ab8a-11e8-9c30-05c727284b7d.png">

**Comment by sharelinux** [comment]
@DoubleLabyrinth 非常感谢，现在密码已经可以保存了。谢谢你的图片教程。

**Comment by brooklynb7** [comment]
这步非常重要，激活成功了，感谢

**Comment by StefanChang** [comment]
> @sharelinux
> 
> 1. 首先请确保你有一个代码签名证书，不管是花钱买的还是自生成的。
>    关于如何生成自签名的代码证书：
>    
>    1. 首先你要建立一个代码签名的CA，没有CA的话你是发不了证书的。
>       <img alt="screen shot 2018-08-29 at 12 40 39" width="757" src="https://user-images.githubusercontent.com/16631994/44765753-cdb6a080-ab88-11e8-9440-fae48f227e5d.png">
>    2. 在弹出的窗口里随你填，但User Certificate那一项必须是code signing（中文的话，应该是代码签名）
>       <img alt="screen shot 2018-08-29 at 12 43 47" width="728" src="https://user-images.githubusercontent.com/16631994/44765866-59303180-ab89-11e8-8914-a3638d35e873.png">
>       之后应该可以一路ok，反正你看着填吧。
>    3. 最后的话应该会生成一个代码签名的CA证书，记得把它放到system的keychains里，并设置为always trust，如图
>       <img alt="screen shot 2018-08-29 at 12 47 46" width="710" src="https://user-images.githubusercontent.com/16631994/44765987-dfe50e80-ab89-11e8-8d8d-ae22ab610239.png">
>       这份证书是我之前就生成的，这里给个样例。
>       之后的话呢，你直接拿这个CA证书签名就行。
>       记得记住你的证书名，在这里是`PhantomCrack Root Certificate Authority`
> 2. 有了代码签名证书就直接到控制台里用codesign签名：
> 
> <img alt="screen shot 2018-08-29 at 12 55 30" width="976" src="https://user-images.githubusercontent.com/16631994/44766176-d90acb80-ab8a-11e8-9c30-05c727284b7d.png">

为什么我这里按你的步骤就提示“您输入的用户名或密码短语不正确”啊，我的系统是MacOS Mojava. 求解啊

**Comment by imzeno** [comment]
> > @sharelinux
> > 
> > 1. 首先请确保你有一个代码签名证书，不管是花钱买的还是自生成的。
> >    关于如何生成自签名的代码证书：
> >    
> >    1. 首先你要建立一个代码签名的CA，没有CA的话你是发不了证书的。
> >       <img alt="screen shot 2018-08-29 at 12 40 39" width="757" src="https://user-images.githubusercontent.com/16631994/44765753-cdb6a080-ab88-11e8-9440-fae48f227e5d.png">
> >    2. 在弹出的窗口里随你填，但User Certificate那一项必须是code signing（中文的话，应该是代码签名）
> >       <img alt="screen shot 2018-08-29 at 12 43 47" width="728" src="https://user-images.githubusercontent.com/16631994/44765866-59303180-ab89-11e8-8914-a3638d35e873.png">
> >       之后应该可以一路ok，反正你看着填吧。
> >    3. 最后的话应该会生成一个代码签名的CA证书，记得把它放到system的keychains里，并设置为always trust，如图
> >       <img alt="screen shot 2018-08-29 at 12 47 46" width="710" src="https://user-images.githubusercontent.com/16631994/44765987-dfe50e80-ab89-11e8-8d8d-ae22ab610239.png">
> >       这份证书是我之前就生成的，这里给个样例。
> >       之后的话呢，你直接拿这个CA证书签名就行。
> >       记得记住你的证书名，在这里是`PhantomCrack Root Certificate Authority`
> > 2. 有了代码签名证书就直接到控制台里用codesign签名：
> > 
> > <img alt="screen shot 2018-08-29 at 12 55 30" width="976" src="https://user-images.githubusercontent.com/16631994/44766176-d90acb80-ab8a-11e8-9c30-05c727284b7d.png">
> 
> 为什么我这里按你的步骤就提示“您输入的用户名或密码短语不正确”啊，我的系统是MacOS Mojava. 求解啊

codesign里的证书名是第二张截图里的名字。他这应该是两张截图，不然二三的名称应该是一致的

**Comment by yanqi321** [comment]
> > @sharelinux
> > 
> > 1. 首先请确保你有一个代码签名证书，不管是花钱买的还是自生成的。
> >    关于如何生成自签名的代码证书：
> >    
> >    1. 首先你要建立一个代码签名的CA，没有CA的话你是发不了证书的。
> >       <img alt="screen shot 2018-08-29 at 12 40 39" width="757" src="https://user-images.githubusercontent.com/16631994/44765753-cdb6a080-ab88-11e8-9440-fae48f227e5d.png">
> >    2. 在弹出的窗口里随你填，但User Certificate那一项必须是code signing（中文的话，应该是代码签名）
> >       <img alt="screen shot 2018-08-29 at 12 43 47" width="728" src="https://user-images.githubusercontent.com/16631994/44765866-59303180-ab89-11e8-8914-a3638d35e873.png">
> >       之后应该可以一路ok，反正你看着填吧。
> >    3. 最后的话应该会生成一个代码签名的CA证书，记得把它放到system的keychains里，并设置为always trust，如图
> >       <img alt="screen shot 2018-08-29 at 12 47 46" width="710" src="https://user-images.githubusercontent.com/16631994/44765987-dfe50e80-ab89-11e8-8d8d-ae22ab610239.png">
> >       这份证书是我之前就生成的，这里给个样例。
> >       之后的话呢，你直接拿这个CA证书签名就行。
> >       记得记住你的证书名，在这里是`PhantomCrack Root Certificate Authority`
> > 2. 有了代码签名证书就直接到控制台里用codesign签名：
> > 
> > <img alt="screen shot 2018-08-29 at 12 55 30" width="976" src="https://user-images.githubusercontent.com/16631994/44766176-d90acb80-ab8a-11e8-9c30-05c727284b7d.png">
> 
> 为什么我这里按你的步骤就提示“您输入的用户名或密码短语不正确”啊，我的系统是MacOS Mojava. 求解啊

@StefanChang 你好，我也碰到同样的问题，你解决了吗

**Comment by yeszao** [comment]
签名生成后，竟然不知道去哪里找，搞了半天原来搜索就可以了，看的这：https://www.jianshu.com/p/4a8e66f540c2
