### ISSUE TITLE
Linux下激活

### ISSUE THREAD

**Issue by libsgh** [DoubleLabyrinth/navicat-keygen#52]
版本:navicat 12.0.11
操作系统:Linux mint 18.3(ubuntu 16.04)
navicat的linux 版本就是wine,我在win10 中已经成功激活,复制到linux中还是需要激活
如果需要在linux中重新激活,正确的操作步骤是怎样的

**Comment by as7212325** [comment]
You can refer to my article about activation under the Linux system.
https://www.52pojie.cn/thread-705020-1-1.html

**Comment by libsgh** [comment]
@as7212325 解决了,在linux里面用wine的方式激活一次就好了,和在windows里面一样,你发的帖子不存在了,我关了哈
