### ISSUE TITLE
mac 10.13.4 Navicat Premium 12.0.24 

### ISSUE THREAD

**Issue by Allkoman** [DoubleLabyrinth/navicat-keygen#53]
安装mac 分支的how to use 与 How to build 操作后，始终显示
Failed to decrypt data.

**Comment by DoubleLabyrinth** [comment]
你的patcher返回了success吗？

**Comment by SiweiZhong** [comment]
![image](https://user-images.githubusercontent.com/18499805/39480109-d1accb08-4d99-11e8-86e1-75beb30b7b19.png)
我也遇到了同样的问题

**Comment by UnaHe** [comment]
貌似现在keygen 都没mac版吧

**Comment by DoubleLabyrinth** [comment]
@SiweiZhong 
如果你的Navicat是12.0.25版本的，请不要用，可能Navicat注册算法有改动。
最近忙毕业，6月中旬之前可能都没时间处理了。

@UnaHe 
mac版是有的，你可以见本repo的mac分支

**Comment by SiweiZhong** [comment]
我的是12.0.24

**Comment by huwsun** [comment]
mac下，12.0.25 可以注册成功

**Comment by point7** [comment]
mac下，12.0.26注册成功
