### ISSUE TITLE
第一步失败了

### ISSUE THREAD

**Issue by tianxiagjl** [DoubleLabyrinth/navicat-keygen#58]
[图片]
![tim 20180504174350](https://user-images.githubusercontent.com/16486146/39621846-b9895dea-4fc2-11e8-90be-83851a972b30.png)

**Comment by DoubleLabyrinth** [comment]
把navicat安装目录下的libcc.dll.backup删掉

**Comment by tianxiagjl** [comment]
已经删了 ，确认过眼神


------------------ 原始邮件 ------------------
发件人: "Double Sine"<notifications@github.com>;
发送时间: 2018年5月4日(星期五) 晚上6:13
收件人: "DoubleLabyrinth/navicat-keygen"<navicat-keygen@noreply.github.com>;
抄送: "lscool"<1711646373@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DoubleLabyrinth/navicat-keygen] 第一步失败了 (#58)




把navicat安装目录下的libcc.dll.backup删掉

**Comment by tianxiagjl** [comment]
ok 谢谢老铁
