### ISSUE TITLE
window Navicat Premium12.0.27 提示激活次数上限

### ISSUE THREAD

**Issue by AKA-bingo** [DoubleLabyrinth/navicat-keygen#59]
操作系统： window10 
Navicat Premium版本：12.0.27x64
点击激活时提示：激活失败。原因可能是由于已达到激活次数的上限。请检查你是否已在卸载或重新安装Navicat前取消激活许可证秘钥
![image](https://user-images.githubusercontent.com/7263336/39682981-893fde1e-51e5-11e8-9740-8251735ab256.png)
请问有遇到类似情况以及是否有解决方案么？ 谢谢

**Comment by ExerciseBook** [comment]
卸载软件重做一次

**Comment by DoubleLabyrinth** [comment]
@AKA-bingo 
请断网再试。

**Comment by AKA-bingo** [comment]
@DoubleLabyrinth 
断网之后可以了，谢谢~

**Comment by harrisdt15f** [comment]
![搜狗截图20190829152934](https://user-images.githubusercontent.com/27404296/63919683-d1b62080-ca71-11e9-9113-7ec0058f3033.png)
断网了之后还是不行 在 navicat 版本 12.1.22  window 10

**Comment by hanggegege** [comment]
断网已解决。
