### ISSUE TITLE
Resources rpk

### ISSUE THREAD

**Issue by falconeri** [DoubleLabyrinth/navicat-keygen#6]
Where do i find Resources rpk to replace for Navicat 12.0.19 En for MAC? thanks

**Comment by DoubleLabyrinth** [comment]
Resource "rpk" is at __Navicat Premium.app/Contents/Resources__.

**Comment by falconeri** [comment]
no, i mean where i get that file to replace Navicat Premium.app/Contents/Resources? because in your gitlab only have mac keygen, i cannot found any files to replace resources.

**Comment by DoubleLabyrinth** [comment]
Well, rpk is a RSA public key file starting with "-----BEGIN PUBLIC KEY-----".
It can be any RSA public key. You can generate it by yourself:

```bash
$ openssl genrsa -out 2048key.pem 2048
$ openssl rsa -in 2048key.pem -pubout -out rpk
```

Remember that you must provide the private key file __2048key.pem__ to navicat-keygen, like:

```bash
$ ./navicat-keygen 2048key.pem
```

**Comment by falconeri** [comment]
well i have convert pem to rpk, then copy and replace rpk inside Navicat Premium.app/Contents/Resources, but active button still greyed out 
![image 2018-01-02 at 2 27 44 pm](https://user-images.githubusercontent.com/9047407/34477080-44534da0-efc9-11e7-8bb2-d223d8c4b165.png)

do i still missing step to active the license?

**Comment by DoubleLabyrinth** [comment]
That because the registration key you input is for Navicat 12 x64 Simplified Chinese version.

You can test this key:
__NAVN-AVQ5-HCL2-7CTP__

And of course, you should replace __"NAVFZCE3FDCB46BX"__ at `main.cpp` Line 74 and Line 143 by __"NAVNAVQ5HCL27CTP"__ and then rebuild navicat-keygen:

```bash
$ make navicat-keygen
```

You may wonder why I do not generate registration key dynamically in my code. That because the generation algorithm I decompiled is still not fully correct. The registration key generated dynamically still has some probability that it cannot work.

**Comment by falconeri** [comment]
1. ok now it is success to active, but when i copy rpk to resource folder, and click active, navicat will crash, but if i am using original rpk, click active, then activation offline will showing up.
2. now when i copied request code in keygen, then click enter, it is just waiting 
![image 2018-01-02 at 3 28 28 pm](https://user-images.githubusercontent.com/9047407/34478143-eb66bb1a-efd1-11e7-9ed3-7739243c99e4.png)

note: in image i cropped some request code

**Comment by DoubleLabyrinth** [comment]
Can you tell me where you download your Navicat? I will download and see it.

**Comment by falconeri** [comment]
i download it from navicat trial directly : https://www.navicat.com/download/direct-download?product=navicat_premium_en.dmg&location=1

**Comment by DoubleLabyrinth** [comment]
Well, you say Navicat will crash after you replace "rpk" file.
But I cannot reappear the crash you mentioned.
And I've successfully activated my Navicat.

![1](https://user-images.githubusercontent.com/16631994/34479234-7660f664-efe0-11e7-8750-7232e3e769bf.jpeg)

![2](https://user-images.githubusercontent.com/16631994/34479239-7b3171e6-efe0-11e7-8165-1ca5a5dc00d3.jpeg)

**Comment by falconeri** [comment]
ok problem solve, i knew where i am doing it wrong. thanks for your guidance.
![image 2018-01-02 at 4 46 03 pm](https://user-images.githubusercontent.com/9047407/34480028-960a2c78-efdc-11e7-8fa5-3178568ba06e.png)
