### ISSUE TITLE
大师,12.0.28发布啦

### ISSUE THREAD

**Issue by songchaoyuan** [DoubleLabyrinth/navicat-keygen#60]
12.0.28发布了,感觉官方现在特别厉害,每个版本都更新修改

**Comment by songchaoyuan** [comment]
发现官方也是厉害了,把公钥拆分分别存储在不同的地方,

**Comment by kerojiang** [comment]
手贱点了更新，12.0.28版本破解失效了
please support the 12.0.28

**Comment by DoubleLabyrinth** [comment]
请在`navicat-patcher/_tmaim.cpp`的55行加如下代码再重新编译：
```cpp
else if (NavicatMajorVersion == 0x000C0000 && NavicatMinorVersion == 0x001C0000) {        // for navicat ver = 12.0.28
    status = patcher::Solution1::Do(libcc_dll_path.c_str(), argc == 3 ? argv[2] : nullptr);
}
```

然后删掉navicat安装目录下的libcc.dll再对navicat重新激活

**Comment by songchaoyuan** [comment]
谢谢大师,特别想学这个,感谢感谢

**Comment by kerojiang** [comment]
楼主 其实25后面几个版本里面的方法都是一样的，干嘛还要去每个版本都去判断一下呢？  我直接把后面几个版本判断的删了。
if (NavicatMajorVersion <= 0x000C0000 && NavicatMinorVersion < 0x00190000) {                // for navicat ver < 12.0.25
        status = patcher::Solution0::Do(navicat_exe_path.c_str());
    } else{        // 
        status = patcher::Solution1::Do(libcc_dll_path.c_str(), argc == 3 ? argv[2] : nullptr);
    } 
这样也是可以的

**Comment by DoubleLabyrinth** [comment]
@kerojiang 
我知道啊，但是每次navicat更新我不能保证它的注册算法还和原来一样。我这么做只是保守一点而已。

**Comment by MrXionGe** [comment]
@DoubleLabyrinth 
老哥，希望您有时间的时候，发一个版本吧，多谢啦！
看releasenote，应该是修复了MySQL sha密码类型的问题。

**Comment by songchaoyuan** [comment]
老哥也需要休息,我们应该努力学习技术,争取自给自足,,哈哈

**Comment by shijunti19** [comment]
谁有编译好的，我不想下vs啊

**Comment by MrXionGe** [comment]
@shijunti19 
我也是这个问题。我看了一下是VS的项目。
我没有VS，但是不知道GCC能不能编译，我猜不太能……

**Comment by shijunti19** [comment]
@MrXionGe 论坛有另外一个软件，可以用https://www.52pojie.cn/thread-721977-1-1.html

**Comment by DoubleLabyrinth** [comment]
@songchaoyuan @kerojiang @MrXionGe @shijunti19 
非常抱歉，最近赶毕设没时间。有能力的编译下然后就在这放个release，谢谢了

**Comment by yi-huan** [comment]
装了个 VS2017, 不过不会用， 生成失败。
根据错误提示 把平台工具集 改成了 vs2017 的，
window sdk 版本改成了 10的，
然后现在生成错误是 缺少文件。 不知道怎么搞了。
![image](https://user-images.githubusercontent.com/5660790/39879534-a5c10610-54ad-11e8-88b0-7f69aac8f322.png)

**Comment by songchaoyuan** [comment]
我也是正在安装虚拟机,安装vs2015,庞然大物啊.没想到大师才刚毕业,大师您是怎么知道这东西密钥被分成5快藏在不同地方的呢

**Comment by DoubleLabyrinth** [comment]
@songchaoyuan 
IDA静态分析+x64dbg动态调试，先动态调试用二分法下断点确定加密函数函数在哪，然后静态分析找到密钥载入函数，一般都是在加密函数附近。当然中间要不断动态调试验证猜想

**Comment by tianxiagjl** [comment]
哪位大佬有编译好的给我发一份
1711646373@qq.com

**Comment by songchaoyuan** [comment]
谢谢大佬,感觉汇编是基础

**Comment by DoubleLabyrinth** [comment]
release已更新。Help yourself~

**Comment by songchaoyuan** [comment]
我知道了,是我的openssl版本不对,这个版本,里面没有这个文件,谢谢

**Comment by DoubleLabyrinth** [comment]
@songchaoyuan 
我在`navicat-patcher/def.hpp`里已经写了openssl的来源。

**Comment by songchaoyuan** [comment]
![image 1](https://user-images.githubusercontent.com/18489852/39953628-8b9142b0-55e2-11e8-9465-96158dc7d086.png)
非常给力,谢谢
