### ISSUE TITLE
keygen生成的snKey都不能用，Activate按钮直接是灰的

### ISSUE THREAD

**Issue by ASK-Lee** [DoubleLabyrinth/navicat-keygen#61]
keygen生成的snKey输入后，那个Activate按钮直接灰的不能点击，你们有没有遇到这个情况？重新生成了好几次都是没用的，连网与断网情况下都试过，走不到本地激活那个步骤

**Comment by DoubleLabyrinth** [comment]
请确保你用的是navicat premium，并在keygen里选择了正确的语言

**Comment by ASK-Lee** [comment]
噢，我没注意到这个使用限制条件，我的是for mysql版本。现在官网下载貌似只能下载到最新版，28的好像还不支持，看了其他issue留言，静候大神空了release新版本，祝毕设顺利！
