### ISSUE TITLE
Navicat Premium for Mac最新版无法激活

### ISSUE THREAD

**Issue by wjsoft01** [DoubleLabyrinth/navicat-keygen#64]
Navicat Premium for Mac 12.0.26简体中文版安装之后在Navicat Premium.app/Contents/Resources/下没有rpk公钥文件，怎么进行激活？

**Comment by DoubleLabyrinth** [comment]
mac分支已经写了新的方案，请看mac分支的readme

**Comment by DoubleLabyrinth** [comment]
由于提问者没有回复，本issue暂时关闭
