### ISSUE TITLE
For Windows 无法生成key.pem

### ISSUE THREAD

**Issue by morninglt** [DoubleLabyrinth/navicat-keygen#65]
以前的版本更新后，卸载重新安装12.0.8，生成key的时候提示
@[BackupFile]: Backup file already exists.
Failed!
但是文件目录下没有备份文件

**Comment by DoubleLabyrinth** [comment]
出现这个错误一定是因为备份文件已存在。
因为这个错误的触发逻辑在 `navicat-patcher/common.cpp`的第16、17行，CopyFile函数发生错误，LastError是`ERROR_FILE_EXISTS`

建议你再次检查，确保没有navicat.exe.backup和libcc.dll.backup。如果确实是真的没有，那很抱歉，我也不能知道是什么原因，建议你在vs里亲自debug检查下。

**Comment by JevonsGuo** [comment]
我也遇到了同样的问题。
我刚开始破解的步骤可能错了，我把Pem文件手动copy到了安装目录，再运行了Patcher命令。
后来看了详细步骤，删除了 PEM，和 dll.backup，再次运行，依然报错。

最后我就卸载了原程序，重新安装，重新正确步骤激活。
完美搞定！ @morninglt @DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
由于提问者不再回复，本issue暂时关闭
