### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by sxm20074428** [DoubleLabyrinth/navicat-keygen#66]

**Comment by sxm20074428** [comment]
12.28不可以的

**Comment by JarvisQJ** [comment]
输入key，右侧显示红叉，Active按钮为灰色

**Comment by DoubleLabyrinth** [comment]
@JarvisQJ 你可能没有选择正确的语言或者你的navicat不是premium

**Comment by hepingtao** [comment]
> > navicat-patcher.exe "C:\PremiumSoft\Navicat Premium 12"
> @[BackupFile]: C:\PremiumSoft\Navicat Premium 12\libcc.dll has been backed up.
> Failed to open libcc.dll. CODE: 0x00000020 @[patcher::Solution1::Do -> CreateFile]
> Failed!

@DoubleLabyrinth 不好意思，上面的报错是因为我误操作导致，之前打开了navicat，没有关闭就开始进行激活操作了，导致出现了上面的报错，后面关闭了navicat再尝试就激活成功了，所以在此澄清一下我上面的误报错误，以免给大家造成干扰，也顺便提醒大家注意先关闭navicat再进行激活步骤，多谢了！

**Comment by ajfg93** [comment]
@sxm20074428 
我12.28成功了

**Comment by xinshemeigui** [comment]
第一步 输入路径后 提示
Usage:
navicat_keygen.exe<RSA-2048 PrivateKey<PEN-FILE>>

**Comment by MichaelXucf** [comment]
这个破解工具真心赞，问下大神有没有针对navicat 12 for mysql的破解补丁啊，感觉破解的原理应该跟navicat premium一样的吧？  公司电脑，navicat premium没有权限安装，需要管理员权限才行，只能装navicat 12 for mysql。  @DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
@xinshemeigui 
如果你的路径里有空格请对整个路径加上引号

**Comment by DoubleLabyrinth** [comment]
@MichaelXucf 
你可以看下issue #73，这个人写了注册机的GUI版本，同时也做了对mysql版本的支持。

**Comment by xinshemeigui** [comment]
@DoubleLabyrinth 路径是加过空格的

**Comment by DoubleLabyrinth** [comment]
@xinshemeigui 
之前没注意到你是说第一步出现了问题。
你应该用navicat-patcher不是navicat-keygen
