### ISSUE TITLE
Mac版本安装中，怎么生成自签名代码签名证书？

### ISSUE THREAD

**Issue by liuzhebaba** [DoubleLabyrinth/navicat-keygen#69]

**Comment by DoubleLabyrinth** [comment]
mac系统的keychain有证书助理吧
https://support.apple.com/kb/PH7173?locale=zh_CN&viewlocale=zh_CN

可以用这种方法建立一个自签名**代码证书**，最后别忘了信任该证书。

**Comment by wxwhy** [comment]
自己动手搞个证书，超简单的，很多人就是想要个详细的可以照着操作的教程吧，毕竟很多人估计都不知道教程里面的 keychain 是什么。

**Comment by DoubleLabyrinth** [comment]
由于提问者不再回复，本issue暂时关闭

**Comment by qzi** [comment]
如何生成自签名代码证书呢？
