### ISSUE TITLE
楼主，你好，不知是否我一人如此认为，你的mac版本真的很难用，好好改进改进把。

### ISSUE THREAD

**Issue by liuzhebaba** [DoubleLabyrinth/navicat-keygen#70]

**Comment by DoubleLabyrinth** [comment]
我觉你可能是想要个GUI界面，这样点几下就可以完事。但是很遗憾，我并不会mac下的图形界面编程。如果你觉得难用你可以改进并提交pull request，我会非常欢迎。

**Comment by songchaoyuan** [comment]
发帖者,我想说的是,作者辛辛苦苦免费提供源码,提供一种可以不用钱就能使用的神器,作者没有收过你一分钱,做到这个地步已经非常厉害了,如果你有能力,那你自己去研究一套,或者说你比较有钱的话,直接去购买正版,岂不是最简单的事情!!!同时,如果你有能力,我们也希望你能开发出来一套最简单的出来使用!!!!

**Comment by liuzhebaba** [comment]
我并没有别的意思，只是想告诉作者，让他改进下mac版本的弊端，而不是一套写给自己看的软件，可能语气强硬了些，但是出于好心

**Comment by DoubleLabyrinth** [comment]
@liuzhebaba 
好吧，那你至少告诉我难用在哪吧？不然我也没有方向改

**Comment by cha0ran** [comment]
@dengshenkk 已经是自动化脚本了,人工操作的步骤很少.要怪只能怪很多人英文不好.

**Comment by ExerciseBook** [comment]
已经很方便了吧。。根据软件的提示一步一步做就可以成功了。。。
