### ISSUE TITLE
提示：Failed to set target file of BIO. CODE: 0x02001002 @[ReadRSAPrivateKeyFromFile - > BIO_read_filename] Failed!

### ISSUE THREAD

**Issue by armoour** [DoubleLabyrinth/navicat-keygen#71]
**环境：**系统是win7 64位，Navicat premium 12是64位的，下载的navicat-keygen也是x64的；

**问题：**直接在navicat-Keygen解压文件夹内执行：navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem时，提示：@[BackupFile]: Access denied, please run as administrator，然后换成用管理员命令打开cmd（已添加navicat-keygen.exe的Path），执行上述命令，然后就报title的错误了；

**Comment by armoour** [comment]
回家之后再试了一下，开始也会报错，后面发现360一直在提示病毒，且删除了相关的文件，然后我重新解压并信任文件之后就可以了，明天去公司再试一下；

**Comment by DoubleLabyrinth** [comment]
由于提问者不再回复，本issue暂时关闭
