### ISSUE TITLE
楼主你好，  请问小白怎么破解，，完全看不懂呃

### ISSUE THREAD

**Issue by xieyi** [DoubleLabyrinth/navicat-keygen#72]
好尴尬的一件事，，具体应该怎么操作呃， 谢谢谢谢谢谢谢谢

**Comment by ajfg93** [comment]
@ExerciseBook 
52上面那个跟这个不一样吧？52那个都有GUI的，肯定还是用这个纯净。

**Comment by ajfg93** [comment]
@xieyi 留下你QQ，我教你。

**Comment by yiyouguisu** [comment]
@xieyi 叫我一下破解mac的navicat12.26    QQ：741459065

**Comment by ExerciseBook** [comment]
@ajfg93 所以我叫你认“作者”啊。 认头像和用户名就基本ok。 那里有图文操作教程。
一样是命令行操作。。
