### ISSUE TITLE
重新签名问题解决不了

### ISSUE THREAD

**Issue by lynn349x** [DoubleLabyrinth/navicat-keygen#79]
不会生成签名文件，无法去进行重签名：
codesign -f -s "mysql.server.crt" /Applications/Navicat\ for\ MySQL.app/
error: The specified item could not be found in the keychain.
楼主帮忙解决下

**Comment by DoubleLabyrinth** [comment]
你必须使用在keychain里的**代码签名证书**，mysql.server.crt可不是代码签名证书，充其量只能算ssl证书，更何况它也不在keychain里

**Comment by cha0ran** [comment]
生成自签证书看#69

**Comment by DoubleLabyrinth** [comment]
因为提问者没有回应，本issue暂时关闭

**Comment by miya2017** [comment]
`$ codesign -f -s "Navicat Premium" /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium
/Applications/Navicat Premium.app/Contents/MacOS/Navicat Premium: main executable failed strict validation`
**为什么重新签名错误？如何解决？
1.网上被复制错误的 ‘odesign -f -s '-----deep no strict .......  方法就不要提了，代码都错了，即使正确也是无法解决上面的错误

----ps: 至于如何生成一个自签名的代码签名证书，
请参考：https://blog.csdn.net/Roland_Sun/article/details/50452665

**Comment by nvidhub** [comment]
Premium.app/Contents/MacOS/Navicat Premium: main executable failed strict validation
这个问题主要是在替换公钥的时候出错了，使用（--no-strict --deep ）参数并不能解决问题。推荐使用本工程中readme的做法，使用命令行工具替换公钥。我在使用过程中通过命令行生成的激活码输入后，无法点击active按钮，后来胡打乱撞使用(https://laucyun.com/a8b422bc6a7712a001117708fc2578b3.html)中生成的激活码，成功的激活了，在这里记录一下，希望帮助到同样遇到问题的人
