### ISSUE TITLE
[MacOS] Navicat restart don't keep right hostname and sets no password for MySQL connection

### ISSUE THREAD

**Issue by s1lviu** [DoubleLabyrinth/navicat-keygen#82]
Navicat Premium, version 12.0.26

**Steps to reproduce:**
1. Follow [how to use](https://github.com/DoubleLabyrinth/navicat-keygen/tree/mac) steps
2. Set a new MySQL (in my case) connection and save it (including password)
<img src="https://i.imgur.com/TnFgUX0.png">

3. Quit the software (Cmd+Q)
4. Reopen Navicat Premium
5. Try to open the saved connection and you'll see that nothing happens
6. Right click, edit connection, press "Test Connection"
<img src="https://i.imgur.com/QEoTbhK.png">

**Issues:**
1. From error, you can see that the connection's hostname is incomplete (192.168.10.1 instead of 192.168.10.10)
2. Password isn't retrieved properly or none (checked in keychain and it's saved)

**Almost a workaround**: tick "Edit Password", retype it and save the connection. It will work, but because of this issue, only for current session.

**Comment by DoubleLabyrinth** [comment]
In MacOS, apps without valid code signature are not allowed to read passwords in keychain where Navicat stores connections' username and password. 

`navicat-patcher` modified the binary file of `Navicat Premium.app` so its code signature became invalid. Thus Navicat cannot read passwords from keychain.

So all you need to do is:
1. Delete all connections that is created by Navicat stored in keychain.
2. Resign `Navicat Premium.app` by your own trusted code signature certificate.

**Comment by s1lviu** [comment]
Ok. It worked!
Yesterday, when I read the steps, I skipped this one: 

> Generate a self-signed code-sign certificate and always trust it. Then use codesign to re-sign Navicat Premium.app.

I thought that it's for version < 12.0.24.
If you want, I think would be better to put 3.1 and 3.2 steps to be much clear.

Thank you!
