### ISSUE TITLE
mac pg 12.27

### ISSUE THREAD

**Issue by yiyouguisu** [DoubleLabyrinth/navicat-keygen#84]
![image](https://user-images.githubusercontent.com/11996269/41147322-ad719dce-6b38-11e8-832b-c16f62c7af98.png)
一直是X

**Comment by DoubleLabyrinth** [comment]
你的是navicat prenium吗？

**Comment by yiyouguisu** [comment]
Navicat for PostgreSQL @DoubleLabyrinth

**Comment by icelemon1314** [comment]
@yiyouguisu 用navicat prenium版本，这个是通用版本，支持多种数据库的。

**Comment by DoubleLabyrinth** [comment]
@yiyouguisu 
目前这个注册机只支持navicat premium
