### ISSUE TITLE
mac 版本如何操作再能写清楚一点吗？

### ISSUE THREAD

**Issue by evenson419** [DoubleLabyrinth/navicat-keygen#87]
mac 版本如何操作再能写清楚一点吗

**Comment by xialeistudio** [comment]
要不弄个视频教程？

**Comment by iluyasha** [comment]
mac版本操作流程：
1、前提条件，需要安装openssl。安装说明可参看：https://blog.csdn.net/qyee16/article/details/72799852

2、cd navicat-keygen
      make release
这一步make的时候需要注意MakeFile文件中openssl的路径为：/usr/local/opt/openssl/include。建议更改下这个MakeFile文件中的路径为：/usr/local/openssl/include。因为后续操作中使用到的openssl路径会是这个。这两个地方使用的并不统一。

3、 cd navicat-patcher
     make release 

4、仅针对版本>= 12.0.24
cd navicat-patcher 
./navicat-patcher /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium （参数为你的navicat启动路径）ma
5、./navicat-keygen 2048key.pem
![image](https://user-images.githubusercontent.com/18301621/41710919-6ea6afe4-7579-11e8-836c-06a50a8875f3.png)
会获得序列啊。输出用户名、组织等信息，接下来就会让你输入请求码。

6、启动你的navicate，输入第5步看到的序列号，会提示失败，然后点击：手动激活。就会弹出请求码。将请求码粘贴到第五步中，按两下回车，就会出现激活码，将激活码贴到第6步中，点击激活，就成功了

**Comment by zhxhdreams** [comment]
你好，make文件能提供一下吗

**Comment by DoubleLabyrinth** [comment]
在mac分支里我已经添加中文版的README，请对照上面的进行操作。

**Comment by evenson419** [comment]
![image](https://user-images.githubusercontent.com/35451163/42257462-2cc4c358-7f89-11e8-9bab-b7320f166949.png)

**Comment by DoubleLabyrinth** [comment]
@evenson419 
从你的截图来看，你的当前目录是项目的根目录，如果你要编译，你需要进入navicat-keygen文件夹或navicat-patcher文件夹，那里面才有makefile

**Comment by evenson419** [comment]
@DoubleLabyrinth 
谢谢你的回复，但我在navicat-keygen文件夹里面没有看到 makefile 文件
![image](https://user-images.githubusercontent.com/35451163/42257781-d5c22ff8-7f8a-11e8-887b-ffdb01e1e3fc.png)

**Comment by DoubleLabyrinth** [comment]
@evenson419 
你clone错分支了，应该是mac分支。你这是windows分支

**Comment by evenson419** [comment]
@DoubleLabyrinth 多谢提醒！

**Comment by evenson419** [comment]
@DoubleLabyrinth 你好，我想请问一下navicat data modeler也能通过此方法破解吗？

**Comment by DoubleLabyrinth** [comment]
@evenson419 
原理是一样的，只是部分代码需要修改。

**Comment by tjpanda88** [comment]
生成一个自签名的代码签名证书，并在Keychain.app中总是信任它。

这步能简单说明一下吗？

**Comment by kevinbin** [comment]
一旦激活后，即便联网了，不升级版本也不会失效？

**Comment by DoubleLabyrinth** [comment]
@tjpanda88 
请见issue #69

**Comment by DoubleLabyrinth** [comment]
@kevinbin 
是的

**Comment by tjpanda88** [comment]
@DoubleLabyrinth 
根据issue #69 中提示的网址已经完成注册，非常感谢。
建议您把这个如何生成自签名证书的说明网址也加到Readme中。

**Comment by lioliy** [comment]
here is a tutorial for mac
https://www.notion.so/The-tutorial-for-cracking-Navicat-Premium-12-on-macOS-1d0a893358e64e8bb3b8b2a7dba993b9

**Comment by suifengJC614** [comment]
请求吗输入后Failed to decrypt data.

**Comment by DoubleLabyrinth** [comment]
@suifengJC614 
你有运行patcher吗？

**Comment by suifengJC614** [comment]
@DoubleLabyrinth 
谢谢你的回复，找到原因了，因为没有制作自签名的代码签名证书

**Comment by Dog-Lee** [comment]
开发者你好。

使用钥匙串访问的证书助理创建了证书，但是使用以下命令时提示错误。我用的是Navicat for MySQL 12.0.28。
```
codesign -f -s "Douglas Lee" /Applications/Navicat\ for\ MySQL.app/Contents/MacOS/Navicat\ for\ MySQL
Password:
/Applications/Navicat for MySQL.app/Contents/MacOS/Navicat for MySQL: replacing existing signature
/Applications/Navicat for MySQL.app/Contents/MacOS/Navicat for MySQL: errSecInternalComponent

```

麻烦了。

**Comment by Dog-Lee** [comment]
想问一下Navicat for MySQL 12.0.28 是否能以mac分支下的文档使用？
我遇到一个问题，运行`./navicat-keygen 2048key.pem`得到的NAVA-DR7S-6PFN-DEV5激活码并不能用于激活窗口，[激活]按钮无法点击。

**Comment by DoubleLabyrinth** [comment]
@Dog-Lee 
你可以把navicat-keygen/main.cpp中第93行改成`temp_snKey[7] = 0x68`，然后重新编译keygen并运行试试看

**Comment by TinChiWay** [comment]
版本大于12.0.24

在第二步骤中没有生成pem，但是在第4步骤中却要求使用pem，这里并不是很理解，
运行过patcher，但是最后Failed to decrypt data.
所以当版本大于24时，应该如何打patch和激活？

![image](https://user-images.githubusercontent.com/16657705/46015957-26d11000-c106-11e8-89d8-f573d306620f.png)

**Comment by dushiwang** [comment]
> 想问一下Navicat for MySQL 12.0.28 是否能以mac分支下的文档使用？
> 我遇到一个问题，运行`./navicat-keygen 2048key.pem`得到的NAVA-DR7S-6PFN-DEV5激活码并不能用于激活窗口，[激活]按钮无法点击。

我也是遇到同样的问题 将navicat-keygen/main.cpp中第93行改成temp_snKey[7] = 0x68 重新编译后还是无法点击

**Comment by DoubleLabyrinth** [comment]
@Dog-Lee 
请你仔细理解上下文。我说的第93行改成temp_snKey[7] = 0x68是给Navicat MySQL用的。
如果你的序列号没用，多半是选错了语言。请你在运行keygen时选择正确的语言再试

**Comment by Dog-Lee** [comment]
@DoubleLabyrinth 非常感谢呢，我决定使用premium版本了，mysql不打算了。

**Comment by Dog-Lee** [comment]
@DoubleLabyrinth 非常感谢呢，我决定使用premium版本了，mysql不打算了。所以你介绍的方法我还没去试。

**Comment by DoubleLabyrinth** [comment]
@Dog-Lee 
抱歉我@错人了。

**Comment by dushiwang** [comment]
> @dushiwang
> 请你仔细理解上下文。我说的第93行改成temp_snKey[7] = 0x68是给Navicat MySQL用的。
> 如果你的序列号没用，多半是选错了语言。请你在运行keygen时选择正确的语言再试

感谢回复😀, 我也是用premium的时候发现无法点击激活, 来这边寻找解决方案, keygen语言选择是正确的, 我再试试吧, 可能是姿势不对

**Comment by dushiwang** [comment]
> > @dushiwang
> > 请你仔细理解上下文。我说的第93行改成temp_snKey[7] = 0x68是给Navicat MySQL用的。
> > 如果你的序列号没用，多半是选错了语言。请你在运行keygen时选择正确的语言再试
> 
> 感谢回复😀, 我也是用premium的时候发现无法点击激活, 来这边寻找解决方案, keygen语言选择是正确的, 我再试试吧, 可能是姿势不对

这里有一个坑, 我的系统语言是英文, 但我的navicat安装包是在中文官网上下载的, 打开后界面为英文, 选择中文后成功激活..
