### ISSUE TITLE
navicat 12.0.29 注册不了问题

### ISSUE THREAD

**Issue by GavinAlison** [DoubleLabyrinth/navicat-keygen#88]
环境： win10 x64,  navicat v 12.0.29 x64 ,
注册时候提示 Access violation at address 00007FF89E7C3FED in module 'libeay32.dll'.  Read of address  00000000000018

**Comment by DoubleLabyrinth** [comment]
请附上patcher的输出

**Comment by DoubleLabyrinth** [comment]
@pondcat 
卡住的地方就是要你粘贴navicat给你的请求码，然后回车2次就可以了。

**Comment by pondcat** [comment]
@DoubleLabyrinth ok了
@GavinAlison 我也是win10, 不过是ltsb版, 刚才亲测12.0.29是可用的, 你是不是正开着navicat, 先关了再试试, 或者导出下connection(记得把导出密码勾上), 然后卸载重装再激活试试

**Comment by MrXionGe** [comment]
12.0.29版本，没问题，可以激活的

**Comment by lovelyh521** [comment]
可以的，多式几次。我是从28升级的，一开始不行，卸了装装了卸，最后一次只执行了第一步后准备复制base64码却莫名其妙提示激活了。

**Comment by mackvord** [comment]
前面都没问题，但是在最后贴了邀请码之后，敲两次回车，直接就提示Failed to decrypt request code.解密不了，上面说12.0.29可以激活的是如何做的？

**Comment by mackvord** [comment]
@lovelyh521 OK，我试一下

**Comment by mackvord** [comment]
@DoubleLabyrinth 重装了一遍Navicat，问题已解决，成功激活！

**Comment by GavinAlison** [comment]
谢谢各位了， 我卸载了重新安装，在尝试一遍就成功了，非常感谢！！

**Comment by GavinAlison** [comment]
closes #80

**Comment by DoubleLabyrinth** [comment]
@GavinAlison @pondcat @MrXionGe @lovelyh521 @mackvord 
既然各位都没有问题了，那么本issue暂时关闭
