### ISSUE TITLE
./navicat-keygen 2048key.pem提示权限不足

### ISSUE THREAD

**Issue by AhahaGe** [DoubleLabyrinth/navicat-keygen#89]
你好，
./navicat-keygen 2048key.pem，提示权限不足
加了sudo ./navicat-keygen 2048key.pem，提示找不到命令

![Uploading Screen Shot 2018-06-17 at 9.33.26 PM.png…]()

**Comment by AhahaGe** [comment]
~/Downloads/project/source/navicat-keygen   mac ●  $ ./navicat-keygen 2048key.pem

zsh: command not found: $
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  ./navicat-keygen 2048key.pem

zsh: permission denied: ./navicat-keygen
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  sudo $ ./navicat-keygen 2048key.pem

sudo: $: command not found
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  sudo ./navicat-keygen 2048key.pem
sudo: ./navicat-keygen: command not found
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  sudo ./navicat-keygen navicat-keygen/2048key.pem
sudo: ./navicat-keygen: command not found
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  ./navicat-keygen navicat-keygen/2048key.pem
zsh: permission denied: ./navicat-keygen
 ✘  ~/Downloads/project/source/navicat-keygen   mac ●  clear

**Comment by DoubleLabyrinth** [comment]
1. 请你检查是否有navicat-keygen这个二进制程序存在，如果没有请先编译。
2. 请检查navicat-keygen是否有可执行的属性。如果没有请用chmod +x navicat-keygen添加可执行属性

**Comment by AhahaGe** [comment]
2之前已执行，可能是1的问题，目前已通过其它方式激活，感谢～
