### ISSUE TITLE
您好，mac版破解成功之后数据库密码全记不住了

### ISSUE THREAD

**Issue by xialeistudio** [DoubleLabyrinth/navicat-keygen#90]
1. 已经删除keychain中所有navicat的数据
2. 注册已经成功
3. 勾选了保存密码

下次打开APP的时候提示密码错误，猜测是不是因为替换公钥导致?

**Comment by DoubleLabyrinth** [comment]
readme中我已经说明需要重新做代码签名，至于为什么请见issue #44

**Comment by DoubleLabyrinth** [comment]
由于提问者 @xialeistudio 没有回应，本issue暂时关闭
