### ISSUE TITLE
会新增12.0.29的适配么？

### ISSUE THREAD

**Issue by tonight-love** [DoubleLabyrinth/navicat-keygen#91]

**Comment by DoubleLabyrinth** [comment]
12.0.29是可以用的

**Comment by tonight-love** [comment]
用你编译好的12.0.8 ，提示Unknown version detected, still continue

**Comment by DoubleLabyrinth** [comment]
直接输入y   继续即可
29版本的navicat premium注册算法没变

**Comment by jnwsczh** [comment]
12.0.29 报错，使用的管理员权限执行的。
Warning: Unknown version detected, still continue? [y/n] y
@[BackupFile]: C:\Program Files\PremiumSoft\Navicat Premium 12\libcc.dll has been backed up.
Failed to set target file of BIO. CODE: 0x02001002 @[ReadRSAPrivateKeyFromFile -> BIO_read_filename]
Failed!

**Comment by DoubleLabyrinth** [comment]
@jnwsczh 
错误发生在
```cpp
if (1 != BIO_read_filename(b, temp_filename)) {
    _tprintf_s(TEXT("Failed to set target file of BIO. CODE: 0x%08x @[ReadRSAPrivateKeyFromFile -> BIO_read_filename]\r\n"), ERR_get_error());

    BIO_free_all(b);
    delete[] temp_filename;
    return FALSE;
}
```

应该是找不到私钥文件，也可能是私钥文件损坏或不是合法的私钥文件。麻烦你将输入的命令贴出来

**Comment by jnwsczh** [comment]
执行的命令：navicat-patcher.exe "C:\Program Files\PremiumSoft\Navicat Premium 12" RegPrivateKey.pem

**Comment by jnwsczh** [comment]
可以了。发现命令执行错了。按照52上的来的，没注意看你项目的介绍。
