### ISSUE TITLE
Doesn't work with Navicat 12 for MongoDB

### ISSUE THREAD

**Issue by aazbeltran** [DoubleLabyrinth/navicat-keygen#93]
I tried to activate Navicat for MongoDB (Beta) which handles the same structure as Navicat Premium and did not work

**Comment by DoubleLabyrinth** [comment]
Sorry for my late reply. I will download it and have a check in IDA.

**Comment by Deltafox79** [comment]
@DoubleLabyrinth  @dragonflylee
Product | Ent | Std | Edu | ESS
-- | -- | -- | -- | --
MongoDB | 0x80 | 0x81 | 0x82 | --

**Comment by Deltafox79** [comment]
My Gui v3.6 Fixed for v12.1.4 >

![navicat_mongodb_12 1 4](https://user-images.githubusercontent.com/2518850/43273510-e5535284-90fc-11e8-98ab-162c9c1d3326.jpg)

http://mirr.re/d/Aav

Thank's and Regards

**Comment by dragonflylee** [comment]
Add mongo support too 

[Navicat.zip](https://github.com/DoubleLabyrinth/navicat-keygen/files/2234245/Navicat.zip)

**Comment by AndDontBlink** [comment]
@DoubleLabyrinth Any update? on Navicat premium 12.1-en-x64

**Comment by swikecc** [comment]
@Deltafox79 
can you share your keygen? i can't get it by using this url.

**Comment by Deltafox79** [comment]
@swikecc 
https://www17.zippyshare.com/v/GR8i9Nhj/file.html

**Comment by AndDontBlink** [comment]
@Deltafox79 ¿Why your keygen need admin rights? theres no need for that to patch it

**Comment by Deltafox79** [comment]
@AndDontBlink need for Patched exe file.. before use keygen...

**Comment by wxlg1117** [comment]
@Deltafox79 ,and how can i use this keygen for mac navicat version   generate  a SN key ?

**Comment by Deltafox79** [comment]
@wxlg1117 you can compile  DoubleLabyrinth Patch / keygen or need to use this my cracked version of navicat for mac :

[Navicat_Mac_v12.1.4_En_x64_Incl_Crack_Keygen_v3.7_By_DFoX_URET.zip](https://mega.nz/#!HORkCagY!iRG58O-wGZBgJnzoJfFztjVkwrnIaQC7HSC3UZfPYO4)

and run my keygen under windows for generate correct serial.. pin mac option in keygen before generate serial..

Regards

**Comment by swikecc** [comment]
@Deltafox79 do you have this kind of keygen for mac?

**Comment by ThalesMatoso** [comment]
i need keygen navicat for mongodb to linux, share?
