### ISSUE TITLE
这个不适用Navicat for Mysql mac？

### ISSUE THREAD

**Issue by yywxf** [DoubleLabyrinth/navicat-keygen#95]
Navicat for Mysql mac 12.0.27
![image](https://user-images.githubusercontent.com/19523788/42199446-124b0fd2-7ec1-11e8-850c-d96950f7e6cb.png)

（这个注册码随便输入的），无法点击激活
同样的步骤，我已经激活Navicat Premium 成功！Thanks！

**Comment by DoubleLabyrinth** [comment]
如果要适配navicat mysql必须修改下代码里相应的参数，你可以参照README改下

**Comment by yywxf** [comment]
好的，有空再搞一下，多谢

**Comment by yywxf** [comment]
确实可以了，改参数`temp_snKey[7] = 0x68;`

**Comment by xiaoliwang** [comment]
我碰到同样的问题，我修改了 `data[7] = 0x68;` 参数。但是 `for mysql` 无法激活。`Navicat Premium` 已经激活成功了。

**Comment by DoubleLabyrinth** [comment]
@xiaoliwang 
对于macOS下的情况，我只会维护Premium的激活，其他产品的激活我不会再维护了。主要是Premium完全可以覆盖其他产品的功能。

**Comment by xiaoliwang** [comment]
嗯嗯。我只是在研究你们写的破解文档时，发现了这个问题，所以想具体了解一下。非常感谢您的维护。@DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
data[7]的那个值是另外两个人报告的，我没有具体考证过。我有时间看看吧。
