### ISSUE TITLE
12.0.29 ubuntu 18.04 提示Failed to decrypt request code.

### ISSUE THREAD

**Issue by jingmian** [DoubleLabyrinth/navicat-keygen#97]
`
jingmian@jingmian-TUF:~/down/navicat12-keygen_Win_CHS_x64$ wine ./navicat-patcher.exe /opt/navicat/Navicat/Navicat.exe
/opt/navicat/Navicat/Navicat.exe has been backed up.
Public key has been replaced.
Success!
jingmian@jingmian-TUF:~/down/navicat12-keygen_Win_CHS_x64$ wine navicat-keygen.exe  RegPrivateKey.pem 

SnKey:
NAVM-4ILN-Z45D-NRWU

Your name: jingmian
Your organization: jingmian
Input request code (in Base64), empty line to return:
pf7ZHADWPQaKGmnDvwqRY0sntuef+qTa/sn2ZbWWwRQDwfq/KiiQxYGzfiKKLTWInvew0S2Q5yCA
lTcnHwkhmF8KU6viHR/AQpXVTDXs/588h22ns9bc7VM0x6vS+/no4QY4rOE9AM3oLEnQ6+5B0WdH
TRu/dt1X+SdLpLx+SOygqILgBSiQni96IIGvOILZmCBKnjl1gBnrkgg+ZoJUbcyG97xC29j8dCIE
gpZ9CL5UVNUCO4xYgrvfR5qWMImaSbvZ1ZA4CEMINnfUmG7B38qSZ2B47IJAzjWcKnKdgE7BG8zb
LuWOal5Mo4pwVn/CRYzDyPjyOMGmQ6tJiSs3pw==

Failed to decrypt request code.
`
我的版本是Navicat Premium Linux 12.0.29
[截图](https://s1.ax1x.com/2018/07/04/PVSHFH.png)

**Comment by DoubleLabyrinth** [comment]
你的keygen是很早的版本了，请到release里下载最新的，然后照着最新的README做。和windows的一样，只是都是在wine环境

**Comment by jingmian** [comment]
`
jingmian@jingmian-TUF:~/down/navicat-keygen_for_x64$ wine navicat-keygen.exe RegPrivateKey.pem 
Which is your Navicat language?
0. English
1. Simplified Chinese
2. Traditional Chinese
3. Japanese
4. Polish
5. Spanish
6. French
7. German
8. Korean
9. Russian
10. Portuguese

(input index)>1

SnKey:
NAVO-G5QX-5VIP-ZTUQ

Your name: jingmian  
Your organization: jingmian
Input request code (in Base64), empty line to return:
vFsN8dzRo4ipKq2CMC9g0FHAwqVxnzKgYCf2FOS9+goz8XvhaW6+xvo07nCfvrKEdAx8NZ9s3MFc
Q3t3jqx/+hcok6lzAdj1C35XZiZxjggtHZ2Srfg4lVZxVNVv0rCyzQBdyqMdwRkK9hlC08+DIbA/
tSHCX4zZNFxBz3nO4UVa4MpssUh8MQarJ5y1rGF5GM7HThhaJxlAsxK5t//x7UCpddCwirUeFQWd
dQi43TaVQrfW/q9oweKNnUDwtTn8F7ff75LTnLiJ5aciT+fz0HXFyqgtNzKu2beVLghsClsdyxa6
IX3LtxhHZXpS1UxHtJiZ30uqq1Lp+GpWUpNlwQ==

Failed to decrypt request code.
jingmian@jingmian-TUF:~/down/navicat-keygen_for_x64$ 
`
已经下载最新release的Support for 12.0.28，可是我版本是12.0.29，可以不
另外我重新删除你的 RegPrivateKey.pem,
通过wine navicat-patcher说不是一个路径,我navicat确实安装在这里的
`
jingmian@jingmian-TUF:~/down/navicat-keygen_for_x64$ wine navicat-patcher.exe /opt/navicat/Navicat/Navicat.exe
Error: Path is not a directory.
jingmian@jingmian-TUF:
`
[截图](https://s1.ax1x.com/2018/07/05/PVrleH.png)
[版本截图](https://s1.ax1x.com/2018/07/05/PVrMOe.png)

**Comment by DoubleLabyrinth** [comment]
navicat-patcher需要的是navicat.exe所在目录的路径，不是navicat.exe的路径。请你再仔细看README

**Comment by jingmian** [comment]
真牛，可以了，哈哈

**Comment by DoubleLabyrinth** [comment]
旧版的我也不知道在哪下，你还是问问别人有没有旧版的存档吧

**Comment by jingmian** [comment]
好的，谢谢了
